### ISSUE TITLE
finagle-stream will accept chunks that are too large

### ISSUE THREAD

**Issue by mariusae** [twitter/finagle#156]
Dave Corocoran, @mariusaeriksen:

>> I noticed something a little strange with the finagle Stream codec. I'll explain with references to your Hosebird/StreamServer example.
>>
>> In the StreamServer example the method 'produce' creates a buffer which is offered to StreamResponse.mesages. If this buffer is larger than 8192 bytes (the default maxChunkSize for HttpClientCodec and HttpServerCodec) it will be sent as mulitple Http Chunks. This is probably ok but the problem is that the client will get multiple messages.
>>
>> I would expect that if you send a single message on the server it would appear as a single message on the client, and therefore the client doesn't have to know anything about chunk sizes. This would mean the finagle HttpDechunker might have to combine multiple chunks at times.
>>
>> For now I've worked around this by increasing the maxChunkSize. Do you think this is a job for the Stream Codec, or is it more like application layer code?
> 
> This highlights an unfortunate — though probably pragmatic — design decision in Hosebird: it uses chunks for *framing*. The application shouldn't need to know anything about chunk boundaries. For streaming discrete items, it's always better to provide your own envelope.
> 
> Put another way: the application should be able to read the HTTP body as a stream, and delimit items further up the stack.
>
> But now that we're in this mess, you're right. This is bad behavior. We should probably reject such messages.

**Comment by luciferous** [comment]
I believe we're not going to tackle this in finagle-stream. HTTP streaming should be using finagle-http/x with streaming enabled.
