### ISSUE TITLE
org.apache.thrift#libthrift;0.5.0 doesn't exist

### ISSUE THREAD

**Issue by mergeconflict** [twitter/finagle#158]
Given the following:

``` scala
libraryDependencies ++= Seq(
  "com.twitter" %% "finagle-thrift" % "6.3.0"
)
```

I get:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.apache.thrift#libthrift;0.5.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

due to: https://github.com/twitter/finagle/blob/master/finagle-thrift/pom.xml#L19

The correct groupId for this version of `libthrift` should be `org.apache.hadoop`. See also issues #58, #70 and #133.

**Comment by hellokangning** [comment]
```
resolvers += "Twitter maven" at "http://maven.twttr.com/"
```

However, the following does NOT work

```
resolvers += "Twitter maven" at "http://maven.twttr.com"
```

**Comment by mosesn** [comment]
@hellokangning if you use a new version of finagle, you won't have to depend on maven.twttr.com at all.  see this [blog post][0] for more details.

[0]: https://finagle.github.io/blog/2016/11/29/central-libthrift/
