### ISSUE TITLE
Cannot find document about load balance, failure detection, backpressure

### ISSUE THREAD

**Issue by netease-datastream** [twitter/finagle#166]
I have installed finagle-zipkin and finish a simple demo.

In construction of finagle I found the finagle client have such features:
1.Load balance
2.Failure detection
3.Retry/Failover
Server have such feature:
1.service registration
2.BackPressure

But I cannot find document about these features in 
http://twitter.github.io/finagle/guide/

I wonder where can I get more document about these advanced features?

Look forward to your reply.

**Comment by mosesn** [comment]
The documentation in the user guide has improved significantly.  I'm going to mark this as fixed.

http://twitter.github.io/finagle/guide/Clients.html
