### ISSUE TITLE
Finagle client doesn't deal well with servers that "Connection: close"

### ISSUE THREAD

**Issue by robstar-nest** [twitter/finagle#167]
It appears that when using a ClientBuilder to access a service that closes connections after requests, Finagle emits ChannelClosedExceptions:

    com.twitter.finagle.ChannelClosedException: ChannelException at remote address: localhost/127.0.0.1:8083
        at com.twitter.finagle.NoStacktrace(Unknown Source)

The gist at https://gist.github.com/robstar-nest/5624388 emits "." for successful requests and "E" for requests that errored out. When run normally (e.g.  sbt run) it prints 5000 dots and is happy. When told to close connections (e.g. sbt "run --close") it emits a significant number of "E"s.  (note that the quotes are important in geting the program to see that "--close")

I ran this (and saw the described errors) on:
- Linux ubuntu 2.6.32 / Java HotSpot(TM) Server VM, Java 1.6.0_31
- MacOS X 10.8 / Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_17

Suggestions? Work-arounds? Is this a Finagle bug?

**Comment by mosesn** [comment]
Looks like this bug was fixed.  Marking this issue as done.
