### ISSUE TITLE
Response.decodeString forces isChunked=true and content=empty

### ISSUE THREAD

**Issue by jdanbrown** [twitter/finagle#174]
Looks pretty severe, so maybe I'm just misunderstanding it? I'm using finagle-core_2.9.2-6.4.1.
```
scala> import com.twitter.finagle.http._
import com.twitter.finagle.http._

scala> val rep = Response()
rep: com.twitter.finagle.http.Response = Response("HTTP/1.1 200 OK")

scala> rep.contentString = "foo"
rep.contentString: String = foo

scala> rep.isChunked
res22: Boolean = false

scala> println(rep.encodeString)
HTTP/1.1 200 OK

foo

scala> val rep2 = Response.decodeString(rep.encodeString)
rep2: com.twitter.finagle.http.Response = Response("HTTP/1.1 200 OK")

scala> rep2.contentString
res24: String = ""

scala> rep2.isChunked
res25: Boolean = true

scala> println(rep2.encodeString)
HTTP/1.1 200 OK
Transfer-Encoding: chunked



scala>
```

**Comment by luciferous** [comment]
What's the issue here? `decodeString` consumes the `HttpMessage` and will mutate it. It has to in order to guarantee the return type.

**Comment by jdanbrown** [comment]
Haven't thought about this issue in a couple years, but reading back over it I think that "consumes the HttpMessage", if that's intentional, is a surprising behavior.

**Comment by luciferous** [comment]
I don't like the API and how it's been communicated. It's not unreasonable that you're surprised, however, can I understand a little more about how you're intending to use encode/decodeString?

**Comment by jdanbrown** [comment]
I don't remember well at this point, but I vaguely remember trying to copy `Request`s, maybe for tests, and seeing if `Response.decodeString(rep.encodeString)` would accomplish that, and then ultimately concluding that `Request`s weren't meant to be copied and finding a different approach.

**Comment by mosesn** [comment]
Looks like this is a confusing API in finagle-http.  We're planning on simplifying the Request and Response APIs, so hopefully that will improve matters here.  I think this works as expected though, so I'm going to close this issue.
