### ISSUE TITLE
Allow retrieval of client certificate

### ISSUE THREAD

**Issue by bpfoster** [twitter/finagle#175]
When using client auth with 2-way SSL, present the client certificate for custom authorization code to use.  The result should be something similar to the call of `SSLEngine.getSession().getPeerCertificateChain()`

Originally posted in the users group at https://groups.google.com/forum/?fromgroups#!topic/finaglers/j4xrFRF1MDI

**Comment by danielpcox** [comment]
Does this commit on develop: https://github.com/twitter/finagle/commit/3d6f236f and the fact that Thrift RPC is now supported over TLS close this question?

**Comment by mosesn** [comment]
I think so?  Have you done this by any chance :P

**Comment by danielpcox** [comment]
Not yet, but it's on my list. :) I'll give it a shot next week and let you know.

**Comment by danielpcox** [comment]
Make that the next three weeks... I'm pretty distracted at the moment. @mosesn would you be able to try it out? At the moment, I expect to be able to circle back around and confirm that this solves our problems by the end of next week, but anybody with some time to kill right now could pull develop and try extracting a client certificate over TLS via Thrift and HTTP.

I think you'd just have to write a little demo ping server that uses TLS and grabs some attribute out of the client cert, and then write a client to connect to it with any certificate.

**Comment by mosesn** [comment]
End of next week is fine, I don't think anyone needs this more urgently than you do (and if they do, they can run their own tests :P)

**Comment by danielpcox** [comment]
OK, I'm finally getting around to this now. I think I'm misunderstanding something fundamental, though. How do I actually get ahold of the Transport from inside a service's request handler? How can I do anything with the client's incoming certificate information so as to affect the response?

**Comment by mosesn** [comment]
Looks like you should be able to call [`Transport.peerCertificate`][0] on the serverside.

I don't think it's officially deprecated yet, but we're [gently encouraging folks][1] to use the finagle-6 style APIs.

[0]: https://github.com/twitter/finagle/commit/3d6f236f#diff-d274cdcb169a7b7dbb5b2e81f9ea4959R93
[1]: http://twitter.github.io/finagle/guide/FAQ.html#how-do-i-configure-clients-and-servers-with-finagle-6-apis

**Comment by danielpcox** [comment]
I'm sorry Moses, I still don't understand. How do I get a handle on the Transport object from within a server implementation? I've read all the documentation and I still only know how to do the most common things. I'm implementing a Thrift IDL-defined interface, and I don't see how the transport object could be injected at this point.

**Comment by mosesn** [comment]
Have you tried calling `Transport.peerCertificate`?  Or is your question about how to invoke the method?  Transport is an object, so it's available globally.

**Comment by danielpcox** [comment]
How can something available globally present me with the certificate for an individual request like this? Is it a thread-local binding or something? This must be the key thing I was missing. Does finagle expose many things this way?

**Comment by mosesn** [comment]
It doesn't expose many things this way, but it does for a few things, like Traces.  It's a context that gets threaded through your execution context when you do things like Future#map.  Most users don't ever need to use the Local mechanism directly (we consider it an expert feature), so we don't document it explicitly.  It should "just work" in the majority of cases.

**Comment by danielpcox** [comment]
Transport.peerCertificate seems to be None at this point in my server implementation. Am I doing anything obviously wrong here? https://github.com/DecipherNow/finagle-tls/blob/master/src/main/scala/com/twitter/finagle/example/tls/TLSServer.scala#L23

Thanks Moses for your patience.

**Comment by bpfoster** [comment]
@danielpcox 
- The big issue is the ```tls()``` method in Finagle does not expose a way to configure the engine to want or need client authentication.  The default is for neither, so the server will never even prompt the client to present a certificate.  You're going to need to create your own engine and use ```newSslEngine()``` instead of ```tls()```, and specify whether you want or need client auth in the engine.  For example:
```
val server = ServerBuilder()
      .codec(ThriftServerFramedCodec())
      .newSslEngine(() => {
          val engine: SSLEngine = createSslContext().createSSLEngine()
          engine.setNeedClientAuth(true)
          engine
       })
      .bindTo(new InetSocketAddress(8080))
      .name("TLSServer").build(service)
```
The finagle native OpenSSL bindings don't currently support specifying client auth modes, so I ended up creating a javax.net.ssl.SSLContext (similar to the Client) to get an SSLEngine.  In theory performance may be worse than via native.

- Your sample certificate has expired so I couldn't get a successful handshake with it.  Generating a new one worked.


With those 2 in mind, I was able to then run your code and get back what looks like a good response:
BeautifulDogResponse(O=Internet Widgits Pty Ltd,ST=Some-State,C=AU,true)

- When you move off the old API, I believe you can configure TLS similar to
```
Thrift.server.configured(Transport.TLSServerEngine(Some(ssl.newEngine)))
```

**Comment by danielpcox** [comment]
Thank you @bpfoster, I really appreciate this. Moses helped me earlier today with the new API, and my experiments are here: https://github.com/DecipherNow/finagle-tls/blob/new-api/src/main/scala/com/twitter/finagle/example/tls/TLSServer.scala

The certificate is expired... That explains why the client was hanging. Bah. I forked this project from someone else and didn't check how old it was.

I'll try to catch up to you tomorrow. :) Thanks again.

**Comment by danielpcox** [comment]
All right, I was able to confirm that these changes provide access to the client certificate with the right incantations, though I was never able to get it working with the new API. I'll file a separate issue about that.

**Comment by mosesn** [comment]
Rad, then I'll mark it as solved :]
