### ISSUE TITLE
Implement a ZooKeeper client purely in Finagle

### ISSUE THREAD

**Issue by caniszczyk** [twitter/finagle#186]
Creating an issue to track Radu's work for GSOC:
https://github.com/twitter/twitter.github.com/wiki/Google-Summer-of-Code-2013#finagle-zookeeper-client

**Comment by vkostyukov** [comment]
I'm pretty sure this is about [finagle-zookeeper](https://github.com/finagle/finagle-zookeeper). So we can probably close this.
