### ISSUE TITLE
What is the proper way to set the timezone of datetime columns in finagle-mysql?

### ISSUE THREAD

**Issue by eric** [twitter/finagle#190]
finagle-mysql [writes DATETIME and TIMESTAMP columns in the current timezone](https://github.com/twitter/finagle/blob/master/finagle-mysql/src/main/scala/com/twitter/finagle/mysql/Value.scala#L168) and does not provide a way to specify a timezone (or force them to be in UTC).

Is this intentional? Are there plans to provide a way to force them to be sent in UTC?

**Comment by mosesn** [comment]
I think this is a solid starter issue.  We might be able to rehydrate #191, add a test and merge it in.

**Comment by vtatai** [comment]
@mosesn I will take a stab at it, hopefully will be able to get some progress.

**Comment by mkantor** [comment]
Unless I'm misunderstanding it looks like this was solved way back in 2014 with 4258d70f60c956e6c6f361f84d84ef1a6e2b38dc.

**Comment by eric** [comment]
Looks like this would work great to solve the problem. I’m not using finagle anymore but I’m glad this has a solution. 🎉

**Comment by kevinoliver** [comment]
As noted [above](https://github.com/twitter/finagle/issues/190#issuecomment-345471631), this was fixed [back in 2014](https://github.com/twitter/finagle/commit/4258d70f60c956e6c6f361f84d84ef1a6e2b38dc).
