### ISSUE TITLE
Netty 4 migration

### ISSUE THREAD

**Issue by okapies** [twitter/finagle#204]
Is there any plan to bump the netty to version 4? I know it includes many API changes.

http://netty.io/wiki/new-and-noteworthy.html

**Comment by note** [comment]
Any news on this subject?

**Comment by dschobel** [comment]
@note no new developments, work is still actively underway internally but we've intentionally taken the longer path of removing netty types from our protocols' public api to make future upgrades easier.

**Comment by futurely** [comment]
That's how Google's gRPC [avoids exposing netty in the public API](https://github.com/grpc/grpc-java/tree/master/netty/src/main/java/io/grpc/transport/netty).

**Comment by luciferous** [comment]
Still in progress. This isn't really an issue, so I'm going to close it.

**Comment by daqulazhang** [comment]
I'm wonderring is this netty4 integration work done?

**Comment by vkostyukov** [comment]
@daqulazhang it's still in progress, but the first Netty 4 bits are already [here](https://github.com/twitter/finagle/tree/develop/finagle-netty4). The Netty 4 work is on track and we except to finish finagle-core in Q1 2016 so we could move to work on protocols (Mux and HTTP will probably be first).

**Comment by eshelestovich** [comment]
Any updates on this, folks ? As far as I can see, latest finagle-core_2.11:6.39.0 still depends on netty-3.10.1.Final.

**Comment by dschobel** [comment]
@eshelestovich we have implementations of most of our protcols on netty4 but the dependency on netty3 will be there for a little while longer as we clean up internals. There is no public api that depends on netty3 however.

**Comment by mosesn** [comment]
@eshelestovich one thing that helps us here is that netty 3 is in a different namespace from netty 4, so finagle-core can still depend on netty 3 but use netty 4 under the hood.

**Comment by vkostyukov** [comment]
I decided to update this epic thread.

As of Finagle 6.42, it's now possible to switch the underlying transport implementation over to Netty 4 for **all supported protocols**. See more details [in this blog post](https://finagle.github.io/blog/2017/02/06/finagle-loves-netty4/).
