### ISSUE TITLE
ChannelClosedExceptions on a single-core host

### ISSUE THREAD

**Issue by anttipoi** [twitter/finagle#211]
I observe a problem on single-core servers where running local finagle client + server combo often results in ChannelClosedExceptions. Adding cores to my virtual box makes the problem go away.

I've distilled this problem to a simple test application, available at https://github.com/anttipoi/ftest
	
I've previously discussed this on the finaglers group where there is some more information on this: https://groups.google.com/forum/#!topic/finaglers/2pOiEWgKCyw

Statistics for the correct and erroneous runs are available in the discussion thread. Much thanks for Ruben and Marius for debugging help.

I can add a custom RetryPolicy to retry all exceptions but the default retry policy that captures just WriteExceptions does not work. It seems these axceptions are not wrapped in WriteExceptions.

I encountered the issue at a customer project where test boxes are single-core virtual machines.

**Comment by mosesn** [comment]
@anttipoi your test project doesn't compile for me locally.

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=utf8
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ftest 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://artifactory.local.twitter.com/repo/org/scala-tools/maven-scala-plugin/2.15.2/maven-scala-plugin-2.15.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.746 s
[INFO] Finished at: 2015-02-04T14:59:34-05:00
[INFO] Final Memory: 7M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.scala-tools:maven-scala-plugin:2.15.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.scala-tools:maven-scala-plugin:jar:2.15.2: Could not transfer artifact org.scala-tools:maven-scala-plugin:pom:2.15.2 from/to Twitter (http://artifactory.local.twitter.com/repo): hostname in certificate didn't match: <artifactory.local.twitter.com> != <*.twitter.biz> OR <*.twitter.biz> OR <twitter.biz> -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by anttipoi** [comment]
I'm sorry, I've long since moved to other projects. 

We ended up giving up on finagle (not just for this reason).

**Comment by mosesn** [comment]
Ah, good luck!
