### ISSUE TITLE
Support reading params in content body for HTTP methods other than POST

### ISSUE THREAD

**Issue by ngocdaothanh** [twitter/finagle#215]
Currently, PUT, PATCH, and DELETE are not supported:

https://github.com/twitter/finagle/blob/master/finagle-http/src/main/scala/com/twitter/finagle/http/ParamMap.scala#L173

```scala
if (request.method == Method.Post &&
    request.mediaType == Some(MediaType.WwwForm) &&
    request.length > 0) {
  parseParams("?" + request.contentString)
} else {
  ParamMap.EmptyJMap
}
```

**Comment by mosesn** [comment]
I think @jeffreyolchovy's patch fixes this, closing this for now.  Please reopen if there are still issues.
