### ISSUE TITLE
Should FailureAccrualFactory accrue failures for cancelled futures?

### ISSUE THREAD

**Issue by ticktock** [twitter/finagle#22]
When using failureAccrualParams in the ClientBuilder, the FailureAccrualFactory that wraps the underlying factory accrues failures for futures that are canceled.

This probably isnt desirable for usage patterns where you are doing something like

    val (first, rest) = Future.select(futures).get() 
    rest.foreach(_.cancel)

I see there is a TODO in FaulureAccrualFactory to enhance this type of behavior, so just mentioning it as a case that should be handled.

**Comment by mosesn** [comment]
We can now use ResponseClassifiers to choose whether to handle different successes or failures as failures or not, so I think we can mark this one as fixed.
