### ISSUE TITLE
high memory utilization in RequestSemaphoreFilter 

### ISSUE THREAD

**Issue by azenkov** [twitter/finagle#241]
I was profiling finagle server to find a a reason for OOM exception we saw on or production servers. I was able to narrow it down to RequestSemaphoreFilter. We are using .maxConcurrentRequests(4)  on our ServerBuilder.
Looks like the reason for a high memory consumption is that RequestSemaphoreFilter holds references to request object for way too long. Our requests can get very big in hundreds of MB and when RequestSemaphoreFilter kepps holding hundreds of request objects in its waitq ArrayDeque server crushes with OOM. 
Is this expected behavior or a bug?

we saw a big jump in memory utilization. After profil

**Comment by mosesn** [comment]
We still don't have a great solution for this, but this ticket is mostly a red herring.  I'm going to close it for now.  Thanks for the great discussion, @azenkov!
