### ISSUE TITLE
Issue trying to get connection status

### ISSUE THREAD

**Issue by rodrigodealer** [twitter/finagle#259]
I'm trying to get the connection status, but when I do:
redis(Info(StringToChannelBuffer("")))

It returns sometimes a Success when the connection is up and a Success when the connection is down.

Any ideas?

**Comment by mosesn** [comment]
@rodrigodealer are you still seeing this behavior?

**Comment by rodrigodealer** [comment]
No, it's working fine now.

**Comment by mosesn** [comment]
:+1:
