### ISSUE TITLE
DefaultClient doesn't close bound dest Var (again)

### ISSUE THREAD

**Issue by sirmax** [twitter/finagle#260]
It's a bugreport to the fix that was implemented in #240.

In `com.twitter.finagle.client.DefaultClient#newStack0` there is now
```
new DelayedFactory(f) {
  override def close(after: Duration) =
    Future.join(Seq(observation.close(after), super.close(after)))
}
```
This `close` won't be called from `ProxyServiceFactory.close` and the like. 
`Closable.close(deadline: Time)` should be overridden instead since it's the method that gets called ultimately, while overloaded `close(after)` simply delegates it.

BTW it may be worth to make overloaded `close(after: Duration)` `final` even if this means a major version bump.

**Comment by mosesn** [comment]
This was fixed a while ago. Thanks again for pointing it out!

https://github.com/twitter/finagle/commit/38b334f431916ef5ca0765f4db588a945a47874e
