### ISSUE TITLE
ExceptionFilter does not set the response content-length

### ISSUE THREAD

**Issue by mmollaverdi** [twitter/finagle#261]
The http ExceptionFilter class calls response.clearContent() but neither the filter, nor "response.clearContent" method set the content-length header to 0.
AWS load balancers are sensitive to missing content-length headers and translate such responses to 502 (Bad gateway) responses.

**Comment by mosesn** [comment]
@mmollaverdi is this still a problem for you?

**Comment by mmollaverdi** [comment]
No, I made a pull request to fix it a while ago and it got merged.
https://github.com/twitter/finagle/pull/266

**Comment by mosesn** [comment]
oh lol.  Looks like I reviewed it, but forgot there was an issue attached.  Closing now, as it had a happy ending :smile_cat:

**Comment by mmollaverdi** [comment]
:+1:
