### ISSUE TITLE
finagle-memcached, all "get" are transformed into "gets" which seems invalid with memcachedb ?

### ISSUE THREAD

**Issue by lerouxrgd** [twitter/finagle#269]
Refering to this :

https://github.com/twitter/finagle/blob/master/finagle-memcached/src/main/scala/com/twitter/finagle/memcached/protocol/text/Show.scala#L83

It seems that all "get" are transformed to "gets" in the implemented memcached protocol.

I am trying to use finagle-memcached with MemcacheDB.
The client calling part of the client code looks like this :
List<String> getBatch = new ArrayList<String>(new String [] {"a","b","c","d"});
Map<String, ChannelBuffer> result = memcachedbClient.get(getBatch).get();
Which is transformed into :
gets a b c d
instead of
get a b c d
With MemcacheDB I get a NonexistentCommand for gets

**Comment by mosesn** [comment]
This was fixed [ages ago][0] :100:.  Thanks @lerouxrgd!

[0]: https://github.com/twitter/finagle/commit/8f62f5d43ad7b9c6a982825441370dfd5027810c
