### ISSUE TITLE
Support for Redis scripting commands

### ISSUE THREAD

**Issue by travisbrown** [twitter/finagle#272]
[finagle-redis](https://github.com/twitter/finagle/tree/master/finagle-redis) currently only supports a subset of Redis commands. Adding [`EVAL` and the related Lua scripting commands](http://redis.io/commands/eval) would make some operations more convenient and efficient.

See [this mailing list thread](https://groups.google.com/d/msg/finaglers/CR17XdpnOWw/JInWl3hBqTEJ) for more context and discussion. You can find the currently supported commands [here](https://github.com/twitter/finagle/blob/master/finagle-redis/src/main/scala/com/twitter/finagle/redis/protocol/Command.scala).

**Comment by timxzl** [comment]
I have a fully functional extension to finagle-redis that supports EVAL, EVALSHA, and other scripting commands. would be happy to share if it's interesting to folks.

**Comment by mosesn** [comment]
Yeah, would definitely love to merge it in!

**Comment by timxzl** [comment]
excellent! I have just created a pull request.

**Comment by timxzl** [comment]
@mosesn I have managed to make the [pull request 381] (https://github.com/twitter/finagle/pull/381) pass all the tests on travis CI. feel free to contact me if you find any problem with it.

**Comment by mosesn** [comment]
Thanks a lot for tackling this in https://github.com/twitter/finagle/pull/383 @timxzl!
