### ISSUE TITLE
Update sbt installation instructions in the quickstart

### ISSUE THREAD

**Issue by travisbrown** [twitter/finagle#275]
The Finagle [quickstart page](http://twitter.github.io/finagle/guide/Quickstart.html) currently includes a `curl` command for downloading the `sbt` script that uses a defunct `raw.github.com` URL.

The URL should be changed to point to the new `raw.githubusercontent.com` domain.

**Comment by tyleranton** [comment]
Is this already being taken care of?

**Comment by travisbrown** [comment]
Yes—[this commit](https://github.com/twitter/finagle/commit/ce64fb1b5168d7012edf5360f0c7fb2637042f82) fixes the version updating issue, and [this PR](https://github.com/twitter/finagle/pull/338) fixes the domain name (but still needs to be pulled internally; I'm taking care of that now).

**Comment by tyleranton** [comment]
Alright, just checking! Thanks.

**Comment by dschobel** [comment]
@travisbrown I just posted #338 internally

**Comment by travisbrown** [comment]
Yep, just shipit-ed—thanks @dschobel.

**Comment by tenaciousRas** [comment]
was this supposed to fix https://twitter.github.io/finagle/guide/Quickstart.html ?

**Comment by vkostyukov** [comment]
@travisbrown Is this closable?

**Comment by travisbrown** [comment]
Fixed by #338 (thanks, @bmckown, @vkostyukov).
