### ISSUE TITLE
finagle-*: scala 2.11 compatibility

### ISSUE THREAD

**Issue by mosesn** [twitter/finagle#290]
It looks like several people are interested in converting finagle over to scalatest.  Since finagle has many small projects, and @p-antoine has already done the biggest chunk, finagle-core, I'm optimistic that we can be done with this quickly.

## coordination

Here are the 
finagle-benchmark :heavy_check_mark:
finagle-commons-stats :heavy_check_mark:
finagle-core :heavy_check_mark:
finagle-example :heavy_check_mark:
finagle-exception :heavy_check_mark:
finagle-exp :heavy_check_mark:
finagle-http :heavy_check_mark: @adamdecaf
finagle-kestrel :o: @chester89
finagle-mdns :heavy_check_mark:
finagle-memcached :heavy_check_mark: @rlazoti 
finagle-mux :heavy_check_mark:
finagle-mysql :heavy_check_mark:
finagle-native :heavy_check_mark: @adamdecaf 
finagle-ostrich4 :heavy_check_mark:
finagle-protobuf :heavy_check_mark:
finagle-redis :o: @penland365
finagle-serversets :heavy_check_mark:
finagle-spdy :heavy_check_mark:
finagle-stats :heavy_check_mark:
finagle-stream :o: @bajohns
finagle-stress :heavy_check_mark:
finagle-swift :heavy_check_mark:
finagle-test :heavy_check_mark:
finagle-testers :heavy_check_mark:
finagle-thrift :o: @bajohns
finagle-thriftmux :heavy_check_mark:
finagle-validate :heavy_check_mark:
finagle-zipkin :heavy_check_mark:

If we could coordinate our efforts, that would be super awesome.

@penland365 has already staked a claim to finagle-redis.  If there's a project that you want to work on, please post on this thread!

If someone is working on something you want to help with, please get in contact with them, make sure they're OK with you helping out, and then get in contact with us.

## tips
1. Follow the [CONTRIBUTING][0] guidelines.
2. Make sure your test works with JUnit (see other scalatest tests to see how to go about doing it).
3. Test with 2.9.2, 2.10.x, and 2.11.x.  They need to all work for your submission to be accepted.
4. Make sure your scalatest versions are lined up properly.  It seems like scalatest has stopped making new versions for 2.9.2, and the earliest scalatest_2.11 is after that cutoff, so there will have to be two scalatests.
5.  Remove the specs dependency from your project to be 100% sure that you're no longer depending on it.
6.  Don't touch the maven or pants files, we'll do it on our end.
7.  Please rename scalatest-ified classes and file names from XSpec to XTest
8.  For mocking, please use [org.scalatest.mock.MockitoSugar][1].
9.  If you have a question about something, look around the rest of the repo to see how it's done.  If you still have questions, reach out on this thread.

[0]: https://github.com/twitter/finagle/blob/master/CONTRIBUTING.md
[1]: http://doc.scalatest.org/2.2.0/#org.scalatest.mock.MockitoSugar

**Comment by hgfischer** [comment]
Hello,

I would like to know the status of the remaining packages/modules that needs to be updated to Scala 2.11.

cheers

**Comment by travisbrown** [comment]
Hi @hgfischer. Most subprojects have been published for 2.11, and everything except finagle-redis is available in the `develop` branch, which means they've been updated internally and will be available in the next release. finagle-redis is [done](https://github.com/twitter/finagle/pull/331) but is not yet merged internally (it's a big changeset).

**Comment by dnatic09** [comment]
@travisbrown , is Ostrich 2.11 on the roadmap too?

**Comment by travisbrown** [comment]
@dnatic09 Yep, Ostrich has been [updated for 2.11](https://github.com/twitter/ostrich/commit/a2028005160c6262cb21be5a322168980a03f900) internally and is just waiting for the next release.

**Comment by rodrigodealer** [comment]
Can finagle-redis be merged?

**Comment by ckampfe** [comment]
Any movement on finagle-redis?

**Comment by penland365** [comment]
@ckampfe @rodrigodealer You can blame me for that - I bit off too large of a change when we did the port to `scalatest` and the PR is bit of handful for the internal team. The dev work has been completed, but finding the time to actual get "All the Things":tm: done has been a challenge.

**Comment by mosesn** [comment]
in defense of @penland365 it has actually been merged internally, we just need to publish and push the code to github.  There's a problem with our ssh keys that we're trying to sort out.  I'll try to figure out what still needs to be done.

**Comment by ckampfe** [comment]
@penland365 @mosesn no worries at all and sincere thanks for your hard work. Was just curious!

**Comment by csaltos** [comment]
Thank you @penland365 and @mosesn for your work. Looking forward for finagle-redis for Scala 2.11.

**Comment by rodrigodealer** [comment]
@penland365 No problem, ping us when you have any news about finagle-redis. Thank you for your work.

**Comment by beenokle** [comment]
@penland365 @mosesn Hey guys, are there any updates on finagle-redis?

**Comment by travisbrown** [comment]
@beenokle The migration to ScalaTest is done and is available in the `develop` branch, and finagle-redis_2.11 will be in the next release (which is likely to be out this week or next).

**Comment by rodrigodealer** [comment]
:shipit: :heart:
