### ISSUE TITLE
StreamResponse.release is not triggered

### ISSUE THREAD

**Issue by takc923** [twitter/finagle#301]
StreamResponse.release is not triggered on master( 1ac2ce7657fd5952a92049a745945fe800c87fb5 )

## Steps to reproduce

1. `sbt "project finagle-example" run`
2. input 2, and enter.
3. `curl http://localhost:8080/` from another terminal and Control-c to disconnect.

## Expected result
This code is called

- https://github.com/twitter/finagle/blob/1ac2ce7657fd5952a92049a745945fe800c87fb5/finagle-example/src/main/scala/com/twitter/finagle/example/stream/StreamServer.scala#L58-L63

## Actual result
The code was not called

## Note
When I did the steps on b071b3e9a6a457abff9d052ed29c03d7709d582b, StreamResponse.release was triggered.

I think the cause is ab3253d59f113a9e3acc0dbfaaf9e132a74b779d but don't know how to fix it.

Thanks

**Comment by luciferous** [comment]
`Http.client.withStreaming(enabled = true)` has been supported for a few months now.
