### ISSUE TITLE
Client configuration examples in FAQ don't work

### ISSUE THREAD

**Issue by travisbrown** [twitter/finagle#324]
The answer to [this question](http://twitter.github.io/finagle/guide/FAQ.html#how-do-i-configure-clients-and-servers-with-finagle-6-apis) needs some attention: `apply` should get called on `ClientBuilder`, the `fetchUrl` example shouldn't use HTTPS (see #323), and other code should be checked.

**Comment by luciferous** [comment]
is this closable?
