### ISSUE TITLE
Setting the content should automatically set the content-length on com.twitter.finagle.http[x].Message

### ISSUE THREAD

**Issue by vicentealencar** [twitter/finagle#335]
The code snippet below, when executed, prints `false`, since `contentLength` returns the value from the Content-Length header (which hasn't been set), and `length` returns the actual byte size of the content. Is there a reason why the contentLength header isn't automatically set when the content is changed?

I ran into issues when trying to use the `Request` class for writing test cases. My requests kept getting rejected by the service and it took me a long time to find out this was the reason. Setting `request.contentLength = request.length` solved the issue for me.

```scala
import com.twitter.finagle.http.{Method, Request, Status}
import org.jboss.netty.buffer.ChannelBuffers.copiedBuffer
import org.jboss.netty.util.CharsetUtil.UTF_8

val request = Request("/test")
request.method = Method.Post
request.content = copiedBuffer("{\"test\": 123", UTF_8)
request.setContentTypeJson
println(request.contentLength.getOrElse(0) == request.length)
```

**Comment by mosesn** [comment]
@luciferous could you weigh in?  I don't know what our policy is on this.

**Comment by luciferous** [comment]
The client dispatcher should set the content length for requests. See [HttpClientDispatcher.scala#39](https://github.com/twitter/finagle/blob/master/finagle-http/src/main/scala/com/twitter/finagle/http/codec/HttpClientDispatcher.scala#L39). If it's not being set, then that's a bug.

@vicentealencar is this consistent with what you're seeing?

`request.contentLength` is misleading,  it's actually a convenience method to view the content length header, have a look at [the definition](https://github.com/twitter/finagle/blob/master/finagle-http/src/main/scala/com/twitter/finagle/http/Message.scala#L164). We don't manage this header each time the content is modified, however we do set it in the dispatcher, but we may not even do that in the future. finagle-http is moving towards a more "raw" API, which could mean header management such as this may become the responsibility of the user.

**Comment by mariusae** [comment]
@luciferous we should document carefully what the http client/server does and doesn't do.

Also, we're not going to change behavior from underneath the user--new behavior would be introduced as an option, or as a new API altogether.

**Comment by vicentealencar** [comment]
@luciferous thank you for responding. What I am actually trying to do is to use the [Request](https://github.com/twitter/finagle/blob/1ac2ce7657fd5952a92049a745945fe800c87fb5/finagle-http/src/main/scala/com/twitter/finagle/http/Request.scala#L164) object along with an `endpoint` instance in test cases. E.g.:

```scala
val service = endpoint.toService
val request = Request("/books")
request.method = Method.Post
request.content = copiedBuffer(s"""{"title": "hello world"}""", UTF_8)
request.setContentTypeJson
// requests always got rejected without the line of code below
// request.contentLength = request.length
service(request)
```
By applying the [Request](https://github.com/twitter/finagle/blob/1ac2ce7657fd5952a92049a745945fe800c87fb5/finagle-http/src/main/scala/com/twitter/finagle/http/Request.scala#L164) object we get a [MockRequest](https://github.com/twitter/finagle/blob/1ac2ce7657fd5952a92049a745945fe800c87fb5/finagle-http/src/main/scala/com/twitter/finagle/http/Request.scala#L224) back, which inherits from the [Request](https://github.com/twitter/finagle/blob/1ac2ce7657fd5952a92049a745945fe800c87fb5/finagle-http/src/main/scala/com/twitter/finagle/http/Request.scala#L21) abstract class. Given that `MockRequest` was created for testing purposes, would it make sense for the `content-length` header to be automatically set in MockRequest instances (instead of setting it automatically in all `Messages` instances as I initially proposed)?

It just took me a long time to figure this out and I thought we might want to avoid others from going through it.

**Comment by luciferous** [comment]
@mariusae thanks for clarification, yes

@vicentealencar it seems reasonable to change MockRequest to make it more convenient to do testing, however, if we change MockRequest in this way, will this test still be testing what we expected it to? In your example, this will mean that MockRequest will pass tests, but Request will perhaps be missing a critical header outside of test usage. I think what we should look at is why the requests are being rejected by the server, can you verify that the content-length header is missing from the dispatched requests?

**Comment by mosesn** [comment]
@vicentealencar were you able to try what @luciferous suggested?

**Comment by vicentealencar** [comment]
Guys, sorry I didn't follow up on this. I will try out what @luciferous suggested and will follow up.

**Comment by vkostyukov** [comment]
@luciferous @dschobel haven't we fixed this already (internally)?

**Comment by vkostyukov** [comment]
I'm talking about commits: https://github.com/twitter/finagle/commit/d9276f9ecbb53737da9d6c513198693816e1be40 and https://github.com/twitter/finagle/commit/e2f4187d050e1a51aa9cf849427c6fb04d909fdd.

**Comment by dschobel** [comment]
@vkostyukov yes, those commits will fix the case that @vicentealencar describes in his 1/19 comment.

Here's our test-case [finagle/http/EndToEndTest.scala](https://github.com/twitter/finagle/blob/develop/finagle-http/src/test/scala/com/twitter/finagle/http/EndToEndTest.scala#L122).

It's now true for all finagle http client dispatchers that every http requests which a) has a message body b) is dispatched c) is not a chunked-transfer will have a defined content-length header.

**Comment by vkostyukov** [comment]
Thanks @dschobel! Let's close it then.
