### ISSUE TITLE
please document when classes are moved to other repos

### ISSUE THREAD

**Issue by fommil** [twitter/finagle#340]
when upgrading from 6.20 to 6.24 we got stung by the movement of StatsReceiver into a jar that I'm still tracking down (the project choose to have intransitive dependency tracking long before I joined).

It would be extremely useful if such movements were documented in the changelog. If it's internally within the project, then a git grep is useful... but this has actually been removed from the project.

**Comment by mosesn** [comment]
Sorry, you're right, we screwed up.  It made it into the util [changelog][0] but I didn't think to document it in the finagle one too.

I'll add it to the finagle ChangeLog too.

[0]: https://github.com/twitter/util/blob/develop/ChangeLog#L16

**Comment by mosesn** [comment]
If you're curious, here's the commit:

https://github.com/twitter/finagle/commit/acf28ac5f805a73fac8ea8aa6f0f0d2189b1aea8

and in util:

https://github.com/twitter/util/commit/55e0cfb938ec000e0cc75546a7f45e0af46a55b5

**Comment by fommil** [comment]
I'm just amazed that you have **this** many stats packages...

```
com.twitter finagle-commons-stats_{scala_version_base} {finagle_version}
com.twitter finagle-stats_{scala_version_base} {finagle_version}
com.twitter util-stats_{scala_version_base} {twitter_version}
com.twitter.common stat 0.0.39
com.twitter.common stats 0.0.98
com.twitter.common stats-util 0.0.49
com.twitter.common stats-provider 0.0.66
com.twitter.common stat-registry 0.0.35
```

it really did cost me most of the day to work this out. I wish that the responsibility of resolving these things lay firmly with the person who choose to go intransitive in the first place. But, alas....

**Comment by mosesn** [comment]
For future reference, if you're looking for a commit for a file that has disappeared, you can examine

`git log $DIR`

where $DIR is the directory of the file that was removed, to narrow down the commits you look through.  Our commit messages tend to have much more context than our changelogs, so if you're curious about what exactly happened, and why, they're the right place to look.

**Comment by fommil** [comment]
I think our biggest problem this time around was the commit that changed how the ServiceLoader worked. By aggressively loading things on startup, it dramatically increases the number of jars that are required for a minimal intransitive setup. We got stung big time.

**Comment by mosesn** [comment]
Happy to accept pull requests!  As you can probably guess, you're the first folks I've talked to who have made all deps intransitive, so you're breaking new ground.

**Comment by fommil** [comment]
I'd rather bash the intransitive advocates over the head with a big stick

**Comment by luciferous** [comment]
I think this issue is resolved, feel free to reopen if not.
