### ISSUE TITLE
memcached zipkin integration bug

### ISSUE THREAD

**Issue by kristofa** [twitter/finagle#343]
We recently noticed, since upgrading to Finagle 6.24, that memcached spans representing GET operations look fine initially (using zipkin-web) but when refreshing the full trace minutes later they have a much longer and incorrect duration. This indicates that memcached GET operation spans are submitted twice with different properties.

Initially the spans have expected annotations but are lacking the `Hit` or `Miss` custom annotations that are added in the memcached filter.

After some time when refreshing the span durations are wrongly updated but they also have the 'Hit' or 'Miss' annotations AND `finagle.flush` annotations.  The last one indicates the span was in the `DeadLineSpanMap` till the deadline was reached.

When looking in more detail at the code I think I know what is happening.  When the `Client Received` annotation is set the span is submitted to the collector/scribe and removed from the `DeadLineSpanMap` as expected. However after that the memcached filter kicks in which submits the hit / miss annotation. When this happens `DeadlineSpanMap#update` is executed. The DeadlineSpanMap won't find the trace id anymore in its map and will create a new Span with same id (Trace + span + parent span id).  This new span will contain the cache hit/miss annotation but will never receive any other annotations and so will get send of once the deadline expires.

memcached SET operation spans are fine as those are not updated by the memcached custom filter.

So I think we should not set any more annotations after an annotation that completes the span is submitted.

I'll look into making a pull request to fix this.

**Comment by mosesn** [comment]
Sounds like a plan!  Please let us know if you need any help.

**Comment by kristofa** [comment]
Thanks, I can use some help, yes :)

The problem is that the `MemcachedTraceInitializer` filter is registered in the `TraceInitializerFilter.role`. The next filter in the chain is the `ClientTracingFilter` which submits cs, cr annotations. After the `ClientTracingFilter` ends the span by submitting cr annotation the `MemcachedTraceInitializer` filter still submits cache hit/miss annotations.

So the obvious way to go I guess is to replace the current `ClientTracingFilter` with an updated Memcached filter which combines submitting cs, cr annotations and cache hit/misses.

This does not sound too complicated but the problem is that I don't see a way to do this using the current Memcached clients. The Memcached clients don't seem to use `StackClient` and they only seem to allow overriding the Trace Initializer?

Any thoughts or suggestions would be really helpful. Thanks!

**Comment by kristofa** [comment]
See #354

**Comment by mosesn** [comment]
@kristofa is this something you're still thinking about?

**Comment by kristofa** [comment]
I'll revisited this soon. I'll check if the issue is still present in Finagle 6.35.0 and if so I'll submit a new pr.

**Comment by mosesn** [comment]
woot!  thanks so much!  *<(。⊃≧∀≦)⊃

**Comment by kristofa** [comment]
Pull request #516 reviewed.

**Comment by mosesn** [comment]
Thanks for tackling this @kristofa !
