### ISSUE TITLE
LoadService not support GBK charset

### ISSUE THREAD

**Issue by tianxiao-ma** [twitter/finagle#366]
when LoadService encounter a file named `META-INF/services/upload.xsd` in a jar, it throw a `java.nio.charsetMalformedInputException` exception. 

Because my linux environment's default charset is GBK, so LoadService use GBK to read files in jar, but the `META-INF/services/upload.xsd` file is encoded with `UTF-8`, so a exception is thrown.

Can let LoadService use `ISO8859-1` as its default charset to read files? or can let the user determine which charset should use?

**Comment by mosesn** [comment]
Could you paste the stack trace?  I think the bug is that https://github.com/twitter/finagle/blob/master/finagle-core/src/main/scala/com/twitter/finagle/util/LoadService.scala#L115 should have a second argument, "UTF-8", but a stack trace would help nail it down.

https://github.com/twitter/finagle/blob/master/finagle-core/src/main/scala/com/twitter/finagle/util/LoadService.scala#L180 is a possible candidate too.

**Comment by tianxiao-ma** [comment]
@mosesn 

sorry, I'm late.

yes, the problem is the second parameter. And [https://github.com/twitter/finagle/blob/master/finagle-core/src/main/scala/com/twitter/finagle/util/LoadService.scala#L93](https://github.com/twitter/finagle/blob/master/finagle-core/src/main/scala/com/twitter/finagle/util/LoadService.scala#L93) is hard code 'UTF-8'.

I think `ISO8859-1` is a better default charset for `LoadService`.

my stack track is here.
![stack](https://cloud.githubusercontent.com/assets/3139359/7134534/4d0630c4-e2d0-11e4-8ef7-ee3f2fbffa55.png)

The `data-resolve.xsd` file is encoded use `UTF-8`, and the linux server's default charset I run `finagle` is `GBK`, so the exception is throwed.

**Comment by mosesn** [comment]
Could you elaborate on why you think ISO8859-1 is a better choice?  And how do you feel about making a PR fixing this?

**Comment by tianxiao-ma** [comment]
@mosesn 
It's about how `ISO8859-1` do encode and decode. For short,  `ISO8859-1` is single-byte fixed length encoding, and `GBK` or `UTF-8` is variable-length encoding. For detail, please see [http://stackoverflow.com/questions/7048745/what-is-the-difference-between-utf-8-and-iso-8859-1](http://stackoverflow.com/questions/7048745/what-is-the-difference-between-utf-8-and-iso-8859-1)

Since the information need by `LoadService` will just ascii chars, so `ISO8859-1` will work. And file's encoded by `GBK` or `UTF-8` can also be read use `ISO8859-1`, so no exception will throw.

**Comment by vkostyukov** [comment]
I believe we can close this already (fix is here https://github.com/twitter/finagle/commit/aad73448b74f9f98b487c8dbd376dcb134927d9d).
