### ISSUE TITLE
MDNS tests wont work

### ISSUE THREAD

**Issue by ncardozo** [twitter/finagle#371]
I am trying to run the tests from finagle 6.24 in an independent project, but run into 2 problems.

1. The resolver tests aborts due the class com/twitter/finagle/stats/StatsReceiver being missing
I dont seem to find the definition of this class anywhere. Regardless of that, this class is used from within the com/twitter/finagle/Resolver class

2. the MDNS object doesnt seem to be found in the project even if it is defined in the finagle-mdns.jar file

Any help that you could provide in getting a small mdns example application running would be of great help

**Comment by mosesn** [comment]
Do you have transitive dependencies turned off?  The finagle stats receiver was moved into the util-stats module.  I'm not sure about what your problem with the mdns object is.

Which branch of finagle are you running tests from?

**Comment by mosesn** [comment]
I think this was a transitive dependencies problem, and there hasn't been a response in over a year, so I'm going to assume we solved @ncardozo's problem and close this ticket.
