### ISSUE TITLE
Document Name.Bound.path

### ISSUE THREAD

**Issue by olix0r** [twitter/finagle#376]
I'm looking at the `Name` implementation; and I can't really recall why we added the [`path` field to `Name.Bound`](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/Name.scala#L36-L47).

We should add some documentation explaining the role of this field.  I'm happy to do it, except I don't really know what to say ;)

**Comment by olix0r** [comment]
Specifically: is this a 'residual' path or is this something else?

If I recall correctly, this path should only consist of the unbound residual path components (and not the bound path), while the id field (if it is a path) should identify the bound path.

**Comment by dschobel** [comment]
routed to #traffic

**Comment by jaked** [comment]
It's the residual path. according to @olix0r - 162.days:

  https://github.com/twitter/finagle/commit/25a24417

**Comment by olix0r** [comment]
I had a feeling this was my fault.  I'll submit a PR to clarify the docs.  Thanks.
