### ISSUE TITLE
./sbt fails to download sbt-launch.jar

### ISSUE THREAD

**Issue by olix0r** [twitter/finagle#377]
$ rm sbt-launch.jar 

    $ ./sbt            
    downloading sbt-launch.jar
    bad sbt-launch.jar.  delete sbt-launch.jar and run ./sbt again.

    $ cat sbt-launch.jar 
    <html>
    <head><title>302 Found</title></head>
    <body bgcolor="white">
    <center><h1>302 Found</h1></center>
    <hr><center>nginx/1.8.0</center>
    </body>
    </html>

    $ curl -v http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.ja
    > GET /typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar HTTP/1.1
    > User-Agent: curl/7.37.1
    > Host: repo.typesafe.com
    > Accept: */*
    > 
    < HTTP/1.1 302 Moved Temporarily
    < Content-Type: text/html
    < Date: Tue, 05 May 2015 21:26:52 GMT
    < Location: http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
    < Server: nginx/1.8.0
    < Content-Length: 160

I think this is trivial to fix by adding the `-L` flag to curl?  I'l prep a PR...

**Comment by dschobel** [comment]
yep, that's the fix, it's up for review internally now so no need for a PR
