### ISSUE TITLE
Is there something wrong with the support of Thrift trace in finagle

### ISSUE THREAD

**Issue by SDHM** [twitter/finagle#379]
These days i try to trace with the rpc call with zipkin, buf in the web console I found some thing wrong with the trace Info, so I seach the problem , I add some Output in the com.twitter.finagle.thrift.TTwitterClientFilter and the com.twitter.finagle.thrift.TTwitterServerFilter 

i found that the spanId and the traceID and parentID are not right

there is some output of my test

this is the server output:

server recv traceId:6661878708663929840
server recv spanId:3293333674833827871
server recv parentId:6661878708663929840                      //I change the source so there is a value
server recv sampled:Some(true)
server recv flag:Flags(0)
apply  // here the server call the func then return the result to the client
--------------------------replay------------------------
client send traceId:5472323338388413376
client send spanId:5472323338388413376
client send parentId:0
client send sampled:false
client send flag:0
 
client send traceId:-477651184034572258
client send spanId:-477651184034572258
client send parentId:0
client send sampled:false
client send flag:0
 
client send traceId:-1429028370350764265
client send spanId:-1429028370350764265
client send parentId:0
client send sampled:false
client send flag:0
------------------------------------------------------------

Here is the client output:
client send traceId:6661878708663929840
client send spanId:6661878708663929840
client send parentId:0
client send sampled:true
client send flag:0

client send traceId:7387068174314188364
client send spanId:7387068174314188364
client send parentId:0
client send sampled:false
client send flag:0

------------------------------------------------------------

it's just call the func for once

we found the client's first spand id and traceID is the server's first parentId and it's traceID, the server's spanId is new. this looks right, but something happen next is wrong.

the server endpoint walk though TTwitterClientFilter  for three times and the client walk though TTwitterClientFilter  for  two times.

thank for you help!
my email:cctcxj@163.com
如果您能说中文，那就太好了，英语实在是太费经了

**Comment by mosesn** [comment]
Sorry it took so long to get back to you!  @SDHM I'm not sure I understand what the problem you ran into was.  Do you remember what was happening here?

**Comment by mosesn** [comment]
Don't have enough information to reproduce, so I'm going to close this for now.  If someone runs into this again, feel free to reopen!
