### ISSUE TITLE
finagle_httpx version in doc/src/sphinx/code/quickstart will not work

### ISSUE THREAD

**Issue by VELVETDETH** [twitter/finagle#388]
It's 6.26.0 in the newest commit, however, it will not work:

    com.twitter#finagle-httpx_2.10;6.26.0: not found)

Then I changed it to 6.24.0, everything is fine.

**Comment by dschobel** [comment]
@VELVETDETH we're in the middle of publishing the 6.26 artifacts but there is a lag between the docsite being updated and the binaries being released so sorry for the confusion.

In the mean time you can still use 6.25.0 of the finagle-* packages and all of the quickstart docs should still run.

**Comment by VELVETDETH** [comment]
@dschobel Thanks for your comment, now I understand.

Still, Finagle rocks

**Comment by VELVETDETH** [comment]
Sorry but should I close this issue @dschobel ?

**Comment by dschobel** [comment]
@VELVETDETH let's keep it open until the binaries are released since it's a legitimate issue. I'll take a look at the release process to see if we can't hold docsite publication until after the binaries are available going forward.

**Comment by dschobel** [comment]
6.26.0 has been published and the example works again.
