### ISSUE TITLE
Support making Kerberos credentials acquirable via native libgssapi

### ISSUE THREAD

**Issue by kevints** [twitter/finagle#395]
The JVM supports using the native platform GSS library libgssapi: http://docs.oracle.com/javase/7/docs/technotes/guides/security/jgss/jgss-features.html by setting the system property `com.sun.security.jgss.native` to `true`

There are a couple advantages to using the native library instead of the JVM-implemented one. You can share the same TGT that has been acquired for other non-JVM applications, even if it's stored in the kernel keyring rather than a file-based credentials cache. The more-familiar setup of kinit-with-environment-variables replaces the esoteric and poorly-documented `jaas.conf`. The native tools `kinit`, `klist`, etc. are much easier to debug with than JAAS as well. Credentials can also be cached in secure unpageable kernel memory rather than a file on disk.

**Comment by luciferous** [comment]
This is an interesting suggestion, thanks @kevints. We can prioritize this against the list of things we're working on internally, but if you're waiting on this it might be faster for us to work together on a PR.

**Comment by mosesn** [comment]
@kevints as you point out, this is something you can turn on with a system property, so I'm not sure it's something finagle should set a default for.  I'm going to close this ticket for now, but please reopen if I missed something!
