### ISSUE TITLE
how can i trace http for java?

### ISSUE THREAD

**Issue by 3thinkthendoit** [twitter/finagle#398]
HI all,

i write a filter like this (java code)

public class HttpTracingFilter implements Filter
{

	protected Logger logger = Logger.getLogger(this.getClass().getName());
	
	private Tracer tracer = null;

	private String module = "";
	
	private String[] params = new String[]{};
	
	@Override
	public void destroy()
	{
		//tracer.flush();
		
	}

	@Override
	public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException,
			ServletException
	{
		HttpServletRequest request = (HttpServletRequest) req;		
		HttpServletResponseWrapper response = new HttpServletResponseWrapper((HttpServletResponse) res);
		long parent = System.currentTimeMillis();
		SpanId spanId = SpanId.apply(System.nanoTime());//创建一个spanId

		TraceId traceId = TraceId.apply(Option.<SpanId> apply(spanId), Option.<SpanId> empty(), SpanId.apply(parent), Option.<Object>apply(Boolean.TRUE));
		Trace.pushTracerAndSetNextId(tracer, false);
		Trace.setId(traceId, false);
		Trace.record(new Annotation.ServerRecv());
		Trace.recordBinary("http.uri", request.getRequestURI());
		Trace.recordBinary("http.port", ""+request.getLocalPort());
		//记录参数
		for (String param : params)
		{
			if (request.getParameter(param) != null)
				Trace.recordBinary("param."+param, request.getParameter(param));
		}
		Trace.recordServiceName(("http-"+module).toLowerCase());
		Trace.recordRpc(request.getMethod());		
		Trace.recordClientAddr(new InetSocketAddress(request.getRemoteAddr(), request.getRemotePort()));
		Trace.recordServerAddr(new InetSocketAddress(NetUtil.getLocalHost(), request.getLocalPort()));
		try {
		    chain.doFilter(request, response);
		} catch (Throwable t) {
			Trace.recordBinary("http.hasError", "true");
			Trace.recordBinary("http.error", t.getStackTrace());
		    try
			{
				throw t;
			}
			catch (Throwable e)
			{
				// TODO Auto-generated catch block
				e.printStackTrace();
			}		        
		}
		Trace.recordBinary("http.status",""+response.getStatus());
	    Trace.record(new Annotation.ServerSend());
	    
		//tracer.flush();
	}

	@Override
	public void init(FilterConfig config) throws ServletException
	{
		String flumeIp = config.getInitParameter("flumeIp");
		if (flumeIp == null)
			flumeIp = "127.0.0.1";
		String flumePort = config.getInitParameter("flumePort");
		
		String sampleRate = config.getInitParameter("sampleRate");
		if(sampleRate == null){
			sampleRate = "1";
		}
		int port = 1463; // 默认
		if (config.getInitParameter("module") != null)
			module = config.getInitParameter("module");
		if (config.getInitParameter("params") != null)
		{
			params = config.getInitParameter("params").split(",");
		}
		if (flumePort != null)
		{
			try
			{
				port = Integer.parseInt(flumePort);
			}
			catch (Exception e)
			{
				e.printStackTrace();
			}
		}
		StatsReceiver sr = DefaultStatsReceiver.self();
		//scala.collection.immutable.List<Tracer> tracers = Trace.tracers();

		tracer  = ZipkinTracer.mk(flumeIp, port,sr,Float.valueOf(sampleRate));
		//tracer = new SamplingTracer(new RawZipkinTracer(flumeIp, port, sr), Float.valueOf(sampleRate));
//		tracer.setSampleRate(0.0f);
		//tracer.setSampleRate(Float.valueOf(sampleRate).floatValue());
//		RawZipkinTracer rawtracer = new RawZipkinTracer(scribeIP, port, sr);
//		tracer = new ZipkinTracer(rawtracer, 0.0f);
		//RawZipkinTracer rawtracer = new RawZipkinTracer(scribeIP, port, sr);
		//tracer = new RawZipkinTracer(flumeIp, port, sr);
		
		logger.info("init  flume IP:"+flumeIp+" port:"+port+"the sampleRate:"+sampleRate+",OK!");
	}
 

when i use the filter int the web project. set the sampleRate = 0, but this tracer  also send trace data to zipkin?? i don't konw why????? 

<filter>
     <filter-name>zipkinFilter</filter-name>
     <filter-class>HttpTracingFilter</filter-class>
     <init-param>
   
       <param-name>flumeIp</param-name>
       <param-value>192.168.115.105</param-value>
       </init-param>
   <init-param>
   
       <param-name>flumePort</param-name>
       <param-value>1463</param-value>
   </init-param>
   <init-param>
    
       <param-name>sampleRate</param-name>
       <param-value>0</param-value>
   </init-param>

**Comment by taylorleese** [comment]
@3thinkthendoit Closing this since it's already been asked on the google group. https://groups.google.com/forum/#!topic/finaglers/SaYvZI8nFZ8
