### ISSUE TITLE
Finagle-mysql client can't select DateTime values correctly.

### ISSUE THREAD

**Issue by ken57** [twitter/finagle#402]
I have a question about Finagle-mysql.
I use Finagle to implement an API server.

I found a curious behavior(bug?) in finagle mysql client.
Finagle-mysql client can't select values from mysql tables correctly,
in case of inputting a selection query using expressions such as IF.

The minimum reproduction code is shown in https://gist.github.com/ken57/80538db7ce6ee36d51e7

Is it correct behavior that Datetime values are converted to RawValue?
 
It seems that a type(12:DateTime) is obtained correctly, but a charset is mismatched(It's not a binary).
Is it necessary to compare the charset for obtaining Timestamp and/or Datetime value?
https://github.com/twitter/finagle/blob/master/finagle-mysql/src/main/scala/com/twitter/finagle/mysql/Value.scala#L104
http://dev.mysql.com/doc/internals/en/character-set.html#packet-Protocol::CharacterSet
 
I tested by using Finagle 6.24 and Mysql 5.6.

Thanks for the help.

**Comment by mosesn** [comment]
Hi @ken57, thanks for filing the issue!  Yeah, that's very strange, we should fix that.  Sorry it took us so long to get back to you about this.

**Comment by iwag** [comment]
the commit to fix is cc891eb?
I'm really happy to see that 😃

**Comment by mosesn** [comment]
Ah, good catch!  I'll mark it as fixed.  Thanks @niw!

**Comment by niw** [comment]
My pleasure 😉
