### ISSUE TITLE
is client thread-safe ?

### ISSUE THREAD

**Issue by hoondori** [twitter/finagle#411]
I have tried to find the explicit comments on this issue on finagle public documentation, but failed to find.

**Comment by mosesn** [comment]
Yes, it is designed to be used by many threads.  In general, the finagle public API is threadsafe unless it explicitly says otherwise.

**Comment by taylorleese** [comment]
@hoondori If you have any additional questions please use the Finaglers group. https://groups.google.com/forum/#!forum/finaglers
