### ISSUE TITLE
finagle-thrift ruby: trace ids as unsigned ints

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [twitter/finagle#413]
Hi,

Since I'm only getting started with using finagle before I try to fix and submit a PR I wanted to check the issue at hand indeed is one.

As it stands now, the ids generated by the [Trace.generate_id](https://github.com/twitter/finagle/blob/develop/finagle-thrift/src/main/ruby/lib/finagle-thrift/trace.rb#L130-L132) will be unsigned if the randomly picked up number exceeds `2 ** 63`.
This is against the supported thrift [types](https://thrift.apache.org/docs/types) and causes interoperability issues.
In our case we have ruby services talking with ones made in .Net and a long time ago when we first looked at Zipkin we ran into overflow errors due to this.

Now, the SpanId class does a [conversion to hex](https://github.com/twitter/finagle/blob/develop/finagle-thrift/src/main/ruby/lib/finagle-thrift/trace.rb#L126) but the zipkin-tracer gem for instance blissfully [calls that generate method directly](https://github.com/openzipkin/zipkin-tracer/blob/master/lib/zipkin-tracer/rack/zipkin-tracer.rb#L107).

In order to figure out what would be the best course can anyone familiar with that part confirm or dismiss this issue?
A quick and easy way would be to set the trace id upper bound to `2 ** 63` instead of `2 ** 64` but I don't know whether this change could have side effects. The aforementioned SpanId class for instance makes a mask out of `(2 ** 64) - 1` and the class Flag mentions [64 potential flags](https://github.com/twitter/finagle/blob/develop/finagle-thrift/src/main/ruby/lib/finagle-thrift/trace.rb#L90-L100) (though if it is unlikely all 64 of them ever get implemented).

Any thoughts, anyone?

**Comment by mosesn** [comment]
That seems reasonable, although it seems weird to me that the ruby thrift implementation would be fine to just make it unsigned instead of failing.

Can we continue generating [0, 2^64] but then subtract 2^63 to preserve the full size of the ids?

**Comment by jfeltesse-mdsol** [comment]
ok, now I've spent more time testing this through zipkin I can safely close this issue.

The confusion was that indeed that generate_id method *does* make unsigned ints sometimes but afterwards it's converted to an hex string by the SpanId class so no issue in the end.
I guess the confusion on our end stemmed from the naming and, dare I say, the clunky API where you end up with calls such as `trace_id.trace_id.to_s`... :sweat:
