### ISSUE TITLE
When i compile  finagle-zipkin  in   finagle-6.25 , throw some errors:

### ISSUE THREAD

**Issue by 3thinkthendoit** [twitter/finagle#416]
When i compile  finagle-zipkin  in   finagle-6.25 , throw some errors:

[trace] Stack trace suppressed: run last finagle-test/*:update for the full outp
ut.
[error] (finagle-test/*:update) sbt.ResolveException: unresolved dependency: com
.twitter#util-core_2.10;6.24.0-SNAPSHOT: not found
[error] Total time: 48 s, completed 2015-9-14 15:04:30

 http://maven.twttr.com/com/twitter   without    util-core_2.10;6.24.0-SNAPSHOT!

**Comment by mosesn** [comment]
@3thinkthendoit can you publish-local the twitter/util project?  If you want to build off of stable versions, you can compile from master, which should only be a little behind `develop`.  You can find more details [here][0].

[0]: https://github.com/twitter/finagle/blob/develop/CONTRIBUTING.md#building-dependencies

**Comment by 3thinkthendoit** [comment]
@mosesn  thank you ,I get it.
