### ISSUE TITLE
Setup zipkin trace with the new api?

### ISSUE THREAD

**Issue by 3thinkthendoit** [twitter/finagle#421]
hi all, I want to set up finagle-zipkin with new api  like this:

new  api:

 Hello.ServiceIface impl = new HelloImpl();
    ListeningServer server = Thrift.serveIface("localhost:8080", impl);

    try {
		//serverImpl.join(endpoint, new HashMap<String,InetSocketAddress>());
    	server.announce("zk!192.168.115.105:2181!/foo/test!1");
		System.out.println("add service to zk ok....");
	} catch (Exception e) {
		e.printStackTrace();
	}
    Await.ready(server); 

and then , how can i config the others like 

hostConnectionMaxIdleTime  ,readTimeout  and  requestTimeout 

thanks.!!

**Comment by kevinoliver** [comment]
Hi @3thinkthendoit sorry for the delay. @tonyd3 has a patch for this that should land soon that lets Java users call `configured`.

You'll be able to do:
`.configured(new Tracer(com.twitter.finagle.tracing.DefaultTracer.get()).mk())`

And take a look at `StackParamCompilationTest` for how to use the others.

**Comment by mosesn** [comment]
@3thinkthendoit the patch landed a while ago, so this should work now.  Please let us know if you run into any trouble with it!
