### ISSUE TITLE
is possible use redis event suscription with finagle-redis?

### ISSUE THREAD

**Issue by cocodrino** [twitter/finagle#435]
Hi, I need suscribe to the expiration event similar to how is explain here

http://www.yanted.com/2014/01/07/keyspace-events-in-redis-2-8/

would be possible  to do this using finagle-redis?

thank so much!!...

**Comment by mosesn** [comment]
@cocodrino we don't have support for it right now, but we'd be happy to work with you to add it :+1:

**Comment by mosesn** [comment]
@cocodrino we've since added support for this here: https://github.com/twitter/finagle/blob/develop/finagle-redis/src/main/scala/com/twitter/finagle/redis/exp/SubscribeClient.scala

**Comment by cocodrino** [comment]
thanks @mosesn looks awesome :+1:

**Comment by mosesn** [comment]
h/t @thirstycrow =)
