### ISSUE TITLE
Reader semantics in a com.twitter.finagle.http.Response

### ISSUE THREAD

**Issue by lukiano** [twitter/finagle#436]
Looking at HttpServerDispatcher, when it sends chunks from response to the transport, it uses ReaderUtils.streamChunks(trans, rep.reader). However rep.reader is usually a Reader.writable() where you can write one chunk at a time.
This makes it necessary to use two threads, one writing to the Writable and the other one executing streamChunks to send that data to the transport.
I feel it'd be better if Response provided a Writer that delegates to some function Buf => Future[Unit], similarly to a scalaz-stream Sink. Then HttpServerDispatcher would fill that function with one that writes directly to the transport (of course converting the Buf to a Netty chunk).
What do you think? Is this feasible?

**Comment by mosesn** [comment]
@lukiano what are you trying to do more generally?  It sounds like you're trying to write from a Reader into a Writer, which we have tooling for: https://github.com/twitter/util/blob/develop/util-core/src/main/scala/com/twitter/io/Reader.scala#L351-L360

**Comment by lukiano** [comment]
I'm in the process of updating a project from the old finagle-http to the new one (a.k.a. httpx). I used to have some code that wrote directly to the transport like let's say
```scala
  def writeOld(list: List[org.jboss.netty.handler.codec.http.HttpChunk], transport: Transport[Any, Any]): com.twitter.util.Future[Unit] = {
    list match {
      case Nil => com.twitter.util.Future.Done
      case h :: hs => transport.write(h) flatMap { _ => writeOld(hs, transport) }
    }
  }
```
and now I'm trying to use the new facilities, writing to the Writable that the Response provides:
```scala
  def writeNew(list: List[com.twitter.io.Buf], writable: com.twitter.io.Reader.Writable): com.twitter.util.Future[Unit] = {
    list match {
      case Nil => com.twitter.util.Future.Done
      case h :: hs => writable.write(h) flatMap { _ => writeNew(hs, writable) }
    }
  }
```
However, this writable only allows one element at a time, so this `writeNew` will block until someone starts consuming the `Reader` (this someone is `ReaderUtils.streamChunks` in `HttpServerDispatcher`).
Since everything is happening on the same thread, I have a deadlock.
Hopefully my issue is now better understood.

**Comment by mosesn** [comment]
It shouldn't deadlock.  write is asynchronous, so your thread can continue to do other work.  If you could send a blocked stack trace, that would be great.

With that said, why are you using the Transport directly?  And how even did you get your hands on the Transport?  You shouldn't be doing this–it's not safe to write directly to the Transport, and ReaderUtils is marked private because this is not a public API.  If this is a patch to finagle-http, I'd be happy to take a look at it though :+1:.

**Comment by roanta** [comment]
The reader is driven by the writer, but as Moses pointed out it's all async. I suspect you are perceiving a deadlock because you aren't closing the writer which signals an EOF for the response. Here is some example code that imitates the arrangement in http server dispatcher: https://gist.github.com/roanta/f148a81a7ae53b73ea3c

Sorry that we don't have better docs for this!

**Comment by lukiano** [comment]
Let me re-explain with a plain Java analogy:

You have a server with plain Java sockets. To write your response you send data to the SocketOutputStream, so it goes back to the client.

Your Response class could have an OutputStream so consumer of the API write their response there.

Instead it provides an InputStream (the Reader) and then the server implementation loops to transfer data from the InputStream to the SocketOutputStream (ReaderUtils.streamChunk).

But thinking that consumers of the API have data to write to an OutputStream, then you provide a PipedInputStream/PipedOutputStream (Reader.writable). 

There will be 1 thread with the program logic writing to the OutputStream the Response provides (the PipedOutputStream) and a second thread looping, transferring data from the PipedInputStream to the SocketOutputStream.

I just say there could be a second approach, where the OutputStream the Response provides is the SocketOutputStream, so only 1 thread is needed.

**Comment by lukiano** [comment]
I'll try to find the time to write an implementation and open a PR.

**Comment by lukiano** [comment]
StreamServerDispatcher and StreamResponse in the finagle-stream module may be the answer to this concern. Although StreamServerDispatcher is package private and the Stream CodecFactory doesn't seem to be as configurable as the Http CodecFactory.

**Comment by mosesn** [comment]
@lukiano I think @roanta is right, I'd suggest reading his comment again.  Note that finagle is asynchronous, not synchronous.  Have you tried what he suggested?

Also, how did you get a Reader.Writable?  finagle http should only expose `Writer with Closable` to you.  I think we'd be able to better help you if you explained to us what you were doing.

**Comment by lukiano** [comment]
@mosesn I have a stream of data in a Process[Task, Bytevector] where Process is a scalaz-stream class and Bytevector is an immutable byte array / bytebuffer wrapper, from the scodec library. Converting from Bytevector to Buf is easy, from Task to a Twitter Future is also easy. The remaining issue is piping the stream to a reader.

**Comment by luciferous** [comment]
What's the type of the stream?

**Comment by luciferous** [comment]
Ok, you said you have `toBuf: Bytevector => Buf` and `toFuture: Task ~> Future`. So we can get quite far with:

```
val process: Process[Task, Bytevector]
val vectors: Process[Future, Bytevector] = process.translate(toFuture)
val bufs: Process[Future, Buf] = process.map(toBuf)
```

Like `Process[Future, Buf]`, Reader is an effectful stream of `Buf`s where each step can run `Future` effects. I can think of two ways to do this.

(Beware: pseudocode below.)

- Run `bufs` each step writing to a Writable.

```
def reader(bufs: Process[Future, Buf]): Reader = {
  val writable = Reader.writable()
  val writeSink: Process[Future, Unit] = sink.lift(writable.write)
  (bufs to writeSink).run before writable.close()
  writable
```

- Wrap the `Process` in a Reader interface. Implement `read` by a pattern-match on `process.step` and if it emits, return the result. Reassign the process to the next one given by the continuation.

**Comment by mosesn** [comment]
@lukiano were you able to solve your problem?

**Comment by lukiano** [comment]
Yes, I ended up implementing Reader via traversing the scalaz-stream Process using process.step
You can see the code https://github.com/lukiano/finagle-http4s/blob/master/src/main/scala/org/http4s/finagle/ReaderUtils.scala and https://github.com/lukiano/finagle-http4s/blob/master/src/main/scala/org/http4s/finagle/ProcessStepper.scala

**Comment by mosesn** [comment]
Very cool, thanks for the update!
