### ISSUE TITLE
`RetryFilter[Req,Rep]` should be a `SimpleFilter`.

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#437]
The `RetryFilter[Req, Rep]` that was introduced in b12582f437d604e8d6ef46d05c1f61d85b79a87f extends `Filter[Req, Rep, Req, Rep]`. Wouldn't it be better if it would extend `SimpleFilter[Req, Rep]`?

This would extra document the fact that it shouldn't touch the request/response types. Moreover, the old `RetryingFilter` was a `SimpleFilter` as well.

**Comment by mosesn** [comment]
We generally use `SimpleFilter[Req, Rep]` as a helper class, not as a marker (since you can use `Filter[Req, Rep, Req, Rep]` directly as a marker), so I'd say it's a toss up.  It feels like it's an implementation detail when something is a `SimpleFilter` or not.

**Comment by spockz** [comment]
Allright, but I think the backwards compatibility argument still holds.

**Comment by mosesn** [comment]
@spockz we purposefully renamed `RetryFilter` from `RetryingFilter` so we've already broken backcompat.  Any place where you used a type of `SimpleFilter` can be replaced with a `Filter`, so I think we should be pretty safe :+1:
