### ISSUE TITLE
Unable to Run Mysql example

### ISSUE THREAD

**Issue by chandra-cd** [twitter/finagle#439]
Getting error message :

Failed query with com.twitter.finagle.exp.mysql.LostSyncException: java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 123

**Comment by mosesn** [comment]
Hi @chandra-cd could you paste the full stack trace?

**Comment by ryanoneill** [comment]
Also @chandra-cd, what version of mysql you are using? I was able to run the example successfully using the version that I already had installed, but I would like to try to test with a similar environment. Thanks.

**Comment by chandra-cd** [comment]
Ryanoneill,

Thanks for quick reply. We are using MySql 5.5.33 on Amazon EC2 instance. Here is the output that i get when i run the Example.scala from mysql example :+1:  

INFO: Finagle version 6.30.0 (rev=745578b931893c432e51da623287144e548cc489) built at 20151015-163641
Nov 24, 2015 8:25:37 PM com.twitter.finagle.tracing.DefaultTracer$$anonfun$3 apply
INFO: Tracer: com.twitter.finagle.zipkin.thrift.SamplingTracer
1124 20:25:37.322 df402d15b3ff05e1.df402d15b3ff05e1<:df402d15b3ff05e1] ServerAddr(/10.191.5.183:3306)
com.twitter.finagle.exp.mysql.LostSyncException: java.lang.IndexOutOfBoundsException: Not enough readable bytes - Need 8, maximum is 0
1124 20:25:37.362 a63fa3cec01f9ab4.a63fa3cec01f9ab4<:a63fa3cec01f9ab4] ServerAddr(/10.191.5.183:3306)

Chandra

**Comment by chandra-cd** [comment]
I cleaned the project and tried again but now i am getting a different error :

[info] Running com.twitter.finagle.example.mysql.Example
Nov 24, 2015 8:58:03 PM com.twitter.finagle.Init$$anonfun$1 apply$mcV$sp
INFO: Finagle version 6.30.0 (rev=745578b931893c432e51da623287144e548cc489) built at 20151124-205603
com.twitter.finagle.exp.mysql.LostSyncException: java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 123
[success] Total time: 136 s, completed Nov 24, 2015 8:58:05 PM

**Comment by ryanoneill** [comment]
Sorry @chandra-cd, unfortunately so far I have been unable to reproduce this issue. I was able to try with the same version of MySql (5.5.33)  (different os) but did not encounter the same issues. Please let us know if you're able to find out anything more. Thanks.

**Comment by chandra-cd** [comment]
Ryanoneill,

I was able to run the sample on a new instance of MySql server. Unable understand the reason for error on the other instance. Pythong and Java clients are able to connect but not through finagle.

Chandra

**Comment by iwag** [comment]
I saw a similar issue.
In my case, I didn't call close() method, so mysql's Aborted_clients or Aborted_connects had become the large value and then mysql blocked my clients.

```
mysql  -e 'show global status;' | head
Variable_name   Value
Aborted_clients 5335
Aborted_connects        24950
```

You may want to see 'show global status' if the same issue occurs again!

**Comment by chandra-cd** [comment]
iwag,

Thanks for sharing your experience. I did face this issue and have to reset the stats. When i used the other version on MySql it works fine. It looks to  me that there is something different with MySql server on my EC2 server. I tried on my laptop with mysql installed locally and it works.

I will try to boot a new instance of Ec2 server with MySql and will try to see if this is an issue with a particular instance or with all MySql server on Amazon EC2.

**Comment by mosesn** [comment]
@chandra-cd did you have a chance to look more deeply into this?

**Comment by chandra-cd** [comment]
mosesn,

it didn't work for with the version of mysql i was using but we migrated to latest version of MySql and its working.

**Comment by mosesn** [comment]
Glad to hear it!  Unfortunately, we don't have the bandwidth to test every version of mysql.  Out of curiosity, which version of mysql didn't work, and which one are you using now?

**Comment by chandra-cd** [comment]
I understand the bandwidth issue. It was not working with 5.5.33 on Amazon linux but works with 5.6 .

**Comment by mosesn** [comment]
Thanks!  Good to know.
