### ISSUE TITLE
Is there a plan on supporting redis sentinel and redis cluster?

### ISSUE THREAD

**Issue by thirstycrow** [twitter/finagle#442]
We are using jedis to visit our sentinel based redis clusters. I'm trying to do the same thing with finagle-redis, but it appears that finagle-redis do not support sentinel commands. And the support for redis cluster is also missing. Is there a plan on supporting them in the near future?

**Comment by mosesn** [comment]
@thirstycrow it's not on our roadmap right now, but we'd be happy to help you with your pull request! :+1:

**Comment by thirstycrow** [comment]
I sent a pull request for the sentinel support here #443.

**Comment by mosesn** [comment]
<3

**Comment by mosesn** [comment]
Both of these were merged in, so I'm going to close this ticket.  Thanks so much @thirstycrow !
