### ISSUE TITLE
if the Cookie contain version='' ,can't get the request.cookies

### ISSUE THREAD

**Issue by futureskywei** [twitter/finagle#453]
If customer‘s Cookie contain version=''，the com.twitter.finagle.http.Message.cookies will be null.
Cause the reason is the netty-3.10.1.Final.jar

class:org.jboss.netty.handler.codec.http.CookieDecoder
method:decode
exception code:
if (names.get(0).equalsIgnoreCase(CookieHeaderNames.VERSION)) { //that will be exception when version is ''
try {
version = Integer.parseInt(values.get(0));
} catch (NumberFormatException e) {
// Ignore.
}
i = 1;
}

and line 139
else if (CookieHeaderNames.VERSION.equalsIgnoreCase(name)) {
version = Integer.parseInt(value);
} 
Call the class in finagle-http_2.11-6.25.0.jar com.twitter.finagle.http.CookieMap.class:
private[this] def decodeCookies(header: String): Iterable[Cookie] = {
val decoder = new NettyCookieDecoder
try {
decoder.decode(header).asScala map { new Cookie(_) }
} catch {
case e: IllegalArgumentException =>
_isValid = false
Nil
}
}

**Comment by mosesn** [comment]
@futureskywei what do you think the fix will be?  would you like to submit a PR?

**Comment by futureskywei** [comment]
Upgrade neety version, the new neety has deprecated the CookieDecoder class.

**Comment by mosesn** [comment]
@futureskywei hmm, well netty 4 has a lot of breaking changes, so we're doing it piecemeal.  What do you think we can do in the mean time?  maybe we should add a null check?

**Comment by futureskywei** [comment]
Thanks for your reply.Because of involving netty source, I also had not good advice.I have get Cookie like this request.getHttpMessage().headers().get("Cookie") and deal it with myself as my temporary solution,maybe we can implement a decoder method catch NumberFormatException and return the passable cookies.

**Comment by mosesn** [comment]
Actually, it looks like this isn't a bug.  It looks like "version" is a reserved name for cookies.  See [RFC2109][0].  Maybe the right thing to do is to rename your version cookie name to something else?

[0]: https://www.ietf.org/rfc/rfc2109.txt

**Comment by mosesn** [comment]
I think this is works as expected, so I'm going to close this ticket.  @futureskywei please let us know what you ended up doing!
