### ISSUE TITLE
getAll on headers is not case-insensitive

### ISSUE THREAD

**Issue by greenrd** [twitter/finagle#466]
but `get` is. This is inconsistent.

**Comment by greenrd** [comment]
I mean in `MapHeaderMap`.

**Comment by mosesn** [comment]
Good point!  Would you like to make a PR?

**Comment by greenrd** [comment]
Will do!

**Comment by greenrd** [comment]
Was fixed in 603c0226029f8cc9da2ea628e793e80a91c170ef
