### ISSUE TITLE
Support http decompression for servers

### ISSUE THREAD

**Issue by adriancole** [twitter/finagle#469]
Can `Http.Server().withDecompression(true)` be implemented? Currently, this is silently ignored (conceding it works on the client)

It is not obvious how to affect the netty pipeline to add server support for this, without changing finagle classes directly. If there's a clean way to affect the pipeline, that'd work for me, too.

**Comment by kevinoliver** [comment]
Does `Http.server.withCompressionLevel` work for you? (Looks like we could
use some scaladoc on that method and the others in Http.server to explain
what they do).

I think it gets wired into `c.t.f.http.Codec` which in turn wires up
netty's `HttpContentCompressor` for a server.

On Wed, Feb 24, 2016 at 12:33 AM, Adrian Cole <notifications@github.com>
wrote:

> Can (gzip) decompression be added for http servers?
>
> The _decompressionEnabled flag and similar threw me for a loop, as it
> seems to be placed on Http, but only implemented on the client. It is not
> obvious how to affect the netty pipeline to add server support for this,
> without changing finagle classes directly.
>
> If there's a way to hook into the netty pipeline to add this (without
> changing finagle classes), that'd work for me, too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/finagle/issues/469>.
>



-- 
Kevin Oliver | Twitter, Inc | follow me: @kevino <http://twitter.com/kevino>

**Comment by adriancole** [comment]
> Does `Http.server.withCompressionLevel` work for you? (Looks like we could
> use some scaladoc on that method and the others in Http.server to explain
> what they do).
>
> I think it gets wired into `c.t.f.http.Codec` which in turn wires up
> netty's `HttpContentCompressor` for a server.

Compression works, iirc. The question here is about decompression. ex can
the netty layer unzip a POST request body.

**Comment by kevinoliver** [comment]
Derp, reading fail on my part.

Looks like it is not wired up but could be done in a similar fashion.

**Comment by taylorleese** [comment]
Can we resolve this based on #478 or is there something else I'm missing here?

**Comment by vkostyukov** [comment]
Yeah, I think it might be closed now. Thanks @nrinaudo for fixing this!
