### ISSUE TITLE
Support server side entity body decoding

### ISSUE THREAD

**Issue by nrinaudo** [twitter/finagle#476]
Finagle currently has support for clients accepting encoded response entities - if a client sets its `Accept-Encoding` to, say, `gzip`, Finagle knows to compress its response and set the `Content-Encoding` header appropriately.

What is not yet supported is the symmetric of this: it's legal, although not terribly common, for clients to submit request entity bodies in a content encoding they know the server to support (`gzip`, for instance, is guaranteed by spec to be supported by all compliant servers). This is not something that Finagle knows to deal with.

The feature appears simple enough to implement - all the necessary bricks are there, even the configuration option, they've just not been assembled. I'd be happy to submit a PR should this be considered a desirable feature.

**Comment by kevinoliver** [comment]
Is this the same issue as in #469? If so, a PR implementing it would be great (cc @adriancole)

**Comment by nrinaudo** [comment]
It absolutely is, you're right. Dont't know how I failed to find it, I'm sorry.
I might be a bit busy this week but I think I can get something done this weekend. It looks like a 2 lines modifications (@vkostyukov pointed me in the right direction).

**Comment by nrinaudo** [comment]
The problem turns out not to be server side decoding implementation - I have something locally that works fine - but client side encoding, which I'll need at least for testing.

From what I managed to piece together, content encoding in netty must go through `HttpContentEncoder`, which is implemented in such a way that it *must* be called in response to a request: if `messageReceived` isn't called, netty doesn't populate its accepted-encoding list and freaks out when asked to encode content. It thinks it's trying to respond to a non-existing request and throws a scary sounding `IllegalStateException("cannot send more responses than requests")`.

I could probably hack together a custom implementation of `HttpContentEncoder`, but before I go down that road, is there a known, clean way of working around that issue? My netty knowledge is next to non-existent, so I might be overlooking something obvious.

**Comment by vkostyukov** [comment]
@nrinaudo In what position do you insert `HttpContentDecompressor`? My take would be to put it right after `HttpChunkAggregator`. I looked through the implementation of `HttpContentDecompressor` and it looks like it should handle streaming requests just fine.

I'm not sure what do you mean by `messageReceiver` isn't called. Do you mean `HttpContentDecompressor` doesn't work if the incoming message isn't encoded?

**Comment by nrinaudo** [comment]
Sorry, I wasn't clear. The server side decompression works fine, it's the *client side* compression that's tricky. The issue I'm having is not with `HttpContentDecompressor` But `HttpContentCompressor`.

**Comment by mosesn** [comment]
Yes, it looks like netty doesn't have support for it, I've filed a ticket with them https://github.com/netty/netty/issues/4970.

With that said, since what you're trying to accomplish is to add support on the server-side, maybe it makes more sense to carefully craft a unit test that you can use to verify it works rather than to add general client-side support?  If you decide you also need it on the client-side, then we can go down that road later.

**Comment by nrinaudo** [comment]
Thanks for taking the time to look into this and to file a much more informed issue than I could have.

I'll do as you suggest, even though it would definitly make sense to add client side compression support at a later date. I was hoping to piggyback `EndToEndTests`, but I can simply write a test that sends gzipped content with the appropriate header (if I can set a custom `Content-Encoding` Header?) and makes sure it's properly decoded server side.

**Comment by mosesn** [comment]
:+1: sounds like a good plan, thanks!

**Comment by vkostyukov** [comment]
I guess we can close this now. Thanks again @nrinaudo!
