### ISSUE TITLE
Proxy example in quickstart does not work

### ISSUE THREAD

**Issue by jabley** [twitter/finagle#477]
https://twitter.github.io/finagle/guide/Quickstart.html#putting-it-together

```
> curl -D - localhost:8080
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Content-Length: 1561
Date: Thu, 10 Mar 2016 09:50:48 GMT

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/</code> was not found on this server.  <ins>That’s all we know.</ins>
```

Debugging this is interesting. I've used Wireshark, since I've not found a way of dumping the request and response that the proxy is handling. That's probably a separate issue.

**Comment by bmorganatlas** [comment]
I've also run into this issue. I'm not sure what is going on either because rewriting the example Client object to request against google.com gives the expected 302 result.

**Comment by vkostyukov** [comment]
@bmorganatlas @jabley Sorry for the delayed response. Any chance you wish to open a PR with `s/www.google.com:80/google.com` if that fixes the issue for you?

**Comment by jabley** [comment]
That doesn't fix the issue for me. Essentially the Proxy is making a request equivalent to:

```
curl -H "Host: localhost:8080" http://google.com/
```

which is why Google returns a 404. I'm not sure how you configure finagle to print out that level of detail, which is why I used Wireshark.

**Comment by mosesn** [comment]
Looks like google changed their behavior slightly.  We should update the quickstart to reflect this.

We can fix this issue by:

1.  Pointing to twitter.com instead of google.com
2.  Changing the test command to be `curl -D - -H "Host: twitter.com" localhost:8080`

I'm marking this as a starter issue since I think this would be a great way for someone to get started with playing around with finagle.

**Comment by mosesn** [comment]
Fixed here: https://github.com/twitter/finagle/commit/a60909d4996ff87d016187fe4abf2f899d466e75 !
