### ISSUE TITLE
have oauth2 with java api sample?

### ISSUE THREAD

**Issue by zhao141** [twitter/finagle#483]

**Comment by vkostyukov** [comment]
@zhao141 Are you looking for server-side or client-side examples?

**Comment by zhao141** [comment]
server.

**Comment by vkostyukov** [comment]
You can take a look at the [finagle-ouath2](https://github.com/finagle/finagle-oauth2) project that provides sever-side OAuth2 support for Fiinagle services. There is also [a complete example](https://github.com/finagle/finch/blob/master/examples/src/main/scala/io/finch/oauth2/InMemoryDataHandler.scala) in the Finch repository.

**Comment by vkostyukov** [comment]
Feel free to swing by a [Finagle room on Gitter](https://github.com/twitter/finagle) and ping us there is you still have questions.
