### ISSUE TITLE
Finagle does not build with SBT 0.13.x

### ISSUE THREAD

**Issue by anupamaggarwal** [twitter/finagle#484]
Hi,

I am not able to compile finagle with sbt-0.13.9, which is the default version homebrew picks up on mac.

I saw another issue marked close wherein support was added for sbt -0.11.x, I am using sbt-package-dist 1.0.7(which I had upgraded as recommended on #61 ), 

Here's the error trace of unresolved dependencies:-

[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter#sbt-package-dist;1.0.7: not found
[warn] 	:: com.twitter#sbt11-scrooge;3.0.0: not found
[warn] 	:: com.twitter#sbt-thrift2;0.0.1: not found
[warn] 	:: com.twitter#scalatest-mixins_2.10;1.0.3: not found

Is sbt 0.13  even supported? If not what are some of the alternatives for me (scala newbie here :) )

**Comment by mosesn** [comment]
@anupamaggarwal we ship an sbt with finagle to avoid these exactly problems :).  Can you try using the one in the root of the finagle directory?  For what it's worth, we use 0.13.9 ourselves, so there might be something else going on though.

**Comment by anupamaggarwal** [comment]
@mosesn thanks for the response, my bad I should have been more specific and should have filed the issue under scala-bootstrapper.  The problem I am facing is not with compiling finagle but compiling a finagle based service generated using scala-bootstrapper.

**Comment by mosesn** [comment]
@anupamaggarwal no worries!  If you have any more finagle questions, feel free to drop into the gitter or to ask a question on the mailing list, which is the finaglers google group.
