### ISSUE TITLE
Change HttpDtab to encode Dtab-local headers

### ISSUE THREAD

**Issue by olix0r** [twitter/finagle#485]
In August 2014, finagle-http changed to read `Dtab-local` headers (https://github.com/twitter/finagle/commit/88ede12847c996547381a2b990b3aaf4f8f99759).  The intent of this change was that we would later be able to stop encoding `X-Dtab` headers (which are substantially more complicated).

I would like to change HttpDtab.write to encode `Dtab-local` headers.  `X-Dtab` headers should be considered deprecated at this point, though we will continue to support _reading_ these headers.

I'll prepare a change.  Please feel free to raise questions before I do so, @kevinoliver @mosesn @atollena @edma2.

**Comment by mosesn** [comment]
:ship: :it:

**Comment by atollena** [comment]
+1.

**Comment by kevinoliver** [comment]
sg, thanks.
