### ISSUE TITLE
Document how to use Reader safely

### ISSUE THREAD

**Issue by mosesn** [twitter/finagle#488]
From #475 it's not obvious how to make sure you close all of your read handles all the time, especially if you want to be able to time out from the client-side.

```
val reader: Reader = ??? // got this from someone at the airport
Reader.readAll(response.reader)
  .raiseWithin(20.milliseconds)
  .onFailure { timeout: TimeoutException => response.reader.discard() }
```

is a safe way of using a reader when you want to fully buffer it, but it's not necessarily obvious why.  Make sure it's easy to understand what's going on with read handles, and how to make sure they're closed.

**Comment by kevinoliver** [comment]
@vkostyukov have we addressed this in the recent `Reader` work?

**Comment by vkostyukov** [comment]
> @vkostyukov have we addressed this in the recent `Reader` work?

Yes, we now have:

 - Docs for readers: f069921af3a986bb74afca01c0e370dfe2dca4cc
 - Docs for writers: 0d183b77e43cd2160ec1bfc2c1f348341989a1cc
 - Docs for pipes: 1d6e539ecd41afb844c9c946b071b367b05c0fd2

**Comment by vkostyukov** [comment]
But, there is still plans to add more docs with regards to Request/Response types and their streams (readers and writers).

**Comment by kevinoliver** [comment]
Thanks, I'm closing this as we aren't working off this ticket directly.
