### ISSUE TITLE
Duplicate tags seem stuck client

### ISSUE THREAD

**Issue by liyichao** [twitter/finagle#490]
The commit: https://github.com/twitter/finagle/commit/e1e3a1ab085a62da637dbf84834872a565919200

seems to cause: https://github.com/openzipkin/zipkin/issues/1015

It seems the transport is not compatible with thrift protocol.

**Comment by mosesn** [comment]
@liyichao thanks for the bug report!  Which thrift client are you using?  Is it the one in go?

**Comment by liyichao** [comment]
Yeah，thrift version is 0.9.1

**Comment by mosesn** [comment]
Hmm, that's interesting.  finagle has been pegged to thrift 0.5.1 for a long time, I wonder if this might be a problem?  Can thrift 0.9.1 clients talk to thrift 0.5.1 servers?

**Comment by liyichao** [comment]
Yeah, the program works when zipkin is at 1.25.3 where finagle is at 6.33.0. So, I think the answer is yes.

**Comment by roanta** [comment]
The referenced patch should actually fix the issue you're describing, it was a bug in 6.33.0. Please try to upgrade to 6.34.0 which contains this fix.

**Comment by liyichao** [comment]
@roanta Thanks, after zipkin upgrading finagle to 6.34.0, the symptom disappears.
