### ISSUE TITLE
Following redirects in HTTP client

### ISSUE THREAD

**Issue by tindzk** [twitter/finagle#500]
An endpoint that I am requesting may redirect to another page, of which I need to access the data stream. I ended up with the following code:

```scala
client(request).flatMap { response =>
  if (response.status != Status.Found) Future.value(response)
  else {
    val newRequest = RequestBuilder().url(response.location.get).buildGet()
    val newClient = Http.client.newService(newRequest.host.get + ":80")
    newClient(newRequest)
  }
}.map(_.reader)
```

Could we introduce an option to automatically follow redirects?

**Comment by kevinoliver** [comment]
My recommendation is to create a "Follow Redirects" Filter and then compose
it with your client.

If you think it is general purpose enough and others could use it, create a
PR adding it to `com.twitter.finagle.http.filter`.



On Tue, Apr 26, 2016 at 3:44 AM, Tim Nieradzik <notifications@github.com>
wrote:

> An endpoint that I am requesting may redirect to another page, of which I
> need to access the data stream. I ended up with the following code:
>
> client(request).flatMap { response =>
>   if (response.status != Status.Found) Future.value(response)
>   else {
>     val newRequest = RequestBuilder().url(response.location.get).buildGet()
>     val newClient = Http.client.newService(newRequest.host.get + ":80")
>     newClient(newRequest)
>   }
> }.map(_.reader)
>
> Could we introduce an option to automatically follow redirects?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/finagle/issues/500>
>



-- 
Kevin Oliver | Twitter, Inc | follow me: @kevino <http://twitter.com/kevino>

**Comment by mosesn** [comment]
@tindzk I think we've answered your question.  If you decide your filter is general-purpose enough, please feel free to make a PR, and we can look at whether we want to add it to finagle!  I'm closing this ticket for now, but please feel free to reopen it if you have more questions or you want to talk more about building this kind of filter.
