### ISSUE TITLE
netty4-http: assertion failed with gzip-encoded responses

### ISSUE THREAD

**Issue by olix0r** [twitter/finagle#509]
```
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at com.twitter.finagle.netty4.http.Netty4ClientStreamTransport$$anonfun$read$2.apply(StreamTransports.scala:178)
```

Based on latest develop.  Http client with Netty4Impl & withStreaming(true).

When a client receives a response like:
```
< HTTP/1.1 200 OK
< Content-Type: text/html;charset=UTF-8
< Content-Encoding: gzip
< Content-Length: 809
< 
...
```

**Comment by dschobel** [comment]
can you paste the full client config?

**Comment by olix0r** [comment]
It's not _exactly_ that straightforward, since in linkerd we don't have a single place where we just list all of our client params (it's composed over several layers of configuration).  But, basically:

    StackClient.defaultParams +
      FailFastFactory.FailFast(false) +
      param.Stats(DefaultStatsReceiver.scope("rt")) +
      FinagleHttp.param.Streaming(true) +
      ProtocolLibrary("http") +
      Netty4Impl

Furthermore, we have configured a RetryBudget, etc.

**Comment by dschobel** [comment]
yeah that assert is wrong, the logic is there to sanity check against fixed length messages falling into the transport collating case but only accounts for chunked transfer encoding and misses non-identity content encodings.

I'll fix it up. Thanks for the report.

**Comment by dschobel** [comment]
fix landed internally and will sync out on Monday.

**Comment by mosesn** [comment]
Landed in `develop`!  https://github.com/twitter/finagle/commit/1b67f5562aac076de32b544229ce30e42a477285
