### ISSUE TITLE
finagle-http: client does not properly handle `Connection: close` 

### ISSUE THREAD

**Issue by olix0r** [twitter/finagle#517]
BuoyantIO/linkerd#482 describes a situation where clients unexpectedly throw a ChannelClosedException.  The scenario is basically:

- Requests being issued from linkerd to a non-Finagle HTTP server on a persistent connection.
- Server responds to a message with `Connection: close`
- Server closes connection.
- Finagle client may issue additional requests on this connection
- requests fail with ChannelClosedException

Per [RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html):
> HTTP/1.1 defines the "close" connection option for the sender to signal that the connection will be closed after completion of the response. For example,
>
>       Connection: close
>
> in either the request or the response header fields indicates that the connection SHOULD NOT be considered `persistent' (section 8.1) after the current request/response is complete.

This seems like a race condition, as the error behavior is not easily triggered unless there are multiple concurrent requests on the connection.

I've written a [small Go HTTP server that reproduces this behavior](https://gist.github.com/olix0r/872f206ed22fce058fcd67c7fdc52e65).  This server can be started with `go run shutter.go`.  Then, configure a finagle HTTP client to issue requests to /$/inet/127.1/8080 (such that there are at least 2 requests issued in parallel) and an error will be encountered.

This issue is observed with both netty3 and netty4 http implementations.

Is this issue known?

I'm happy to help further diagnose/fix this problem, but any pointers are appreciated.

**Comment by olix0r** [comment]
In one of the test, I see that out of about 60K total requests, with ~6.5K server-disconnects, we observe ~550 ChannelClosedExceptions (exceptions caused by 8.5% of disconnects).

**Comment by olix0r** [comment]
I think I have a fix for this. Forthcoming...

**Comment by vkostyukov** [comment]
I've never seen that we've handled that `Connection: close` header in Finagle. I guess we just ignore it right now? Looks like there is a window between receiving a response with `Connection: close` and `channelInactive` event in the pipeline, in which we see `ChannelClosedException`.

**Comment by olix0r** [comment]
It looks like `ConnectionManager` is supposed to handle this:

```scala
  def observeResponse(response: Response, onFinish: Future[Unit]): Unit = synchronized {
    if ((!response.isChunked && response.contentLength.isEmpty) || !response.isKeepAlive) isKeepAlive = false
   ...
```

`Message.isKeepAlive` checks `Connection: close`.

I'm going to look at HttpTransport to see if it's possible that write() occurs before the read operation completes? or something like that?

**Comment by roanta** [comment]
Does `ConnectionManager` affect the `status` of the respective `Service`? Could there be a race where the `Service` is put back in the connection pool and reused before `ConnectionManager` closes the connection?

**Comment by olix0r** [comment]
Interestingly, it appears that netty4 does _not_ exhibit this behavior and netty3 does.  I'll run more tests to confirm this.

**Comment by olix0r** [comment]
i've added debug logging to com.twitter.finagle.http.codec.ConnectionManager and I see something interesting:

```scala
    if (debug && !isKeepAlive)
     println(s"ConnectionManager.observeMessage($message) alive=$isKeepAlive streams=$activeStreams idle=$isIdle close=${shouldClose}")
```

in netty3:
> ConnectionManager.observeMessage(Response("HTTP/1.1 Status(400)")) alive=false streams=1 idle=false close=false

in netty4:
> ConnectionManager.observeMessage(Response("HTTP/1.1 Status(400)")) alive=false streams=0 idle=true close=true

I'm wondering if there are differences in the way that onFinish is satisfied between implementations (such that activeStreams is decremented differently).

Surpisingly, Netty3StreamTransport seems to satisfy onFinish immediately:
```scala
  private[this] val readFn: NettyOut => Future[Multi[Out]] = {
    case res if !res.isChunked =>
      val reader = BufReader(ChannelBufferBuf.Owned(res.getContent))
      Future.value(Multi(mkMessage(res, reader), Future.Done))
```

So maybe there  is something else at play...

**Comment by olix0r** [comment]
Indeed, onFinish.isDefined is false in netty3 and is true in netty4.  This causes the connection manager to indicate that the connection should not be closed immediately in netty3.

**Comment by olix0r** [comment]
It appears that the response:
```
HTTP/1.1 400 Bad Request
Connection: close
```
is marked as chunked(!).

While a request with an explicit content-length is correctly marked as not chunked:
```
HTTP/1.1 400 Bad Request
Connection: close
Content-length: 0
```

So, this problem is exhibited with chunked responses on which `Connection: close` is set (as is the case in the [original ticket](https://github.com/BuoyantIO/linkerd/issues/482)).

**Comment by olix0r** [comment]
And I've reproduced this problem in netty4, so it's not limited to a single netty version.  My guess is that netty4 doesn't treat
```
HTTP/1.1 400 Bad Request
Connection: close
```
as a chunked request and so it did not exhibit this error.

When [forcibly setting a chunked response with `Connection: close`](https://gist.github.com/olix0r/872f206ed22fce058fcd67c7fdc52e65#file-shutter-go-L37), I can reproduce this problem in either netty version.

**Comment by olix0r** [comment]
I added debug logging to HttpTransport to report on read(), write() and status:

Issuing the the request:
> transport.status = Open
> transport.write()

receiving the response:
> transport.reading
> transport.read(onFinish.isDefined=false)

response.isKeepAlive is _false_ beecause `Connection: close` was set, but `shouldClose` is false because `isIdle` is false because the response stream has not ended yet...
> Response("HTTP/1.1 Status(400)") alive=false streams=1 idle=false close=false finished=false

Something checks the transport's status after the response is satisfied. The status is reported as Open because the response chunk's onFuture hasn't been satisfied:
> transport.status = Open
> transport.status = Open
> transport.status = Open

Another request is written on the transport:
> transport.write()
> transport.reading

> transport.status = Closed
> transport.status = Closed

Finally, we observe the connection closed exception after the write is attempted:
> E 0617 21:30:02.255 THREAD72: service failure
com.twitter.finagle.ChannelClosedException: Connection reset by peer at remote address: /127.0.0.1:8080 from service: 0.0.0.0/4141. Remote Info: Upstream Address: /127.0.0.1:51654, Upstream Client Id: Not Available, Downstream Address: /127.0.0.1:8080, Downstream Client Id: #/io.l5d.fs/ugly, Trace Id: 7c3d9122adfd0926.a041f45e3a33e464<:7c3d9122adfd0926
```

**Comment by mosesn** [comment]
OK, so it sounds like that's it?  We should add some extra state to ConnectionManager to keep track of whether we've ever seen an `isKeepAlive` that's false?

**Comment by olix0r** [comment]
I think I understand the issue now:

We have a client stack somewhat like the following:

- ...
- FactoryToService
- ...
- WatermarkPool
- CachingPool
- ...
- HttpClientDispatcher
  - HttpTransport
    - ConnectionManager

When a response is read in the HttpTransport, it is passed through _ConnectionManager.observeResponse(rep, onFinish)_. The response has `Connection: close` and `Transfer-encoding: chunked`, and so the ConnectionManager is set with `isKeepAlive = false` and `activeStreams = 1` (and so _ConnectionManager.shouldClose_ returns false).

The HttpClient dispatcher essentially works as follows:
```scala

def apply(req: Req): Future[Rep] = {
  val p = new Promise[Rep]

  semaphore.acquire().respond {
    case Return(permit) =>
      dispatch(req, p).respond {
        case t@Throw(_) =>
          p.updateIfEmpty(t.cast[Rep])
          permit.release()
        case Return(_) =>
          permit.release()
      }
    case t@Throw(_) =>
      p.update(t.cast[Rep])
  }

  p
}

def dispatch(req: Request, rep: Promise[Response]) = {
  ...
  Future.join(Seq(
    trans.write(req),
    trans.read().flatMap {
      ...
      case Multi(res, readFinished) =>
        p.updateIfEmpty(Return(res))
        readFinished
    }
  ))...
```

There are two important events that occur when handling a response:

First, the response promise is satisfied.  This causes FactoryToService to close the underlying service:
```scala
  def apply(request: Req): Future[Rep] =
    factory().flatMap { service =>
      service(request).ensure {
        service.close()
      }
    }
```

When FactoryToService calls _service.close()_, _CachingPool.WrappedService.close()_ checks the _status_ of the underlying transport. This status check reports Open because  _ConnectionManager.shouldClose_ returns false (because readFinished hasn't been satisfied yet), and the service is returned to CachingPool's cache.

At this point, a new request is received by the client and a ServiceFactory is acquired from the CachingPool. Unfortunately, the caching pool returns the same service factory that's currently being used to complete the initial response---the one that's about to close. The http client dispatcher tries to dispatch the request, but it cannot do so until the dispatcher's semaphore is released (and so it waits on _acquire()_).

Then, the initial response's _readFinished_ future is satisfied and the client dispatcher releases the semaphore, allowing the second request to be dispatched & written. By then, the server has already town down the connection, and writing the second request fails with a ConnectionClosedException.

So, the root of the problem is that FactoryToService closes the service once the response is satisfied and before the response stream has finished.  We wouldn't see this problem if close() was called after the response stream was finished, but there doesn't appear to be an API for receiving this notification outside of the dispatcher.

Another option is to change the ConnectionManager/Dispatcher to indicate status as Closed as soon the response is observed. I'm unsure of the implications of indicating that the Dispatcher is Closed while it's still processing a stream, but I'm concerned that this may cause the stream to be torn down prematurely.

**Comment by olix0r** [comment]
This is an issue with linkerd -- I inserted a FactoryToService without a DelayedReleaseService under it. Inserting DelayedReleaseService fixes this issue. :tmyk:

**Comment by olix0r** [comment]
Reopening to discuss another (seemingly related) issue.

Adding a DelayedFactoryService under FactoryToService does indeed appear to fix this issue.  However, when I test this configuration against Netty4, I appear to still observe connection closed errors (though at a much lower frequency than before). Here's what I think is happening:

We have a stack like:

- FactoryToService
- DelayedReleaseService
- ...
- CachingPool
- ...
- HttpClientDispatcher
  - HttpTransport
    - netty4.ChannelTransport
    - ConnectionManager

Sometimes the server responds with a message that has
```
Connection: close
Transfer-encoding: chunked
```

Usually, the client handles this properly such that:

- The response is received on the transport
- ConnectionManager observes the responses, marking _isKeepAlive=false_. _activeStreams_ is set to _1_ since the response has not completed yet.
- FactoryToService begins closing the underlying service
- DelayedReleaseService prevents the underlying service from closing until the response is complete
- The response body is read.
- The ConnectionManager is updated, marking _activeStreams=0_ so that _shouldClose_ returns true.
- DelayedReleaseService observes the stream completion and closes the underlying service
- CachingPool checks the status of the underlying service which is _Closed_, and the transport is torn down.

However, _sometimes_ we observe the following:

- The response is received on the transport
- ConnectionManager observes the responses, marking _isKeepAlive=false_. _activeStreams_ is set to _1_ since the response has not completed yet.
- FactoryToService begins closing the underlying service
- DelayedReleaseService prevents the underlying service from closing until the response is complete
- The response body is read.
- DelayedReleaseService observes the stream completion and closes the underlying service
- CachingPool checks the status of the underlying service which is _Open_ (because ConnectionManager has not updated yet, transport is returned to CachingPool.
- A new request is processed, and provisions the cached transport from CachingPool.
- The ConnectionManager is updated, marking _activeStreams=0_ so that _shouldClose_ returns true, but it's already too late because the transport is not checked.

So, I think it's possible that DelayedReleaseService observes that the stream has been completed and closes the service before the ConnectionManager has observed this event.

DelayedReleaseService wraps responses so that a promise is satisfied when the reader observes a stream termination.

ConnectionManager uses the future returned from from:
```scala
  def copyToWriter[A](
    trans: Transport[_, A],
    writer: Writer
   )(eos: A => Boolean)(chunkOfA: A => Buf): Future[Unit] =
    trans.read().flatMap { a: A =>
      val chunk = chunkOfA(a)
      val writeF =
        if (!chunk.isEmpty) writer.write(chunk)
        else Future.Done
      if (eos(a))
        writeF
      else
        writeF.before(copyToWriter(trans, writer)(eos)(chunkOfA))
    }
```

So, I think this means that a reader's read promise may be satisfied before a writer's write-promise is?

I'm not sure why this race only appears to manifest with Netty4.

**Comment by olix0r** [comment]
It does appear that Reader.writable() may satisfy read requests promises before write promises are satisfied:
```scala
    def write(buf: Buf) =
      ...
        case Reading(n, p) =>
          // pending reader has enough space for the full write
          state = Idle
          p.setValue(Some(buf))
          Future.Done

```

**Comment by olix0r** [comment]
It seems that a minor change to Transport.collate resolves this:

```patch
diff --git a/finagle-netty4-http/src/main/scala/com/twitter/finagle/netty4/http/StreamTransports.scala b/finagle-netty4-http/src/main/scala/com/twitter/finagle/netty4/http/StreamTransports.scala
index b806424..ee139aa 100644
--- a/finagle-netty4-http/src/main/scala/com/twitter/finagle/netty4/http/StreamTransports.scala
+++ b/finagle-netty4-http/src/main/scala/com/twitter/finagle/netty4/http/StreamTransports.scala
@@ -48,10 +48,16 @@ private[http] object StreamTransports {
   )(eos: A => Boolean): Reader with Future[Unit] = new Promise[Unit] with Reader {
     private[this] val rw = Reader.writable()
 
-    become(copyToWriter(trans, rw)(eos)(chunkOfA).respond {
-      case Throw(t) => rw.fail(t)
-      case Return(_) => rw.close()
-    })
+    val f = copyToWriter(trans, rw)(eos)(chunkOfA)
+    forwardInterruptsTo(f)
+    f.respond {
+      case r@Throw(t) =>
+        updateIfEmpty(r)
+        rw.fail(t)
+      case r@Return(_) =>
+        updateIfEmpty(r)
+        rw.close()
+    }
 
     def read(n: Int): Future[Option[Buf]] = rw.read(n)
 
```

This causes the collation future to be satisfied before the reader is closed, so that the transport may observe the state before other readers do.  I'll test this a bit longer and, if the error does not appear, submit a PR

**Comment by roanta** [comment]
@olix0r nice sleuthing.

One thing to consider is that this (and the n3 impl) rely on the implementation details of the scheduler to ensure that the closures are ordered correctly. @dschobel and I were looking into this and we agreed that it might be nice to explore doing away with `DelayedReleaseService` and reconciling outstanding streams in the pool. We could change the status of the service to `Busy` via `ConnectionManager` and defer on the decision to close or put it back into the pool until it changes. This would be a bigger change, but I think it would make the code much easier to understand and reason about. If it's not something you're interested in exploring, I'm okay with the scheduler coupling since its effectively what we had before.

**Comment by olix0r** [comment]
@roanta interesting!  @adleong and I were just discussing how #518 is scheduler-dependent and more of a hack than a fix... I'm interested in improving this, but, if it's amenable to you, I think I'd prefer to ship the hack while we sort out what the proper solution looks like.

**Comment by roanta** [comment]
@olix0r that works for me. I'll work towards pulling in #518. Thanks again for digging into this.
