### ISSUE TITLE
DNS Resolving should be deferred to proxy when using HTTP proxy

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#523]
We are using a proxy to connect to APIs outside our network. In our case our local machine cannot resolve the DNS hostname and has to defer the DNS resolving to the proxy.

It appears that it is not possible to do so. When creating an `InetSocketAddress` with the hostname, Finagle fails with the exception below.

How should Finagle be configured? We current use the Transporter.HttpProxy configuration. (`client.configured(new Transporter.HttpProxy(getProxyAddress(), getProxyCredentials()).mk());`).

```
Caused by: java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:107)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:649)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at org.jboss.netty.handler.ssl.SslHandler.handleDownstream(SslHandler.java:521)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.channel.SimpleChannelHandler.connectRequested(SimpleChannelHandler.java:306)
        at com.twitter.finagle.netty3.ssl.SslConnectHandler.connectRequested(SslConnectHandler.scala:109) 
```

**Comment by vkostyukov** [comment]
Thanks @spockz for the bug report!

We do that for N4 but haven't had a chance to backport that to N3. You're more than welcome to do that and I'm happy to assist you with that. Any chance you want to take a stab and wire in `Transporter.HttpProxyTo` stack param in N3?

**Comment by spockz** [comment]
Yes @vkostyukov, I'm willing to give it a try. However, this week and weekend is swamped with courses and working at my home. @mosesn linked to a commit in the gitter room. I'll check whether that makes sense tomorrow. (It's a bit later here.)

**Comment by spockz** [comment]
FYI: This is the [commit](https://github.com/twitter/finagle/commit/b9b222cb5877b8c4faca755ce9d9f947024ab638#diff-8b7c2f5a15bf6822a18ff662cb633bdcR88) @mosesn mentioned.

https://github.com/twitter/finagle/commit/b9b222cb5877b8c4faca755ce9d9f947024ab638#diff-8b7c2f5a15bf6822a18ff662cb633bdcR88

**Comment by spockz** [comment]
I've created a [gist](https://gist.github.com/spockz/ebf0ccb47c912a21b924efc45d120859) with my on-going work. It doesn't compile yet.

**Comment by vkostyukov** [comment]
@spockz How is it going? Is there anything we can help with?

**Comment by Ashald** [comment]
@vkostyukov how that could be done with N4 proxy?

**Comment by vkostyukov** [comment]
@Ashald you'd need to add a dependency to `finagle-netty4-http` and switch your client over to N4 IO transport. Something like

```scala
import com.twitter.finagle.Http
import com.twitter.finagle.netty4.http.exp.Netty4Impl

Http.client
  .configured(NettyImpl).
  .withTransport.httpProxyTo("google.com")
  .newService("my-local-http-cluster")
```

**Comment by vkostyukov** [comment]
Please also note that N4 implementation should be considered experimental for now. We're still in the process of gaining confidence in it. That's why it's `exp`.

**Comment by Ashald** [comment]
@vkostyukov thanks!

I tried:
```
import com.twitter.util.Await
import com.twitter.finagle.Http
import com.twitter.finagle.http.{Request, Method}
import com.twitter.finagle.netty4.http.exp.Netty4Impl

val client = Http.client.configured(Netty4Impl).withTransport.httpProxyTo("service-available-only-through-proxy", None).newService("localhost:4140")
val req = Request(Method.Get, "/")
Await.result(client(req))
```

And the only thing I got is few log messages:
```
Sep 12, 2016 12:27:30 PM com.twitter.finagle.netty4.channel.ChannelStatsHandler channelRead
WARNING: ChannelStatsHandler received non-channelbuffer read
Sep 12, 2016 12:27:30 PM com.twitter.finagle.netty4.channel.ChannelStatsHandler channelRead
WARNING: ChannelStatsHandler received non-channelbuffer read
```

I wonder whether something wrong with my proxy or there is some kind of issue in Finagle Netty4 Proxy module?

**Comment by vkostyukov** [comment]
So the `Await.result()` never returns? Something has to be returned from the call - either a value or exception.

**Comment by vkostyukov** [comment]
Also if you don't use TLS/SSL you don't actually need TCP tunneling (don't need N4) and can simply send HTTP messages with proper `Host` header to your proxy server.

**Comment by Ashald** [comment]
> So the Await.result() never returns?
Yeah, I waited for ~ 5 mins but didn't get anything. 

> Also if you don't use TLS/SSL you don't actually need TCP tunneling (don't need N4) and can simply send HTTP messages with proper Host header to your proxy server.
OK, I think I'll go this way - thanks.

**Comment by spockz** [comment]
@vkostyukov I'll try to get my code up today.

**Comment by spockz** [comment]
The code is up in #555. :)

**Comment by mosesn** [comment]
@spockz I'm going to close this, since netty 4 is quickly becoming the default.  I don't think we're going to get a ton of value out of porting this back to netty 3 anymore.  If you want to revisit it, feel free to reopen!
