### ISSUE TITLE
Marking all instances down by `ResponseClassifier` should lead to `FailedFastExceptions`

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#529]
When an instance is marked as down by the `FailureAccrualFactory` on account of the `ResponseClassifier` the instance is still used and calls don't result in `FailedFastException`.

### Expected behaviour

I would expect a server to not be used when it is considered as down caused by `ResponseClassifier` and that when all instances are down that I get a `FailedFastException`.

### Actual behaviour

Actually the http client stays in `Busy` mode and the requests are sent to the instance. This happens regardless whether 1, 2, or more instances are configured in the client.

### Steps to reproduce the behaviour

The below testcase shows that all requests continue and return happily. The testcase fails on the last check

```scala
import com.twitter.finagle.{FailedFastException, Failure, Http, Service}
import com.twitter.finagle.http.{Request, Response, Status, Version}
import com.twitter.finagle.service.{FailureAccrualFactory, ReqRep, ResponseClass, ResponseClassifier}
import com.twitter.util._
import org.scalatest.{FlatSpec, Matchers}

class ResponseClassifiersTest extends FlatSpec with Matchers {
  "the responseclassifier" should "cause FailedFastExceptions by considering all responses as failures" in {
    val serverService:Service[Request, Response] = Service.mk(_ => Future.value(Response(Version.Http11, Status.Forbidden)))
    val server = Http.server.serve("127.0.0.1:*", serverService)
    val server2 = Http.server.serve("127.0.0.1:*", serverService)

    val depressedClassifier: ResponseClassifier = {
      case ReqRep(_,_) => ResponseClass.NonRetryableFailure
    }

    val client = Http.client
        .withResponseClassifier(depressedClassifier)
        .configured(FailureAccrualFactory.Param(1, Duration.fromSeconds(10)).mk())
        .newService(FinagleUtil.socketsToName(server.boundAddress, server2.boundAddress), "classifierTestClient")

    val testRequests = 5

    val responsesFuture: Future[Seq[(Try[Response], com.twitter.finagle.Status)]] =
      Future.collect(1 to testRequests map { (_:Int) =>
      client(Request("http://service/")).liftToTry.map {  (_, client.status) }
    })

    val responses = Await.result(responsesFuture, Duration.fromSeconds(1))

    println(responses)
    responses.size should be(testRequests)
    responses.map(_._1) exists {
      case Throw(_: FailedFastException) | Throw(Failure(Some(_:FailedFastException))) => true
      case _ => false
    } should be(true)


  }
}
```

**Comment by mosesn** [comment]
@spockz I think this is expected behavior.  When the loadbalancer marks all nodes as unhealthy, it just tries one.  The reason why you see "failed fast" is because "failed fast" happens when we can't even establish a tcp connection to the remote host, and the load balancer has picked that node as the one to send load to.  When something has triggered failure accrual, we still have the tcp connection, it's just that it has not had a good track-record success rate wise.  In general, our clients maximize success rate, which is why they're optimistic.

We're investigating cluster-wide overload prevention, so that if the overall cluster doesn't look too healthy it can shed load, but it doesn't exist yet.

**Comment by spockz** [comment]
@mosesn I understand the need to maximise the success rate. However, we should consider both connection errors and responses classified as errors equal for sake of simplicity and understandability.

Taking this into account, the current situation is counter intuitive. I would expect that when there are two nodes, where one of which is marked dead, that all traffic should go to the healthy node. 

However, and this is tested with 6.34.0 and 6.36.0, in my test, I have one server that returns Forbidden and another that returns 200 OK. The response classifier considers Forbidden to be a failure.

When running the test, I see a log message saying that a node is marked dead. However, I see both servers receiving load after that initial response from the error server. I've seen the following ratios of error/ok responses: 16/84, 3/7, 29/71, 7/93. The log-message makes me expect that the node isn't used anymore as it is marked as dead as do the metrics. However, it still receives messages. (PS: Delaying requests a bit instead of firing all requests at once puts the ratio at the expected 1/99 consistently.)

Moreover, there should be a way to observe that all your instances are considered dead based on the response classifier because it means your service is broken and you need to act. One can monitor for FailedFastExceptions to see whether there are no instances available to connect with but whether applications are failing on a functional level cannot be observed.

```scala
"the responseclassifier" should "cause traffic to go to the healthy node" in {
    val testRequests = 100
    val failureTolerance = 1
    val sleepTime = 10L // introducing a bit of delays actually 'fixes' things

    val serverService: Status => Service[Request, Response] = s => Service.mk { _ =>
      Future.value(Response(Version.Http11, s))
    }
    val server = Http.server.serve("127.0.0.1:*", serverService(Status.Forbidden))
    val server2 = Http.server.serve("127.0.0.1:*", serverService(Status.Ok))

    val errorClassifier: ResponseClassifier = {
      case ReqRep(_, Return(rep: Response)) if rep.status == Status.Forbidden => ResponseClass.NonRetryableFailure
    }

    val client = Http.client
      .withResponseClassifier(errorClassifier)
      .configured(FailureAccrualFactory.Param(failureTolerance, Duration.fromSeconds(30)))
      .newService(FinagleUtil.socketsToName(server.boundAddress, server2.boundAddress), "classifierTestClient")


    val responsesFuture: Future[Seq[(Try[Response], com.twitter.finagle.Status)]] =
      Future.collect(1 to testRequests map { (_: Int) =>
        Thread.sleep(sleepTime)
        client(Request("http://service/")).liftToTry.map {
          (_, client.status)
        }
      })

    val responses = Await.result(responsesFuture, Duration.fromSeconds(1))

    val counts: Map[Status, Int] = responses.groupBy(_._1.get().status).mapValues(_.length)
    println(counts)
    counts(Status.Ok) should be(testRequests - failureTolerance)
    counts(Status.Forbidden) should be(failureTolerance)
  }
```

**Comment by mosesn** [comment]
@spockz we typically set alerts on low success rate using the metrics we export.  would that work for your use case?

**Comment by spockz** [comment]
I would like to be able to act on that information programmatically inside the application, e.g. write to a different kind of log and taking a different functional path or disabling features.

**Comment by kevinoliver** [comment]
@spockz yeah, it seems reasonable to me that on the state change an event would fire. You you could do what you wish with that in the application layer. What are you thinking the events should look like?

**Comment by spockz** [comment]
@kevinoliver I'm not entirely sure how to listen to those events. Currently, we detect failure of all instances by monitoring `FailedFastException` and we log those occurrences. I would expect all failures to have the same effect so marking all instances down because of response classification should in my opinion also lead to a `FailedFastException`.

**Comment by kevinoliver** [comment]
ok i think i misunderstood what you were looking for. let me see if i can get up to speed.

first, are we talking about the case when all memcached nodes have been marked down via failure accrual (which happens to use response classification)? if so, do you want a callback or different behavior? or something else?

if not, what situation are you discussing?

**Comment by spockz** [comment]
@kevinoliver Exactly. My use-case was for the HTTP case specifically but I think the behaviour should be the same for all clients of course.

My understanding of failure accrual is to detect faulty instances in order to direct load to other, functional, instances. Previously, only connection errors counted for the failure-accrual. In order to compensate for this the Response Classifier was introduced. Now responses that are deemed errors by the response classification, functional errors for my purpose, count as errors towards ignoring an instance as well. This results in successful direction of traffic to instances that don't respond with functional errors.

Now consider the case that all servers return functional errors. Currently, requests will be sent to those instances and the caller will see the response. This is in contrast with connection errors that will trigger a `FailFastException`.

In my opinion connection failues and responses that are considered failures by the response classification should behave in exactly the same way instead of slightly different in some cases. Therefore, I expect to see `FailedFastExceptions` when all instances are considered down by the failure accrual.

**Comment by kevinoliver** [comment]
@spockz i'm not convinced we want to have different behaviors. to be explicit, prior to response classification failure accrual was not only responding to connection errors. timeouts and other network issues also would be included.

what i'm hearing is that you'd like to have a different behavior in the LB when no nodes are `Status.Open`. today this is not configurable but perhaps it should be. i have a patch that should show up on `develop` this Monday that doesn't change this, but it cleans this code up in the `Distributor`s and would make it easier to change. 

i'd be open to a patch that makes the behavior configurable when no nodes are Open. this is something we've discussed internally as well but we were fine with the current default. that said i'm not sure you'll get the level of control you are asking for — where you want different behavior based on how they got marked busy.

**Comment by spockz** [comment]
@kevinoliver I think we do agree. I want the behaviour of failure accrual to be equal, so the behaviour of the client should be the same when the node is marked dead because of connection issues and when it is marked dead because of responses marked as failure by the classifier.

Do you agree?

**Comment by kevinoliver** [comment]
`FailedFastException` is only used by `FailFastFactory` which indicates connection failures. whereas `FailureAccrualFactory` is used to change the status of a node to `Busy` which is used by the load balancer to route traffic around it. in other words, it doesn't return exceptions directly.

i think you are talking about the case when all nodes are marked `Busy` via `FailureAccrualFactory`. in that case, finagle's load balancer optimistically try to send traffic. if thats the case, i think you want to open a PR that allows you to change that load balancer's behavior to return a `FailedFastException` or perhaps something slightly different.

**Comment by mosesn** [comment]
@spockz I'm going to mark this as closed, since I think we answered your question?  please ping us on gitter if you still have questions.

**Comment by spockz** [comment]
The behaviour is clear. We introduced a filter that checks the status on the underlying service and completes with FailedFastException when that status is unavailable.
