### ISSUE TITLE
Make GlobalFlags java accessible

### ISSUE THREAD

**Issue by adriancole** [twitter/finagle#536]
One line summary of the issue here.

### Expected behavior

As a java user, I should be able to define global flags naturally.

### Actual behavior

The lookup system for global flags requires them to be scalaesque classes (ex. with a `$` suffix). Also, the naming convention isn't natural in java.

### Steps to reproduce the behavior

Here's what I had to do to make a valid flag in java. It would be much nicer to be able to define (and register them) with a static function vs stuff like this.

```java
public final class ZipkinFlags {

  // this class naming convention is required for global flags to work
  public static final class initialSampleRate$ extends GlobalFlag<Float> {
    public static final initialSampleRate$ MODULE$ = new initialSampleRate$();

    // to avoid making unnatural class names, I override the name here
    @Override public String name() {
      return "zipkin.initialSampleRate";
    }

    private initialSampleRate$() {
      super(
          BoxesRunTime.boxToFloat(Sampler$.MODULE$.DefaultSampleRate()),
          "Percentage of traces to sample (report to zipkin) in the range [0.0 - 1.0]",
          Flaggable$.MODULE$.ofJavaFloat());
    }
  }

  // this class naming convention is required for global flags to work
  public static final class initialSampleRate {

    // this method is looked up at runtime
    public static Flag<?> getGlobalFlag() {
      return initialSampleRate$.MODULE$.getGlobalFlag();
    }
  }

--snip--
```

**Comment by mosesn** [comment]
@adriancole sounds like a good idea to me!  do you mind moving this issue to the twitter/util project though?  GlobalFlag is part of util-app, not finagle.

**Comment by adriancole** [comment]
ahh of course. sure.

**Comment by adriancole** [comment]
https://github.com/twitter/util/issues/169
