### ISSUE TITLE
Is the Event.Type stuff in c.t.f.zipkin.core.SamplingTracer zipkin-specific?

### ISSUE THREAD

**Issue by adriancole** [twitter/finagle#540]
It seems there's a lot of untested code around json marshaling of events in `c.t.f.zipkin.core.SamplingTracer`, I'd love for this code to be moved somewhere else, for example, an event decorating tracer.
### Expected behavior

The package `c.t.f.zipkin.core` is expected to hold zipkin-specific code.
### Actual behavior

It seems that general purpose event codec and sink logic has been added into the SamplingTracer class last year. This is an unexpected conflation of concerns as marshaling Trace events to Event sink has nothing to do with zipkin.
### Steps to reproduce the behavior

Open SamplingTracer and find a bunch of awkward jackson code and event logic which hasn't anything to do with zipkin.

**Comment by adriancole** [comment]
ps by untested, I mean that there's nothing that shows the intent of the jackson logic apart from this bijection test https://github.com/twitter/finagle/blob/develop/finagle-zipkin-core/src/test/scala/com/twitter/finagle/zipkin/core/SamplingTracerTest.scala#L103

I'd basically like to write a drop-in replacement of SamplingTracer without having to guess the serialization format this jackson code is trying to create.

**Comment by kevinoliver** [comment]
Agreed about the conflation. You'd be fine writing a `SamplingTracer`replacement without that code, including the serialization. Running without it with only impact devs who want to use event tracing with this replacement and that could always be addressed separately.

**Comment by adriancole** [comment]
Thanks for the green light. Good point that these arent really coupled as
the event stuff can be added later!

**Comment by mosesn** [comment]
I think this is more of a question than an issue, so I'm going to close this ticket, since it seems to have been answered?  If I'm mistaken, please reopen!
