### ISSUE TITLE
InetResolver uses an unbounded thread pool

### ISSUE THREAD

**Issue by reikje** [twitter/finagle#544]
The `InetResolver` uses an unbounded threadpool under the hood. For applications that resolve a lot of `inet!....` destinations, this creates a lot of threads which can be a problem. Unfortunately this is not at all configurable. It's also not possible to extend and create a new `InetResolver` as it is package private. 
### Expected behavior

`InetResolver` can be used with a threadpool that can be configured if needed.
### Actual behavior

`InetResolver` uses `FuturePool.unbounded`
### Steps to reproduce the behavior

Create an application that creates a few hunded `Http.client` instances using `inet! ..` destinations. Do a thread dump and look for threads named `UnboundedFuturePool-xyz`.

**Comment by kevinoliver** [comment]
@edma2 or @atollena may have thoughts about this.

**Comment by atollena** [comment]
The number of concurrent DNS resolutions (and thus the number of threads spawned) is bound by a semaphore to a concurrency of 100:

https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/Resolver.scala#L109

I could see value in making that more configurable, but presumably this would need to be done via a global flag, since InetResolver is a singleton.

We are exploring the use Netty 4 DNS implementation (io.netty.resolver.dns) which would make this implementation obsolete, but in the mean time you could submit a patch to tune the max concurrency level.

**Comment by mosesn** [comment]
@reikje do you mind telling us about your use case?  why are you doing so many DNS resolutions?

**Comment by reikje** [comment]
@mosesn it's an application that listens on a event stream that a remote server provides. on the stream we receive notifications containing host:port of slave machines (nodes being added and removed). Before we start listening we receive all current nodes in one go, around 150-200 items. For each we create a finagle.Http.client using the `inet!host:port` destination, which will internally `bind` using the `InetResolver`.

@atollena Yes I was also thinking global flag. Rx is doing [this](https://github.com/ReactiveX/RxJava/blob/5be3a4b12f2a72fe194d347d6518f42a2920f61a/src/main/java/rx/internal/schedulers/EventLoopsScheduler.java#L27-L44) for instance, except that they use a system property instead of the flag. Regarding the semaphore, there is also this timer which periodically re-resolves using `FuturePool.unbounded` and is not guarded by the semaphore. I might be wrong here but I think there are scenarios where you can get to more than 100 threads in that pool. Even though under the hood it uses `newCachedThreadPool()` which will also shrink in size, it would be great to control the size somehow.

**Comment by edma2** [comment]
`InetResolver` has a `resolveHost` private constructor argument. Another way is to expose that in the public constructor and provide a default in a subclass with a different scheme identifier (e.g. `myinet!blah`). The benefit of this approach is you don't require any flags which are dependent on a particular `resolveHost` implementation (such as the private `DnsResolver`).

**Comment by mosesn** [comment]
@reikje it sounds like the event stream represents a service discovery endpoint.  you shouldn't have to create a new finagle client on each request–finagle clients are designed to work well with service discovery endpoints.  Have you considered making a Resolver that your finagle client can use?

**Comment by reikje** [comment]
@mosesn yes that would totally be possible but then I could just write my own `InetResolver` and use it with `myinet!` as scheme. The choice not to use a more advanced service discovery is on purpose, we want one Http client per endpoint.

@edma2 yes an easy fix would be to open up for extension and change package private scope to protected. I can provide a pull request but maybe there is a reason it shouldn't be extendable?

**Comment by edma2** [comment]
Let's pass a max concurrency parameter to InetResolver's factory which defaults to a global flag value.

**Comment by reikje** [comment]
This came up again here. Whats the status of this issue, can I help in any way?

**Comment by kevinoliver** [comment]
@reikje i think a PR would move things forward. looks like @edma2 [suggested](https://github.com/twitter/finagle/issues/544#issuecomment-242817389) injecting the `FuturePool` to use as a parameter to a new `InetResolver.apply` [method](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/InetResolver.scala#L50). this should be easy to do in a backwards compatible way.

**Comment by kevinoliver** [comment]
This got resolved in #579 thanks again.
