### ISSUE TITLE
Documentation/Getting started improvements

### ISSUE THREAD

**Issue by asheshambasta** [twitter/finagle#546]
Make documentation clearer and getting started easier.

### Expected behavior

Getting started guide leads to broken situations with no apparent explanation on how to approach things. 
I set up a simple Finagle project with `build.sbt` that looks like this;
```sbt
def finagleVer = "6.36.0"

resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

libraryDependencies ++= Seq(
  "com.twitter" %% "finagle-http" % finagleVer,
  "com.typesafe.play" %% "play-json" % "2.3.8"
)

fork in run := true
```

And I've run into some very weird issues.
Expected:
- should be able to follow the getting started guide from start to finish with the quick setup

### Actual behavior

- 6.36.0 fails to resolve
- tried with the sbt support in IntelliJ and the CLI with no luck.

### Steps to reproduce the behavior

- set up a simple project like stated above.

This makes the process of getting started very slow and painful, imo.

**Comment by mosesn** [comment]
@asheshambasta which version of scala are you running?  Please make sure you're on 2.11, we no longer support 2.10 as of 6.36.0.

**Comment by asheshambasta** [comment]
@mosesn 
That was it.
It would be helpful to add that [here](http://twitter.github.io/finagle/guide/Quickstart.html)

**Comment by mosesn** [comment]
@asheshambasta if you would like to make a PR, we would appreciate it!

**Comment by asheshambasta** [comment]
@mosesn https://github.com/twitter/finagle/pull/547
