### ISSUE TITLE
publish finagle-thrift gem

### ISSUE THREAD

**Issue by adriancole** [twitter/finagle#565]
Can someone publish finagle-thrift? (to https://rubygems.org/gems/finagle-thrift) There was a recent change to support 128-bit trace IDs that depends on this.

cc @nshkrob 

ps you might want to update the authors and owners, as it looks out-of-date

**Comment by adriancole** [comment]
@jcarres-mdsol fyi I'm pretty sure the zipkin gem will die on long ids until this happens

**Comment by bryce-anderson** [comment]
Done: https://rubygems.org/gems/finagle-thrift/versions/1.4.2

**Comment by adriancole** [comment]
thank you!
