### ISSUE TITLE
`RetryFilter` does not honour Interrupts

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#569]
`RetryFilter` keeps retrying, even if the request was interrupted.

### Expected behavior

No more retries should be executed once the originating request/response has been interrupted. In the testcase I should only see 1 request.

### Actual behavior

The RetryFilter keeps retrying.

### Steps to reproduce the behavior

Add a Timoutfilter on top of a RetryFilter on top of a failing service: https://github.com/spockz/finagle-testcases/blob/master/src/test/scala/finagle/tests/retry/RetryInterruptIT.scala

We could create a new Promise in the RetryFilter and use `.setInterruptHandler` to cancel any pending requests.

**update**: Do we want futures that are interrupted always to complete the value with the exception, or only when the interrupt was successful? And if we do return the 'real' result do we want to wrap the exception in a failure and set the interrupted flag?

**Comment by mosesn** [comment]
@spockz I think your test is incorrect.  note that `service(Request())` has already finished because it's synchronous.  I think it behaves correctly.

**Comment by spockz** [comment]
@mosesn I think you are right. I changed the test to include an actual http server and client and I'm seeing the expected behaviour: the timeout results in a failure that is interrupted.
