### ISSUE TITLE
remove libthrift 0.5-0-7 

### ISSUE THREAD

**Issue by allquantor** [twitter/finagle#571]
Old libthrift version is the possible origin of runtime class loader errors.

### Expected behavior
Newest finagle-thrift version should support the current thrift version.
### Actual behavior
```com.twitter:libthrift:jar:0.5.0-7:compile```
in classpath.

Can be the origin of class loader errors if overlap with current libthrift (0.9.3).
Any plans to remove it? 
Ivan

**Comment by taylorleese** [comment]
This isn't published yet, but please see https://github.com/finagle/finagle.github.io/pull/24. Also, see the notes in https://github.com/twitter/finagle/releases/tag/version-6.40.0.

**Comment by mosesn** [comment]
@allquantor you should be able to fix your problem by following @taylorleese's instructions, so I'm going to close this for now.
