### ISSUE TITLE
Make it possible to close client connections

### ISSUE THREAD

**Issue by sohamsankaran** [twitter/finagle#572]
It is currently not possible to close clients instantiated via the method interface (an example follows)

```
val client: LoggerService.FutureIface = Thrift.client.newIface[LoggerService.FutureIface]("localhost:1234")
```

### Expected behavior

A method such as ``client.close()`` should close the connection.

### Actual behavior

No easy way to do this exists. This [stackoverflow answer](http://stackoverflow.com/questions/34780815/how-do-i-close-a-finagle-thrift-client) seems like a hacky workaround, but does work.

**Comment by nepthar** [comment]
@sohamsankaran this does sound like something we should be able to do more easily. It would involve modifications to [Scrooge](https://github.com/twitter/scrooge).

This is something that we'd like to do, but hasn't yet landed on our roadmap. If you'd like to take a stab at a PR, we'd love to help you out/answer any questions that might come up!

**Comment by yufangong** [comment]
Hi @sohamsankaran , thanks for the report! Now you can close the connection by calling
client.asClosable.close().
