### ISSUE TITLE
finatra dependency problem between finagle-http and finagle-base-http

### ISSUE THREAD

**Issue by knightpop** [twitter/finagle#577]
One line summary of the issue here.

### Expected behavior

I use 
- finatra 2.6.0
- finagle 6.40.0
- twitter-util 6.39.0

and I want my server sbt assembly well

### Actual behavior

but get error duplicate dependency

`java.lang.RuntimeException: deduplicate: different file contents found in the following:
{homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferManager.class
{homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferManager.class
deduplicate: different file contents found in the following:
{homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$$anonfun$1.class
{homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$$anonfun$1.class
deduplicate: different file contents found in the following:
{homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$$anonfun$2.class
{homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$$anonfun$2.class
deduplicate: different file contents found in the following:
{homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$.class
{homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$.class
deduplicate: different file contents found in the following:
{homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$state$.class
{homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$state$.class
deduplicate: different file contents found in the following:
{homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker.class
{homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker.class
	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:140)
	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
	at sbtassembly.Assembly$.apply(Assembly.scala:83)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:241)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:238)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (iu-server/*:assembly) deduplicate: different file contents found in the following:
[error] {homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferManager.class
[error] {homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferManager.class
[error] deduplicate: different file contents found in the following:
[error] {homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$$anonfun$1.class
[error] {homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$$anonfun$1.class
[error] deduplicate: different file contents found in the following:
[error] {homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$$anonfun$2.class
[error] {homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$$anonfun$2.class
[error] deduplicate: different file contents found in the following:
[error] {homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$.class
[error] {homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$.class
[error] deduplicate: different file contents found in the following:
[error] {homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$state$.class
[error] {homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker$state$.class
[error] deduplicate: different file contents found in the following:
[error] {homedir}/.ivy2/cache/com.twitter/finagle-http_2.11/jars/finagle-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker.class
[error] {homedir}/.ivy2/cache/com.twitter/finagle-base-http_2.11/jars/finagle-base-http_2.11-6.40.0.jar:com/twitter/finagle/http/codec/ChannelBufferUsageTracker.class`

### Steps to reproduce the behavior

I just add dependency.
I resolve it by adding MergeStrategy

assemblyMergeStrategy in assembly := {
    ...
    ...
    case PathList("com", "twitter", "finagle", "http", "codec", xs @ _*)   => MergeStrategy.last
    ...
    ...
  },

**Comment by ryanoneill** [comment]
Hi @knightpop, thanks for the report. I checked this out with the versions you specified (finatra 2.6.0, finagle 6.40.0, util 6.39.0),  and I see the same issue that you do. Our apologies for that.

A few days ago though we [released updated versions of these libraries](https://finagle.github.io/blog/2016/12/23/release-notes-6-41/) (finatra 2.7.0, finagle 6.41.0, util 6.40.0), and I confirmed with those versions that this same issue no longer exists.
