### ISSUE TITLE
Prefer to avoid sending a retried request to the same server

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#585]
Retried requests might end up at the same server, failing again.

### Expected behavior

We want to avoid sending a request that failed to the same server again. In particular for small server sets, as chances for selecting the failing instance are higher.

### Actual behavior

We would like to try and select a different server than the one that gave the failed response.

### Discussed solution approaches

These approaches have been discussed with @kevinoliver at gitter.

#### Patch load-balancer
If somehow we keep track per request or retry which servers we have visited we could patch the load-balancer such that it would prefer not to pick the same instance again.

The down-side of this is that the load-balancer will get more complex which is undesirable. It could also be argued that this isn't a responsibility of the load-balancer.

#### Add an extra filter to the endpointStack
Instead of adding the logic to the load-balancer, we could add an extra filter/module to the endpoint stack which will fail a request if it has already seen it. The benefits are that the load-balancer isn't getting more complicated. The downside is figuring out what the behaviour should be in case that *all* servers in the server-set are hit but there is still RetryBudget left.

#### How to keep track
Another open point is how to keep track which servers have been hit for a request. It would be a waste if we spend cycles on the bookkeeping when requests aren't failing. The requeue or retry filter could e.g. only create the local context necessary for tracking the info once the request failed and initialise with the remoteAddress.

Your thoughts?

**Comment by kevinoliver** [comment]
+@roanta 

Some brief comments on this:
* The benefits need to outweigh the costs. 
* We should be able quantify probabilities for various cluster sizes. For example, given 3 retries and a backend of size (5, 10, 20, 100), what are the odds?
* Internally, we are moving towards using aperture as the default load balancer and as such we are more likely to see the same node selected for retries.

**Comment by roanta** [comment]
Something to note is that the client stack already attempts to avoid nodes that are performing poorly relative the rest of the server set. It does this via prioritizing the least latent endpoints and via circuit breakers. Have you found both of those mechanism to be insufficient in these cases? Maybe you can try to tune the circuit breakers to be more aggressive. For example, failure accrual can now keep track of a target SR and close the circuit when it is out of SLA.

**Comment by spockz** [comment]
@roanta do you have an example on how to configure the target SR?

In our case, most of the times, the instances that respond quickest are broken and return errors. Which means that we don't necessarily want to favour *the* fastest instances. Tuning the failure accrual to be more aggressive (less forgiving) would mean a higher risk of needlessly ignoring an instance and being very trigger happy. Retrying a request to a different node would allow to keep the FA more relaxed.

**Comment by roanta** [comment]
The SR failure accrual policy [1][2] is still experimental, so there isn't a `with*` style API for it. Instead, you have to use `configured` on the client:

```
$protocol.client
   .configured(FailureAccrualFactory.Param(FailureAccrualPolicy.successRate(...)))
```

You can also configure a response classifier [3] to take into account responses that look successful to finagle (i.e. are a `Return`), but really represent an application failure. This should help with the issue you described where the load balancer favors hosts that respond quickly with failures.

[1] https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/service/FailureAccrualFactory.scala#L129

[2] https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/service/exp/FailureAccrualPolicy.scala#L122

[3] https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/param/CommonParams.scala#L46

**Comment by nepthar** [comment]
@spockz I'm marking this as closed for now, considering where we are with the aperture rollout & failure accrual stuff.

Feel free to re-open (is that possible without admin status?) or create a new issue if you'd like to continue the discussion.
