### ISSUE TITLE
pending Metric in StatsFilter can be incorrect

### ISSUE THREAD

**Issue by reikje** [twitter/finagle#594]
The `pending` metric in the `StatsFilter` can be incorrect.

### Expected behavior

The metric should always contain the correct number of outstanding requests.

### Actual behavior

If `service(request)` is throwing an exception, the count is never decremented.

### Steps to reproduce the behavior

Create a `Server` that is throwing an `Exception` without wrapping it in a `Future`.

**Comment by mosesn** [comment]
Thanks for the bug report!  My guess would be that we should wrap `service(request)` in a try/catch block in https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/service/StatsFilter.scala.  @reikje do you want to take a stab at this?

**Comment by reikje** [comment]
Yes will do @mosesn :)

**Comment by reikje** [comment]
Created a pull request: https://github.com/twitter/finagle/pull/595 and also added some notes.

**Comment by vkostyukov** [comment]
Fixed by #595.
