### ISSUE TITLE
Finagle-mysql H2 support?

### ISSUE THREAD

**Issue by bachateraconfuego** [twitter/finagle#598]
Does finagle-mysql work with in-memory H2 db with an address like:

jdbc:h2:[file:][<path>]<databaseName>
jdbc:h2:~/test
jdbc:h2:file:/data/sample
jdbc:h2:mem

**Comment by mosesn** [comment]
Hi @bachateraconfuego, we don't support that, but people have added support for [postgres][0], so it might be worth looking into doing something similar for h2.  finagle-mysql isn't built on top of jdbc, but you can make a jdbc client participate neatly in the finagle ecosystem by wrapping calls to the client with a FuturePool.

[0]: https://github.com/finagle/finagle-postgres
