### ISSUE TITLE
HTTP request transfer-encoding header fix needed

### ISSUE THREAD

**Issue by herberteuler** [twitter/finagle#613]
Currently, providing content for a request is [the same](https://github.com/twitter/finagle/blob/develop/finagle-base-http/src/main/scala/com/twitter/finagle/http/Request.scala#L345) as [making](https://github.com/twitter/finagle/blob/develop/finagle-http/src/main/scala/com/twitter/finagle/http/netty/Netty3StreamTransport.scala#L38) it [chunked](https://github.com/twitter/finagle/blob/develop/finagle-netty4-http/src/main/scala/com/twitter/finagle/netty4/http/StreamTransports.scala#L171). This causes trouble in some case and needs to be fixed.

### Expected behavior

I have a server written with Finch (source omitted here), and sending POST requests with contents should work fine with Finagle http.

### Actual behavior

However, due to the above-mentioned behavior of Finagle http, sending a chunked POST request to it results in a response with status `404 Not Found`. The following example, although using `curl`, demonstrates such behavior of client written with Finagle http:

```
$ curl -v -X POST -d "" "http://..."
* About to connect() to ... port 5260 (#0)
*   Trying ... connected
* Connected to ... port 5260 (#0)
> POST ... HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-koji-linux-gnu) libcurl/7.19.7 NSS/3.12.10.0 zlib/1.2.3 libidn/1.18 libssh2/1.2.2
> Host: ...:5260
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 201 Created
< Content-Type: application/json
< Content-Length: 8
<
* Connection #0 to host ... left intact
* Closing connection #0
"test81"
$ curl -v -H 'Transfer-Encoding: chunked' -X POST -d "" "http://..."
* About to connect() to ... port 5260 (#0)
*   Trying ... connected
* Connected to ... port 5260 (#0)
> POST ... HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-koji-linux-gnu) libcurl/7.19.7 NSS/3.12.10.0 zlib/1.2.3 libidn/1.18 libssh2/1.2.2
> Host: ...:5260
> Accept: */*
> Transfer-Encoding: chunked
> Content-Type: application/x-www-form-urlencoded
>
> 0
< HTTP/1.1 404 Not Found
< Content-Length: 0
<
* Connection #0 to host ... left intact
* Closing connection #0
```

(I have to hide the actual host and the URL, sorry)

### Steps to reproduce the behavior

Create a POST request in the usual way and send it to the server is sufficient to reproduce the issue.

I propose deciding if the content of a request is present via the headers. It will be considered present if and only if there is a greater-than-0 value of `Content-Length` header, or there is a `Transfer-Encoding` header that contains `chunked`.

How do you think about this? If it is OK, I can prepare a pull request.

**Comment by nepthar** [comment]
After doing some digging, I think a PR would be most welcome here. Some notes:
- This MIGHT be a breaking change for some folks who rely on chunked encoding to just magically happen. ...if they exist :)
- Do you have an idea of how users will choose to make a chunked vs normal request?

**Comment by herberteuler** [comment]
Here is the plan.

#### Changes to `Request` and `Response` creations

This is where all user-visible changes exist. I checked the code and found that there was a similar issue in `Response` as well, so it might be preferable to change both `Request` and `Response`.

The common use cases include requests/responses (a) without contents, (b) with a single piece of content, and (c) with a (possibly infinite) sequence of contents (aka streaming).

Case (a) is not affected by this change.

For case (b), add a `size` parameter because it is the user who knows the actual size of the content, otherwise Finagle has to scan to find out, which is wasteful:

```scala
// For Request
def apply(version: Version, method: Method, uri: String, reader: Reader, size: Int) = ???

// For Response
def apply(version: Version, status: Status, reader: Reader, size: Int) = ???
```

These methods will not set the result message to chunked, but will instead set a proper `Content-Length` header.

The current methods can be reused for case (c) with their behaviors and thus semantics keeping unchanged.

```scala
// For Request
def apply(version: Version, method: Method, uri: String, reader: Reader) = ???

// For Response
def apply(version: Version, status: Status, reader: Reader) = ???
```

#### Changes to `Message`

Now it should be possible to identify a `Message` with contents by checking it headers. If it contains a `Content-Length` header or its `Transfer-Encoding` header contains `chunked`, then it has content(s). This is packaged as a new method:

```scala
def hasContents: Boolean = ???
```

#### Changes to `Bijections`

[`Bijections` for Netty 4](https://github.com/twitter/finagle/blob/develop/finagle-netty4-http/src/main/scala/com/twitter/finagle/netty4/http/Bijections.scala#L152) can be simplified because the request has been set up properly.

#### Changes to transports

Finally, the `write` methods in transports need to be changed. Currently they are defined as

```scala
  def write(msg: In): Future[Unit] =
    transport.write(from[In, NettyIn](msg)).rescue(wrapWriteException).before {
      if (msg.isChunked) streamChunks(rawTransport, msg.reader) else Future.Done
    }
```

A simple change to `if (msg.hasContents)` should suffice.

How do you think about this plan?

**Comment by mosesn** [comment]
@herberteuler I'm not sure that this simplifies things.  `Reader` is an API for byte streaming.  If you don't need to stream bytes (ie you provide a buf via `request.content = content`), then it's not chunked, if you do need to stream bytes, it's chunked.

Why does your finch server care whether it's chunked or not?  If you read the contents of the POST with `Reader.readAll(msg.reader)` then you won't get 404s anymore.  You could alternatively disable streaming on your server, and finagle would dechunk the message on your behalf.

**Comment by nepthar** [comment]
@herberteuler Thanks so much for digging into this. I've also just chatted with @mosesn a bit more about this.

Our conclusion here is that our lack of documentation should be fixed, and I've created a ticket internally to look into it.

In the meantime, can you accomplish what you're setting out to do by setting the content as Moses suggested?

**Comment by herberteuler** [comment]
I tested setting content with `content_=` and it worked. This is a non-issue and will be closed. Thank you for your time and the clarification.

**Comment by mosesn** [comment]
@herberteuler glad we could help!
