### ISSUE TITLE
Tolerate X-B3-Sampled: 1

### ISSUE THREAD

**Issue by adriancole** [twitter/finagle#617]
`X-B3-Sampled: 1` is not accepted while `X-B3-Sampled: true` is

### Expected behavior

While a lot of instrumentation leniently read "true" or "false", "1" and "0" are the most often used
ways of indicating tracing is on or off.

https://github.com/openzipkin/b3-propagation#sampled

### Actual behavior

In the http Codec.scala, we use toBoolean, which may have at some point worked with truthy values, but currently does not:

```scala
try Some(request.headerMap(Header.Sampled).toBoolean)
catch { case _: IllegalArgumentException =>
  None
}
```

This causes finagle to suspend traces from other apps, as it interprets "1" as unsampled.

### Steps to reproduce the behavior

You either write a unit test, or put a breakpoint at the catch to notice "1" is not accepted.

**Comment by adriancole** [comment]
@kevinoliver @mosesn I was just about to brag on how I have brave working sharing finagle's context in process. Then I realized that finagle is breaking processes between processes :P

While a workaround is to make an interceptor to rewrite the sampled header when we know downstream is finagle, it would be great to leniently read, or even better switch to 1|0 since most instrumentation use this convention.

**Comment by adriancole** [comment]
cheapest fix is to special case and look for the character '1' as anything else ends up '0' anyway

**Comment by mosesn** [comment]
For now let's leniently read, we can switch to writing 1|0 in a couple releases.  We need to give folks time to upgrade so that we don't break tracing for finagle services that aren't redeployed frequently.

**Comment by adriancole** [comment]
Perfectly sensible. I will raise a PR for 0|1 tolerant reads

**Comment by adriancole** [comment]
https://github.com/twitter/finagle/pull/619

**Comment by mosesn** [comment]
This was fixed here: https://github.com/twitter/finagle/commit/a6de338c0ffb0e7b6924f326cd0feac0bc9dad0a thanks!

**Comment by adriancole** [comment]
thanks for championing it
