### ISSUE TITLE
set useCacheForAllThreads false throw exception on buffer allocate

### ISSUE THREAD

**Issue by yzb808** [twitter/finagle#630]
1. PoolThreadLocalCache.initialValue()
 when **useCacheForAllThreads** is true, and thread is not a FastThreadLocalThread, then:
return new PoolThreadCache(heapArena, directArena, 0, 0, 0, 0, 0);
freeSweepAllocationThreshold is 0;

2. PoolThreadCache 
        if (freeSweepAllocationThreshold < 1) {
            throw new IllegalArgumentException("freeSweepAllocationThreshold: "
                    + freeSweepAllocationThreshold + " (expected: > 0)");
        }
Because freeSweepAllocationThreshold is 0, the exception will throw when allocate buffer.

3. test case
	@Test
	public void test() {
		PooledByteBufAllocator bufAllocator = new PooledByteBufAllocator(false,
				PooledByteBufAllocator.defaultNumHeapArena(), PooledByteBufAllocator.defaultNumDirectArena(),
				PooledByteBufAllocator.defaultPageSize(), PooledByteBufAllocator.defaultMaxOrder(),
				PooledByteBufAllocator.defaultTinyCacheSize(), PooledByteBufAllocator.defaultSmallCacheSize(),
				PooledByteBufAllocator.defaultNormalCacheSize(), false);
		ByteBuf byteBuf = bufAllocator.buffer(100);
		byteBuf.release();
	}

**Comment by nepthar** [comment]
Hi @yzb808, thanks for the report!

This looks to me like it lives in [Netty](https://github.com/netty/netty)'s io.netty.buffer, as opposed to Finagle. Perhaps you meant to open a ticket with them?

**Comment by mosesn** [comment]
@yzb808 did this cause you an issue in finagle?

**Comment by nepthar** [comment]
Hi @yzb808, I'm going to close this ticket for now. If you believe this is a finagle issue and you run into it again, feel free to open an issue again.

**Comment by yzb808** [comment]
thank you very much
