### ISSUE TITLE
Possible memory leak issue?

### ISSUE THREAD

**Issue by iyogi** [twitter/finagle#632]
Our Tomcat server, containing a java based application using finagle as client to invoke remote REST APIs, on stopping logs errors indicating likely memory leaks at SEVERE log level.

### Expected behavior
Stopping tomcat server should result in a clean shutdown with no error logged in catalina.log

### Actual behavior
Stopping tomcat results in errors in logs indicating (according to org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads) memory leak.
Sample log:
The web application [] appears to have started a thread named [X] but has failed to stop it. This is very likely to create a memory leak
where X = [finagle/netty3-*], [Hashed wheel timer #1], [util-jvm-timer-1] and [UnboundedFuturePool-*] 

### Steps to reproduce the behavior

- Use finagle as REST client service to invoke remote APIs
Service<Request, Response> finagleService = ....
finagleService.apply(request).toJavaFuture().get(1000, TimeUnit.MILLISECONDS)
- deploy the application to tomcat
- start the server
- invoke the finagle client service a few times
- stop the tomcat server. 
- Check catalina.log

### Version
- finagle (com.twitter:finagle-core_**2.11:jar:6.35.0** and com.twitter:finagle-http_2.11:jar:6.35.0)
- Java **1.8.0_121**
- Tomcat **7.0.69**

### Actual logs
INFO: Stopping service Catalina
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Hashed wheel timer #1] but has failed to stop it. This is very likely to create a memory leak.
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [util-jvm-timer-1] but has failed to stop it. This is very likely to create a memory leak.
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [UnboundedFuturePool-1] but has failed to stop it. This is very likely to create a memory leak.
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [UnboundedFuturePool-2] but has failed to stop it. This is very likely to create a memory leak.
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [UnboundedFuturePool-3] but has failed to stop it. This is very likely to create a memory leak.
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [com.twitter.concurrent.LocalScheduler$$anon$1] (value [com.twitter.concurrent.LocalScheduler$$anon$1@13f91d2c]) and a value of type [com.twitter.concurrent.LocalScheduler.Activation] (value [empty iterator]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [com.twitter.concurrent.LocalScheduler$$anon$1] (value [com.twitter.concurrent.LocalScheduler$$anon$1@13f91d2c]) and a value of type [com.twitter.concurrent.LocalScheduler.Activation] (value [empty iterator]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [com.twitter.concurrent.LocalScheduler$$anon$1] (value [com.twitter.concurrent.LocalScheduler$$anon$1@13f91d2c]) and a value of type [com.twitter.concurrent.LocalScheduler.Activation] (value [empty iterator]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [com.twitter.concurrent.LocalScheduler$$anon$1] (value [com.twitter.concurrent.LocalScheduler$$anon$1@13f91d2c]) and a value of type [com.twitter.concurrent.LocalScheduler.Activation] (value [empty iterator]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jul 12, 2017 4:06:46 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [com.twitter.concurrent.LocalScheduler$$anon$1] (value [com.twitter.concurrent.LocalScheduler$$anon$1@13f91d2c]) and a value of type [com.twitter.concurrent.LocalScheduler.Activation] (value [empty iterator]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jul 12, 2017 4:06:46 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-bio-8080"]
Jul 12, 2017 4:06:46 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["ajp-bio-8009"]
Jul 12, 2017 4:06:46 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-bio-8080"]
Jul 12, 2017 4:06:46 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["ajp-bio-8009"]
Disconnected from server

**Comment by mosesn** [comment]
@iyogi thanks for the report! have you actually detected any memory leaks?

**Comment by iyogi** [comment]
No. I added this issue based on what we observed in the tomcat log. 

- See [https://wiki.apache.org/tomcat/MemoryLeakProtection#cclThreadSpawnedByWebApp](https://wiki.apache.org/tomcat/MemoryLeakProtection#cclThreadSpawnedByWebApp) 
- Hanging ThreadLocal variables may be a code smell?

**Comment by mosesn** [comment]
@iyogi maybe I don't understand what's happening.  You can't rely on the JVM shutting down to shutdown all of the threads?

**Comment by mosesn** [comment]
@iyogi it doesn't sound to me like this is a memory leak, but for what it's worth, we don't expect you to use finagle as a servlet.  You might be better served by using finagle as a server.  I'm going to close this ticket for now, but we can revisit if you continue to have problems.
