### ISSUE TITLE
How to use Http.Client#withResponseClassifier() in Java

### ISSUE THREAD

**Issue by wouterd** [twitter/finagle#635]
Thanks for creating Finagle, it's helped me tremendously in creating more resilient clients. I have a project that should only contain Java code, I cannot use any Scala in it. (don't ask... =])

I'd like to define a custom ResponseClassifier in a Java project, setting it using Http.Client#withResponseClassifier()

### Expected behavior

I can create a new ResponseClassifier and add it to the client.

### Actual behavior

I can't find a way to create the ResponseClassifier in Java. There doesn't appear to be some kind of Java proxy class like with compose()

### Steps to reproduce the behavior

Try making this compile / work in java. I want to treat HTTP 500s as retryable failures.

```
Http.client()
   .withResponseClassifier(...)
   .newService(config.hostPort, "...")
```

**Comment by kevinoliver** [comment]
take a look at [ResponseClassifierCompilationTest.java](https://github.com/twitter/finagle/blob/develop/finagle-core/src/test/java/com/twitter/finagle/service/ResponseClassifierCompilationTest.java).

if you are a java user, we strive for full compatibility, though we sometimes miss things — please let us know when we do. the `*CompilationTest` classes will often help point you in the right direction.

**Comment by wouterd** [comment]
Thanks for the pointer. That helped a ton. Not as pretty as when done in Scala, but I've got it working now.
