### ISSUE TITLE
finagle-mysql: CLIENT_FOUND_ROWS

### ISSUE THREAD

**Issue by wpK** [twitter/finagle#637]
Right now it doesn't seem possible to change [Capability.FoundRows](https://github.com/twitter/finagle/blob/develop/finagle-mysql/src/main/scala/com/twitter/finagle/mysql/Capability.scala#L5).

Is there any plans on the future to allow modifying the client capabilities when creating a client?

More information for those that are not aware of what _CLIENT_FOUND_ROWS_ changes:

For [INSERT ... ON DUPLICATE KEY UPDATE](https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html) statements, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values. If you specify the _CLIENT_FOUND_ROWS_ flag, the affected-rows value is 1 (not 0) if an existing row is set to its current values.

**Comment by ryanoneill** [comment]
Hi @wpK, 

I don't believe we have any current plans here, but thanks for letting us know that you would like to use this feature. Is this something that you would be interested in working on and adding to finagle-mysql via a pull request?

Thanks, Ryan

**Comment by wpK** [comment]
Sure. I'll send over a pull request shortly.

**Comment by nepthar** [comment]
Fixed w/ PR #640
