### ISSUE TITLE
Finagle Mysql connect to Server using SSL

### ISSUE THREAD

**Issue by teodor-pripoae** [twitter/finagle#647]
Hi

I'm trying to connect to a Google Cloud SQL MySQL server using the provided certificates. I understand that first there is a plaintext handshake and then the connection gets upgraded to SSL. Is there a way to achieve this ?

### Expected behavior

It should succesfully connect to MySQL server.

### Actual behavior

```
[info] io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 550000000a352e372e31342d676f6f676c652d6c6f6700a1740e0026765f52160a566100ffff210200ffc11500000000000000000000011b316c074e3725015b7d5e006d7973716c5f6e61746976655f70617373776f726400
[info] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
[info] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[info] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[info] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
```

### Steps to reproduce the behavior

```scala
val sslClientConfiguration = SslClientConfiguration(
  hostname = None,
  keyCredentials = KeyCredentials.CertAndKey(
    certificateFile = new File(sslCertPath),
    keyFile = new File(sslPrivateKeyPath)
  ),
  trustCredentials = TrustCredentials.CertCollection(new File(sslCaCertPath))
)
    
var client = new Mysql.Client(newStack)
  .withCredentials(context.user, context.password)
  .withDatabase(context.database)
  .withMaxConcurrentPrepareStatements(maxPrepareStatements)
  .withTracer(Tracing.tracer)
  .withLabel(tracingLabel)
  .withMonitor(MysqlMonitor)
  .withCharset(Utf8mb4_bin)
  .withRequestTimeout(requestTimeout)
  .withSession
  .acquisitionTimeout(connectTimeout)
  .configured(
    DefaultPool.Param(
      low = context.lowWatermark,
      high = context.highWatermark,
      idleTime = context.idleTime.seconds,
      bufferSize = context.bufferSize,
      maxWaiters = context.maxWaiters
    )
  )
  .configured(
    Transport.ClientSsl(sslClientConfiguration)
  )
  .newRichClient(dest)
```

**Comment by vkostyukov** [comment]
Thanks for the issue, @teodor-pripoae!

I have to figure out how TLS works with MySql, I guess. Do you know if MySql negotiates TLS connections via its handshake message? If so, I don't think it's supported in Finagle. Right now, we can only support TLS connections that start with SSL handshake (there is no machinery to upgrade an existing connection to become TLS).

However, we're working on something similar for Mux right now. Hopefully, some of that work can be ported over for MySql.

**Comment by teodor-pripoae** [comment]
Mysql clients first send a client capabilities packet with SSL flag and the server responds with a server capabilities packet containing SSL flag. Then the client tries to upgrade the connection to SSL if the server supports it. I couldn't find more information about how tls works in mysql.

**Comment by ksilin** [comment]
+1 is there any progress on the SSL for MySQL issue?

**Comment by ryanoneill** [comment]
@ksilin Not as of yet, but I do expect us to add this at some point within the next few months.

**Comment by ryanoneill** [comment]
Hey folks, wanted to update this issue. Movement is happening here. We have a working prototype and are starting to ship some of the necessary changes to make this a reality. I would expect it to be available for use in the January Finagle release, or depending on the timing, at the latest February.

**Comment by ryanoneill** [comment]
This got put on the back burner for a bit, but as of the last release (19.6.0), SSL/TLS should now work with finagle-mysql.
