### ISSUE TITLE
Project does not build due to scrooge sbt plugin

### ISSUE THREAD

**Issue by justinhj** [twitter/finagle#649]
clone the project and run `sbt run` and you find that the project does not compile due to missing dependency

error] (*:update) sbt.ResolveException: unresolved dependency: com.twitter#scrooge-sbt-plugin;4.19.0-SNAPSHOT: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? a

On investigation I see that it is not built for the version of Scala the project uses by default.

Is building this plugin documented anywhere?

**Comment by mosesn** [comment]
@justinhj yep, there's a note in the README that explains you should peek in the [CONTRIBUTING.md](https://github.com/twitter/finagle/blob/master/CONTRIBUTING.md) doc, or you can build from stable versions by switching to the 'master' branch.

**Comment by crispywalrus** [comment]
@mosesn the underlying issue here is that `scrooge-sbt-plugin` was literally not published for ANY version of `sbt` This is kind of a big bug for me and anyone else outside of twitter that uses thrift with finagle.

**Comment by mosesn** [comment]
@crispywalrus ah, I see now.  We'll get right on that, thanks!

**Comment by dschobel** [comment]
@crispywalrus sorry about that, this should be fixed now

**Comment by crispywalrus** [comment]
I see it now, thanks @dschobel!
