### ISSUE TITLE
Finagle 7.1.0: JVM memory issues under high traffic

### ISSUE THREAD

**Issue by ptaillard** [twitter/finagle#652]
Hello all,

We recently upgrade our Finagle version from 6.2.0 to 7.1.0 (yes, it's a big jump :-) )
Since this upgrade, our application get some memory issues under high traffic only.
We use Finagle as HttpClient only and implemented using synchronous response way.
When the application is under traffic, the JVM memory increases gradually in few hours until  latency issues and crash. The behaviour seems to be a memory leak issue but under local/internal test, we don't see memory leak with JVM profiler.

Let's give you our Finagle configuration:
1/ HttpClient service creation:
```
client = ClientBuilder.get()
                    .stack(Http.client())
                    .hosts(computeHostWithPort(hosts, DEFAULT_PORT_SSL))
                    .tls(hostWithoutPort(hosts))
                    .hostConnectionLimit(hostConnectionLimit)
                    .keepAlive(keepAlive)
                    .tcpConnectTimeout(Duration.fromTimeUnit(connectionTimeoutMillis, TimeUnit.MILLISECONDS))
                    .requestTimeout(Duration.fromTimeUnit(requestTimeoutMillis, TimeUnit.MILLISECONDS))
                    .retries(1)
                    .logger(loggerFinagle);
client.failFast(failfast);

Service<Request, Response> httpClient = ClientBuilder.safeBuild(client);
```

2/ HttpClient send request:
```
Request request = Request.apply(version, method, url);
request.headerMap().add(HttpHeaders.Names.CONNECTION, HttpHeaders.Values.KEEP_ALIVE);
request.headerMap().add(HttpHeaders.Names.ACCEPT, "*/*");
request.headerMap().add(HttpHeaders.Names.HOST, host);
Future<Response> future = service.apply(request);
```

3/ HttpClient receive response:
```
try {
    Response response = Await.result(future, Duration.apply(requestTimeoutMillis, TimeUnit.MILLISECONDS));
  // If status code OK, then use jackson to deserialize the response using response.content().copiedByteArray() to our java bean
} catch(Exception exception) {
 // log errors
}
```

Did we miss something in our implementation which can explain our JVM memory issue?
Do we need to close the request after us it (request.close()) or Await.result do the job?

Thanks

**Comment by kevinoliver** [comment]
Ooof. So quick things first, neither of which will solve your problem —
1. Because `ClientBuilder` is immutable, your call to `failFast` is ignored since you don't use the result of it. This is not a memory leak, just may be a separate application configuration issue for you.
2. You should only need to use `Request.close` if you are doing streaming writes, and from your example, that does not appear to be the case.

As for what your memory leak is… nothing jumps out to me. I think we'll need some more details or clues to proceed. One suggestion is to capture the `jmap -histo` of the process as it leaks memory.

**Comment by ptaillard** [comment]
@kevinoliver Thanks for your answer.
Let's dive deeper and give you more details.

**Comment by ptaillard** [comment]
@kevinoliver 
We captured jvm memory using jmap on different times during the application life under traffic (and fix the failfast misconfiguration as you advised it).
Below you can see the jmap output (histo and heap).

- Few minutes after the start of the application:
[1-jmap_heap_start.txt](https://github.com/twitter/finagle/files/1336184/1-jmap_heap_start.txt)
[1-jmap_histo_start.txt](https://github.com/twitter/finagle/files/1336496/1-jmap_histo_start.txt)

- Few hours after the start of the application:
[2-jmap_heap_during_life.txt](https://github.com/twitter/finagle/files/1336226/2-jmap_heap_during_life.txt)
[2-jmap_histo_during_life.txt](https://github.com/twitter/finagle/files/1336497/2-jmap_histo_during_life.txt)

- And the last one, when the jvm memory and latency issue occured:
[3-jmap_heap_latency_issue_occured.txt](https://github.com/twitter/finagle/files/1336231/3-jmap_heap_latency_issue_occured.txt)
[3-jmap_histo_latency_issue_occured.txt](https://github.com/twitter/finagle/files/1336499/3-jmap_histo_latency_issue_occured.txt)


We noticed that the com.twitter.finagle.Stack$Node instances increased and seems to be not released => On the jmap heap, the Old generation increased as well.
That's why we thought it was a memory issue, maybe it could be also a restraint issue.
This behaviour is not visible on the old Finagle version 6.2.0.
Each server send around 30 000 000 requests (30 Millions) by day using Http Finagle client.

Does something jump out at you?
Thanks

**Comment by ptaillard** [comment]
@kevinoliver Could be this issue? https://finagle.github.io/blog/2016/09/01/block-party/

**Comment by kevinoliver** [comment]
I would not expect to see that many `Stack.Node`s. They are part of constructing a Finagle client (and server) and shouldn't number that many...

My guess is that you are creating a good number of clients, likely via `ClientBuilder.build`, and missed calling `Service.close` (or `ServiceFactory.close`) on them — causing the leak.

**Comment by ptaillard** [comment]
Yes you are right @kevinoliver 
Many thanks for your help, we will fix that.
