### ISSUE TITLE
API changes report for Finagle Core

### ISSUE THREAD

**Issue by lvc** [twitter/finagle#654]
Hi,

I'd like to share my results on API changes analysis for the Finagle Core library: https://abi-laboratory.pro/java/tracker/timeline/finagle-core/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars found at http://central.maven.org/maven2/com/twitter/finagle-core_2.11/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![finagle-core-2](https://user-images.githubusercontent.com/1517837/31268613-d59984b6-aa85-11e7-962d-8463e88e2f75.png)
![finagle-core-1](https://user-images.githubusercontent.com/1517837/31268614-d59a862c-aa85-11e7-9eec-331ea97dfdaf.png)

**Comment by kevinoliver** [comment]
@lvc thanks for the report.

couple of questions:

1. are these numbers good or bad? do you have a link to some context/color/opinions?
2. i see that the tool supports scala but couldn't find details on the support. does it understand scala's visibility modifiers? in other words, we treat code scoped to `private[finagle]` as non-public API and don't bother with release notes for those sorts of changes.

**Comment by mosesn** [comment]
Thanks @lvc!  I'm going to close this ticket for now, but it's very interesting, and thanks for sharing it.
