### ISSUE TITLE
"Extending Finagle" section of guide is broken

### ISSUE THREAD

**Issue by glassorio** [twitter/finagle#656]
Something is missing in [your developer guide](https://twitter.github.io/finagle/guide/developers/Extending.html)

For example the "Using a Netty 4 ChannelPipeline" subsection of "Server Protocol" section is empty.

**Comment by glassorio** [comment]
I have used the way back machine and found [a version of the page](https://web.archive.org/web/20161201065438/https://twitter.github.io/finagle/guide/Extending.html) where those sections are still there.

**Comment by ryanoneill** [comment]
Hi @glassorio, thanks for the report. I'll look into getting this fixed up again.

**Comment by yufangong** [comment]
Thank you for your report @glassorio, this is fixed.
