### ISSUE TITLE
Hashcode calculation of http.client never terminates

### ISSUE THREAD

**Issue by DieBauer** [twitter/finagle#669]
Calculating hashcode of the Http.Client never terminates when having a retrywithbackoff (infinite stream) set. 

### Expected behavior

```scala
val client = Http.client
println(s"$client with hashcode ${client.hashCode}")

val client2 = client.withRetryBackoff(Backoff.const(10.seconds))
println(s"$client2 with hashcode ${client2.hashCode}")
```
the second client with Backoff stream, will have a valid hashcode in finite time.

### Actual behavior

Calling hashcode on the second client, with backoff stream, will evaluate the infinite stream and thus never terminates.

### Steps to reproduce the behavior

See snippet above.

**Comment by ryanoneill** [comment]
Hi @DieBauer, thanks for reporting. This is definitely a bug. I was able to easily reproduce this given your steps. Is this something you would be interested in trying to fix via a pull request?

**Comment by DieBauer** [comment]
Hi @ryanoneill, I'd be interested ;) I tried an initial patch in #670.

**Comment by ryanoneill** [comment]
Oops, sorry I missed it. :)
