### ISSUE TITLE
Dtab support '{' and '}' characters

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#672]
Dtab entries are not allowed to contain `{` nor `}` characters. `{`, `}` should be supported.

### Expected behavior

`com.twitter.finagle.Dtab.read("/foo/{bar} => /foo/{bar}/12.34.56.78:1234")` should give `res: com.twitter.finagle.Dtab = Dtab(/foo/{bar}=>/foo/{bar}/12.34.56.78:1234)`.

### Actual behavior

scala> com.twitter.finagle.Dtab.read("/foo/{bar} => /foo/{bar}/12.34.56.78:1234")
java.lang.IllegalArgumentException: label char expected but '{' found at '/foo/[{]bar} => /foo/{bar}/12.34.56.78:1234'
  at com.twitter.finagle.NameTreeParsers.illegal(NameTreeParsers.scala:29)
  at com.twitter.finagle.NameTreeParsers.illegal(NameTreeParsers.scala:36)
  at com.twitter.finagle.NameTreeParsers.parseLabel(NameTreeParsers.scala:111)
  at com.twitter.finagle.NameTreeParsers.parseDentryPrefixElem(NameTreeParsers.scala:124)
  at com.twitter.finagle.NameTreeParsers.parseDentryPrefix(NameTreeParsers.scala:156)
  at com.twitter.finagle.NameTreeParsers.parseDentry(NameTreeParsers.scala:254)
  at com.twitter.finagle.NameTreeParsers.parseDtab(NameTreeParsers.scala:268)
  at com.twitter.finagle.NameTreeParsers.parseAllDtab(NameTreeParsers.scala:305)
  at com.twitter.finagle.NameTreeParsers$.parseDtab(NameTreeParsers.scala:12)
  at com.twitter.finagle.Dtab$.read(Dtab.scala:356)
  ... 36 elided

**Comment by adleong** [comment]
For what it's worth, [Linkerd](https://github.com/linkerd/linkerd/) currently depends on the behavior that `{` and `}` are not valid dtab characters:  https://github.com/linkerd/linkerd/blob/master/finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/PathMatcher.scala#L45

**Comment by spockz** [comment]
I'm game for supporting `*` otherwise. But it seems as if LinkerD also relies on that. I'm actually not seeing how LinkerD relies on `{}` not being valid syntax? Isn't LinkerD's path matcher run before Finagles?

**Comment by kevinoliver** [comment]
@spockz can you explain the motivation for wanting braces?

**Comment by adleong** [comment]
Yes, but if `/{foo}` is a valid finagle path, that won't be representable anywhere that Linkerd is expecting a path matcher because the segment will be interpreted as a variable capture and not as a literal path segment.  In other words, by allowing more things to be valid finagle paths, we would lose the ability to represent all valid finagle paths.

**Comment by spockz** [comment]
> @spockz can you explain the motivation for wanting braces?

We are looking up services not by key but by `host/method/pathTemplate` and this pathTemplate can contain variables. Currently we do `.newService("ourResolver!host/method/pathTemplate")`, but we want to move to paths so we can do `.newService("/endpoint/host/method/pathTemplate"). This is on order for us to be able to override resolutions through Dtab-local headers.

**Comment by kevinoliver** [comment]
so, my best guess to why braces aren't allowed, is that we wanted to be conservative in what we accepted. i'm not opposed to changing that restriction, but we'd want @adleong to be amenable to the patch. or perhaps we can come up with a different approach that works for both?

**Comment by mosesn** [comment]
@spockz is this something you're still interested in?  It sounds like you want to use braces similarly to how linkerd uses braces.

**Comment by spockz** [comment]
Yes, I’d like this in but haven’t found a way to do it in a compatible way to LinkerD. We are using the curly braces verbatim whereas in LinkerD they are used to mark something replaceable. Using underscores instead of curly braces means changing many of our other systems. Basically the endpoints including he curly braces are used as ids right now so that would be a pain to change.

@adleong, can you imagine a compatible way?

Otherwise we could try hooking into the serviceFactory.newService method to rewrite the string... that sounds hacky but preferable to changing all our IDs.

**Comment by adleong** [comment]
I don't really have anything to suggest.  Some form of encoding or escaping to encode curly braces as other Path legal characters maybe? 

I don't want to block development but we picked curly braces to use for this purpose specifically because we knew they were not legal Path characters.

**Comment by spockz** [comment]
If we could make the parser pluggable we could solve both our issues. We can just eat the curly braces and LinkerD can directly implement the parser instead of relying on parsing to fail. Does this sound feasible?

**Comment by mosesn** [comment]
I think the tricky thing here is propagation.  If some services respect curlies and some don't, propagating dtabs will be a mess.

@spockz going back to the original thing you were trying to get done, `.newService("/endpoint/host/method/pathTemplate")` looks like a fine format, and doesn't seem to have curlies.  What's the issue you ran into with this? It seems to me like you should be able to use it with the existing `ourResolver`.

**Comment by spockz** [comment]
Whoops. Missed this. Propagation will be a mess regardless of any change. Luckily we have relatively tight control on the used versions.

> .. doesn’t seem to have curlies 

My apologies, within our idiom pathTemplate is the template just like in swagger. That means that path parameters are encoded as `/mypath/{param}/remainder`.  This is what developers use in their newService, e.g. `.newService(“apis.com:GET:/accounts/{id}/transactions”)`.

@mosesn Do you know a way to let developers still use the form above but that we rewrite the string somehow to replace curly path parameters with underscores? The goal is that we can use DTabs to rewrite the name.

**Comment by mosesn** [comment]
@spockz how about using scala string interpolation?  we could do something like:

`dtab"apis.com:GET:/accounts/{id}/transactions"`

**Comment by spockz** [comment]
@mosesn interesting. I hadn’t thought of that. Our native java users (far majority) could use something like a `normalise` method. Sounds fair and straightforward.

**Comment by mosesn** [comment]
@spockz cool!  can you try it out and get back to us?  I'm going to close this ticket for now, but if it doesn't work out, we can reopen it.
