### ISSUE TITLE
400 Bad request against Grizzly server

### ISSUE THREAD

**Issue by politrons** [twitter/finagle#674]
One line summary of the issue here.

### Expected behavior

When I do an http request to Grizzly server using this code

>   val client: Service[Request, Response] = Http.newService("localhost:8080")
>   val request = http.Request(http.Method.Get, "/hello_server")

Return a 400 Bad request. But using this one works

>   val client: Service[Request, Response] = Http.newService("localhost:8080")
>   val request = RequestBuilder()
>     .url(new URL("http://localhost:8080/hello_server"))
>     .buildGet()

Any idea why?. 

The funny thing is, that the first code against another finagle Http server or Vertx server works fine, it´s failing only against Grizzly.

I realize that the problem was that with Grizzly server I need to add the whole uri again in the request

     val request = http.Request(http.Method.Get, "http://localhost:8080/hello_server")

Is this a bug?

Regards

**Comment by bryce-anderson** [comment]
Just a wild guess, but try adding a host header.

**Comment by politrons** [comment]
A header where?

**Comment by politrons** [comment]
Yeah adding the header or directly host it works. Still wondering why with Vertx or Finagle servers are not needed

**Comment by mosesn** [comment]
@politrons my guess would be that only Grizzly validates that the request has a Host header by default.  I'm going to close this issue, since I think your question has been answered, but please feel free to open a new one or continue this thread if you have more questions.

**Comment by lelence** [comment]
I have the same problem, when I using code like 
`val client: Service[Request, Response] = Http.newService("localhost:8080")
val request = http.Request(http.Method.Get, "/hello_server")`
It's return 400 Bad Request

when I using code like 
`val client: Service[Request, Response] = Http.newService("localhost:8080")
val request = RequestBuilder()
.url(new URL("http://localhost:8080/hello_server"))
.buildGet()`

It will be successed.

I found something like
`val withHost = config.headers.updated(Fields.Host, Seq(hostValue))`  at line 153 on source file 'RequestBuilder'

so I think, it will be working , add header info like 
`val client: Service[Request, Response] = Http.newService("localhost:8080")

request.headerMap.add("Host", "localhost:8080") // add header

val request = http.Request(http.Method.Get, "/hello_server")`

so it's working, return status 200, 


mybe there is a bug!!!
