### ISSUE TITLE
Implicit error in finagle-http2

### ISSUE THREAD

**Issue by politrons** [twitter/finagle#676]
I´m trying to use finagle-http2 and with this client

> Http.client
>       .configured(Http.Http2)
>       .newService(s"localhost:$port")

I´m receiving this compilation error

> Error:(20, 18) not enough arguments for method configured: (implicit evidence$2: com.twitter.finagle.Stack.Param[com.twitter.finagle.Stack.Params])com.twitter.finagle.Http.Client.
> Unspecified value parameter evidence$2.
>       .configured(Http.Http2)

**Comment by mosesn** [comment]
@politrons Http.Http2 is actually a set of params, so you need to use Http.client.configuredParams(Http.Http2) instead.
