### ISSUE TITLE
Unable to run finagle-example project

### ISSUE THREAD

**Issue by AlexITC** [twitter/finagle#683]
finagle-example is throwing compilation errors

### Expected behavior

The project should be able to compile.

### Actual behavior

While executing the `sbt "project finagle-example" "run"` command, I'm getting the following errors:
```
...
[info] Done compiling.
[info] Packaging /home/dell/projects/github/finagle/finagle-memcached/target/scala-2.12/finagle-memcached_2.12-18.3.0.jar ...
[info] Done packaging.
[info] Compiling 21 Scala sources and 11 Java sources to /home/dell/projects/github/finagle/finagle-example/target/scala-2.12/classes ...
[error] /home/dell/projects/github/finagle/finagle-example/src/main/scala/com/twitter/finagle/example/stress/Stress.scala:3:19: object common is not a member of package com.google
[error] import com.google.common.util.concurrent.AtomicLongMap
[error]                   ^
[error] /home/dell/projects/github/finagle/finagle-example/src/main/scala/com/twitter/finagle/example/stress/Stress.scala:25:21: not found: value AtomicLongMap
[error]     val responses = AtomicLongMap.create[Status]()
[error]                     ^
[error] two errors found
[error] (finagle-example/compile:compileIncremental) Compilation failed
```

### Steps to reproduce the behavior
Run this command from the `master` branch:  `sbt "project finagle-example" "run"`.

**Comment by cacoco** [comment]
@AlexITC thanks for the issue. Looks like a dependency issue has been introduced. We'll take a look.

**Comment by yaroot** [comment]
`finagle-example` does not depend on guava in sbt build, but in pants BUILD it does. Looks like been broken since the removal of guava from serversets.

**Comment by smlance** [comment]
A patch is in progress.

**Comment by smlance** [comment]
This should be fixed with https://github.com/twitter/finagle/commit/6f8adbfe90a6573de98b0653223d4fd0b6c4a4ed.
