### ISSUE TITLE
Retry (a limited number of times) on connection reset

### ISSUE THREAD

**Issue by kaqqao** [twitter/finagle#689]
I unfortunately have a rather old Finagle version (6.35.0) which, at the moment, can not be changed.

I'm trying to set it up as an HTTP client, for a service that has 2 nodes. When a node resets the connection, I want Finagle to retry up to 3 times alternating the nodes.

To make matters infinitely more confusing, I'm doing this in java and pretty much all Finagle docs and examples are in Scala. 

Here's what I have so far:
```java
RetryPolicy<Tuple2<Request, Try<Response>>> retryPolicy = new SimpleRetryPolicy<Tuple2<Request, Try<Response>>>(3) {
    @Override
    public boolean shouldRetry(Tuple2<Request, Try<Response>> reqRes) {
        return reqRes._2.isThrow() && reqRes._2.throwable() instanceof ChannelClosedException;
        }

    public Duration backoffAt(int i) {
        return Duration.fromSeconds(i);
    }
};

Service<Request, Response> client = Http.client()
        .filtered(new RetryFilter<Request, Response>(retryPolicy, HighResTimer.Default(), RetryFilter.apply$default$2()))
        .newService("localhost:48409"); //only 1 node for testing

Request request = ...; //build the request
Response res = Await.result(client.apply(request));
```
For some reason, this keeps retrying endlessly, not 3 times like I expected (due to `new SimpleRetryPolicy<>(3)`) and the response future never completes.

Am I even on the right track with this? Could it be related to #167 ?

DISCLAIMER: This is a [cross-post from StackOverflow](https://stackoverflow.com/questions/50043849/how-to-setup-finagle-to-retry-a-limited-number-of-times-when-a-connection-is-res). The reason is that Finagle users on SO are few and far in between (only ~140 tagged questions in total), so my chances of getting an answer are slim without contacting someone here more directly.

**Comment by kevinoliver** [comment]
Hi @kaqqao,

I think you need to change how you implement `backoffAt`. Check out it's [scaladocs](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/service/RetryPolicy.scala#L144-L149) for an example of how to break after a certain number of attempts.

**Comment by kaqqao** [comment]
Hey @kevinoliver ,

You're indeed right! Thanks a bunch for the pointer!
I'm now missing the point of the `SimpleRetryPolicy ` constructor argument, but that's less important.

**Comment by kevinoliver** [comment]
glad that worked out!

> I'm now missing the point of the SimpleRetryPolicy constructor argument, but that's less important.

it allows the class to be immutable. 

in practice, you should always use the no-args constructor, and the 1-arg one should be private to the class.
