### ISSUE TITLE
Duplicated requests based on number of hosts

### ISSUE THREAD

**Issue by samschlegel** [twitter/finagle#697]
We are seeing some strange behaviour where our backends are seeing duplicated requests and proportional to the number of hosts we set when building the client.

### Expected behavior

For `M` hosts, and `N` requests, we would expect to see `N` requests from the backend side, and `1` resolve of the future returned for each call. 

### Actual behavior

For `M` hosts, and `N` requests, we set `M*N` requests from the backend side, and `M` resolves of the future returned for each call. 

### Steps to reproduce the behavior

Using Finagle and Scrooge 18.5.0, we create a Thrift client with M hosts with stats enabled (e.g. `Thrift.client.withStatsReceiver(...).build("host1:4444,host2:4444...,hostM:4444")`
After making N requests, which we determine with the `finagle.requests` stat, we can see that the count of time `finagle.retries.requeues_per_request` was updated was `M*N`. No retry stats were incremented, so we know all requests were completed successfully. We also have a counter that's updated in a `map` on the result of the client call, and that also shows `M*N` requests.

We are using [pinterest/elixir-thrift](https://github.com/pinterest/elixir-thrift) as the backend, but I can't imagine how that would be a problem here.

**Comment by mosesn** [comment]
@samschlegel this is bizarre.  It looks like we're requeueing your request every time.  Your success and failure metrics reflect that everything is succeeding?  Can you try removing the RequeueFilter from the stack and see if you still have this issue?

**Comment by kevinoliver** [comment]
@samschlegel any more info here? We've never seen this behavior.

**Comment by baybatu** [comment]
Hi, I've encountered with this behaviour with 2 REST apis running on localhost. (apigwservice -> customerservice)

I added ConsoleTracer to Http client and logs are something following:

```
1207 18:09:16.264 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] Rpc(POST)
1207 18:09:16.266 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] BinaryAnnotation(http.uri,/customers)
1207 18:09:16.266 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] ServiceName(customerservice)
1207 18:09:16.266 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] BinaryAnnotation(clnt/finagle.version,18.11.0)
1207 18:09:16.266 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] ClientSend
1207 18:09:16.266 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] Rpc(POST) # duplication starting
1207 18:09:16.267 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] BinaryAnnotation(http.uri,/customers)
1207 18:09:16.267 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] ServiceName(customerservice)
1207 18:09:16.267 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] BinaryAnnotation(clnt/finagle.version,18.11.0)
1207 18:09:16.267 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] ClientSend
1207 18:09:16.350 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] WireSend
1207 18:09:16.350 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] WireSend
1207 18:09:16.353 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] ServerAddr(localhost/127.0.0.1:9002)
1207 18:09:16.353 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] ServerAddr(localhost/127.0.0.1:9002)
1207 18:09:16.354 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] ClientAddr(/127.0.0.1:60432)
1207 18:09:16.354 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] ClientAddr(/127.0.0.1:60431)
1207 18:09:17.500 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] WireRecv
1207 18:09:17.500 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] WireRecv
1207 18:09:17.504 0ed23f75c00b1f09.950bf153dfbe4c4d<:0ed23f75c00b1f09] ClientRecv
1207 18:09:17.504 0ed23f75c00b1f09.ff5814a2e8f40305<:0ed23f75c00b1f09] ClientRecv
```

Sometimes, `apigwservice` duplicates requests that sent to `customerservice`.

**Comment by baybatu** [comment]
It seems the duplication requests' cause is Http client's idempotency settings(1.percent)

**Comment by kevinoliver** [comment]
Thanks for following up @baybatu that sounds like expected behavior.
