### ISSUE TITLE
Update the finagle com.fasterxml.jackson.core:jackson-core dependency from 2.8.x to 2.9.x

### ISSUE THREAD

**Issue by rajcspsg** [twitter/finagle#698]
Looks like finagle 18.5.0 depends on com.fasterxml.jackson-modules 2.8.4 version. Shall we update using these dependencies to 2.9.5?

### Expected behavior com.fasterxml.jackson-modules  version to 2.9.5 without changing any technical functionalities as part of this issue..

Please update 

### Actual behavior

The problem is because the our classpath has different dependency which transitively brings different version of paranamer and updating it is causing classNotFoundException.

### Steps to reproduce the behavior

do `sbt dependencyTree` in root folder.

**Comment by cacoco** [comment]
Finagle is developed internally in a monorepo and thus changing a core dependency like Jackson requires updating the entire internal repository so we tend to do these updates ourselves. 

To make this change, we need to update our internal monorepo all at the same time which are not currently ready to do. But please stay tuned.

**Comment by cacoco** [comment]
If you're OK with it, I'm going to close this issue for now. As we chatted, I would try to add some exclusion rules. Please feel free to re-open or open a new issue if you have problems.
