### ISSUE TITLE
Register Service With ZK in maven

### ISSUE THREAD

**Issue by zhangandyhui** [twitter/finagle#702]
LoggingFilter accessLog = new LoggingFilter();
        NullToNotFound nullFilter = new NullToNotFound();
        HandleErrors errorsFilter = new HandleErrors();
        Service<Request, Response> service = accessLog
                .andThen(nullFilter)
                .andThen(errorsFilter)
                .andThen(Handlers.handler(demoService));

        listeningServer=Http.server().withLabel("demoService-server").serveAndAnnounce("zk!127.0.0.1:2181!/service/demoService/!0",service);
        Await.ready(listeningServer);

I've registered my service with zk,  but i cannot use it in my client;

 @PostConstruct
    public DemoService.ServiceIface demoService(){
        Service<Request, Response> service = Http.client().withSessionPool().minSize(1).newService(serverAddr, "DemoService-client");
        return xxxxxxx;
    }
 I just cannot understand how i can get the DemoService.ServiceIface?????   
can u provider some java demos in finagle source???????

**Comment by smlance** [comment]
Hi @zhangandyhui. You might find it helpful to take a look at the [Thrift Client and Server examples](https://github.com/twitter/finagle/tree/develop/finagle-example/src/main/java/com/twitter/finagle/example/java/thrift) in finagle-example.

**Comment by kevinoliver** [comment]
@zhangandyhui hopefully the examples helped.
