### ISSUE TITLE
Make SPNEGO requests through Finagle client

### ISSUE THREAD

**Issue by Alterrien** [twitter/finagle#708]
Hi,

I'm currently trying to issue HTTP requests authenticated to an endpoint secured by Kerberos and SPNEGO. I've seen a fair share of servers implementing this protocol using Finatra/Finagle, but none for requests. 
Is this use case supported, and if so, how can I do it ?
Cheers !

**Comment by dschobel** [comment]
There's an example of configuring client-side SPNEGO in [finagle's test suite
](https://github.com/twitter/finagle/blob/develop/finagle-http/src/test/scala/com/twitter/finagle/http/SpnegoAuthenticatorTest.scala#L165)

Please let me know if that doesn't answer your question.

**Comment by Alterrien** [comment]
Hi, I managed to get the code to sort of work (minus kerberos setup on my machine, but that's not Finagle scope). It was my first time being exposed to SPNEGO, so the documentation, specifically what was to fill in as loginContext for the JAASClientSource, was not enough to allow me to use it out of the box. I guess that's more related to knowledge of the SPNEGO protocol and JAAS.

Anyway, thanks !

**Comment by dschobel** [comment]
@Alterrien agreed it could use more / better docs. I think we have an internal ticket for more docs already but if not I'll file one. Thanks for the feedback.
