### ISSUE TITLE
finagle-mysql client produces "Elevated metric creation requests" lint issue

### ISSUE THREAD

**Issue by komsit37** [twitter/finagle#712]
Using transaction in finagle-mysql would produce "Elevated metric creation requests" lint error in the following rule in `com.twitter.finagle.stats.MetricsStatsReceiver`. This seems to affect performance?
```scala
  GlobalRules.get.add(
    Rule(
      Category.Performance,
      "Elevated metric creation requests",
      "For best performance, metrics should be created and stored in member variables " +
        "and not requested via `StatsReceiver.{counter,stat,addGauge}` at runtime. " +
        "Large numbers are an indication that these metrics are being requested " +
        "frequently at runtime."
    ) //...
  )
```

### Expected behavior
no lint issue

### Actual behavior
calling `transaction` more than 30,000 times would produce lint issue

### Steps to reproduce the behavior
running below test
```scala
class FinagleMySqlTransactionMetricsLintTest extends FunSuite {
  //to enable metrics creation log
  com.twitter.logging.Logger.get(classOf[com.twitter.finagle.stats.MetricsStatsReceiver]).setLevel(com.twitter.logging.Level.TRACE)
  private val log: Logger = LogManager.getLogManager.getLogger("")
  log.getHandlers.foreach { h: Handler =>
    h.setLevel(Level.ALL)
  }

  test("insert persons with transaction") {
    val client = Mysql.client
      .withCredentials("root", null)
      .withDatabase("some_database")
      .newRichClient("localhost:3306")

    Await.result(client.modify("create table if not exists Person(name varchar(36) not null)"))
    Await.result(client.modify("insert into Person values ('a')"))
    Await.result(client.read("select * from Person"))
    Await.result(Future.collect((1 to 50000).map(_ => client.transaction({ cli => cli.read("select * from Person") }))))

    val issues = GlobalRules.get.iterable.flatMap({ rule =>
      rule.apply()
    })
    println("issue: \n" + issues.mkString("\n"))
    Await.result(client.modify("drop table Person"))
  }
}
```
would log
```
issue: 
Issue(StatReceiver.counter() has been called 100041 times)
Issue(StatReceiver.stat() has been called 150018 times)
```

**Comment by komsit37** [comment]
seems calling `transact` would create new client repeatedly, which requests new `CursorStats` metrics every time
https://github.com/twitter/finagle/blob/develop/finagle-mysql/src/main/scala/com/twitter/finagle/mysql/Client.scala#L319

**Comment by roanta** [comment]
Hi @komsit37! Thanks for the detailed report and repro.

It seems to me that reasonable solution would be to move the creation of those stats inside the `cursor` method (specifically, as part of the `CursoredStatement` object). Would you be interested in providing a patch for this?

**Comment by smlance** [comment]
Thanks @komsit37. We're working on a fix for this.

**Comment by smlance** [comment]
This should be resolved as of https://github.com/twitter/finagle/commit/c404078f4d2ae1dbbbe5799a2aa554fd216b09dd.
