### ISSUE TITLE
finagle-mysql: value type not supported for SUM() aggregated column

### ISSUE THREAD

**Issue by moleike** [twitter/finagle#713]
Client throws UnsupportedTypeException when decoding the result of a `SUM()` aggregation.

### Expected behavior

An integer value per row with the aggregation.

### Actual behavior

Get an exception telling me that the returned value is a `RawValue`:

```
com.twitter.finagle.mysql.UnsupportedTypeException: For column name 'total', value type not supported: com.twitter.finagle.mysql.RawValue
```

### Steps to reproduce the behavior
Contrived example:

```scala
val query =
      """SELECT SUM(amount) AS total FROM claim
          WHERE `user-id` = ?
          GROUP BY `user-id`"""

client
  .prepare(query)
  .select(123)(_.longOrZero("total"))
  .map(_.headOption.getOrElse(0L))
```

If there anything else I can provide please let me know, thanks!

**Comment by kevinoliver** [comment]
Looks like MySQL is returning the aggregate as a new decimal. It should work if you switch to using `Row.bigDecimalOrNull` from `longOrZero`.

**Comment by moleike** [comment]
indeed, thanks!
