### ISSUE TITLE
Missing dtab information in NoBrokersAvailableException

### ISSUE THREAD

**Issue by coduinix** [twitter/finagle#716]
The message of the `NoBrokersAvailableException` always shows an empty `Dtab.base` and `Dtab.local` even if they are set.

### Expected behavior

The message of the `NoBrokersAvailableException` should display the actual `Dtab.base` and `Dtab.local` being used.

### Actual behavior

Exception message always shows both the Dtab.base and Dtab.local as empty. This causes confusion specifically in cases where the Dtab is set in other parts of the code. Then it's unclear whether the dtab was actually picked up.

### Steps to reproduce the behavior

Run the example code below:
```scala
object FinagleTest extends App {
  Dtab.base = Dtab.read("/s => /$/inet/localhost/8000")
  Dtab.local = Dtab.read("/s => /$/inet/non-existing-host/8000")

  val service = client.newService("/s/aweseomservice")

  val response = Await.result(service.apply(http.Request(Method.Get, "/hello")))
  println(response.getContentString())
}
```

It results in this exception: `Exception in thread "main" com.twitter.finagle.NoBrokersAvailableException: No hosts are available for /s/aweseomservice, Dtab.base=[], Dtab.local=[]. Remote Info: Not Available`

While I was expecting the Dtab.base and Dtab.local parts to be filled with the actual dtab information.

**Comment by kevinoliver** [comment]
Nice find.

Looks to me like [LoadBalancerFactory](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/loadbalancer/LoadBalancerFactory.scala#L257) is not using the right constructor for `NoBrokersAvailableException`. 

That said, even if we capture the right value at construction time, those values could change after that. 

My inclination is to evolve `NoBrokersAvailableException.getMessage` to allow those values to be read from `Dtab.base` and `Dtab.local` unless they have been set.

Are you interested in working on a PR to fix this?

**Comment by kevinoliver** [comment]
It'd be a bigger API change. A compromise might be to add a new constructor to `NoBrokersAvailableException` where `baseDtab` and `localDtab` are Function1's.

```
class NoBrokersAvailableExeption(
  val name: String, 
  baseDtabFn: () => Dtab,
  localDtabFn: () => Dtab
) extends ...

  // backwards compatibility constructor
  def this(name: String, baseDtab: Dtab, localDtab: Dtab) =
    this(name, () => baseDtab, () => localDtab)

  def this(name: String) =
    this(name, () => Dtab.base, () => Dtab.local)

  def baseDtab: Dtab = baseDtabFn()
  def localDtab: Dtab = localDtabFn()

  ...

**Comment by coduinix** [comment]
The suggested compromise makes sense I think. I'll prepare a PR
