### ISSUE TITLE
Suspected balancer leak in finagle

### ISSUE THREAD

**Issue by dadjeibaah** [twitter/finagle#735]
When an empty address set is used in a client's LoadBalancer, the Balancer instance for that instance is set to "Closed", however, when a new Balancer is added due to the Address set being updated, the previous Balancer's instance is set to "Closed" and is never unregistered from the BalancerRegistry. 

### Expected behavior
"Closed" balancers should be evicted from the `BalancerRegistery` after some configured time or should be excluded from being added to the `BalancerRegistery`if the there are no addresses to load balancer over.

### Actual behavior

When an empty address set is used in a client's LoadBalancer, the Balancer instance for that instance is set to "Closed", however, when a new Balancer is added due to the Address set being updated, the previous Balancer's instance is set to "Closed" and is never unregistered from the BalancerRegistry.

### Steps to reproduce the behavior

I've created a small repro case that will show this behavior at https://github.com/dadjeibaah/finagle-balancer-leak

**Comment by adleong** [comment]
I suspect the leak might be here: https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/loadbalancer/TrafficDistributor.scala#L285

It looks like when a new Distributor replaces the previous one, the previous one isn't closed.

**Comment by kevinoliver** [comment]
Thanks for the report and great repro @dadjeibaah 

@adleong I think the issue is that we are managing state (`newBalancer`) in 2 places. A few lines above where you pointed and also in `partition`. I think we want it to only be handled in `partition`. 

I'll take a crack a fix.

**Comment by dadjeibaah** [comment]
@kevinoliver, I made a first attempt at fixing the bug. Not sure if it's the totally right way to do it but from my understanding, it looks like the `partition` method needs to handle situations where the `endpoints` activity is updated with an empty set. The code I have on my branch moves the `newBalancer` method into `partition` and creates a `CachedBalancer` with weight 0 (Not sure if that even makes sense). I will play around with it more to see if I can come up with a better solution.

Diff can be found here...https://github.com/twitter/finagle/compare/develop...dadjeibaah:develop

**Comment by kevinoliver** [comment]
@dadjeibaah yeah its more complicated than i'd thought and hoped...

**Comment by bryce-anderson** [comment]
@dadjeibaah, your patch looks pretty solid to me. Do you want to put it up as a PR?

**Comment by dadjeibaah** [comment]
@bryce-anderson I can add a PR for review. I just need to work on it a little more to fix some tests that are failing.

**Comment by dadjeibaah** [comment]
@bryce-anderson, I added a PR as a potential fix for this issue, just as a heads up.

**Comment by bryce-anderson** [comment]
Thanks @dadjeibaah! I'll try to take a look this afternoon.

**Comment by bryce-anderson** [comment]
This should make it out in the December release, likely the first part of dec.

**Comment by kevinoliver** [comment]
fixed in 21664df3700257de3165511c2625d232c399322b
