### ISSUE TITLE
Upgrade netty to 4.1.29+ to fix high epoll memory usage

### ISSUE THREAD

**Issue by dziemba** [twitter/finagle#738]
Since finagle has enabled native epoll in netty, non-heap memory usage has gone up significantly in our apps.

This has been fixed in netty 4.1.29 
My local tests with epoll enabled and netty bumped to 4.1.29 confirmed this.

Original issue: https://github.com/netty/netty/issues/8159
Fix: https://github.com/netty/netty/pull/8160

### Expected behavior

Memory usage stays the same.

### Actual behavior

Memory usage is significantly higher (up to 512MB in extreme cases).

### Steps to reproduce the behavior

Run an app with epoll enabled (default in 18.9.1) and then again with it disabled 
(`-Dcom.twitter.finagle.netty4.useNativeEpoll=false`). Watch memory usage (RSS of JVM).

**Comment by dziemba** [comment]
If you haven't planned this already and don't have capacity for it, I'm also happy to try this myself and create a PR. We would love to see this in the next finagle release if possible.

**Comment by dziemba** [comment]
Awesome! that works for us too

**Comment by kevinoliver** [comment]
This got included in the upgrade to 4.1.31 in 8e0f4b868c34259350fb0def2e7fee5d3d77fece
