### ISSUE TITLE
How to run two instance of finagle in same host with different ports?

### ISSUE THREAD

**Issue by pra527vin** [twitter/finagle#750]
One line summary of the issue here.

### Expected behavior

As concisely as possible, describe the expected behavior.

### Actual behavior

As concisely as possible, describe the observed behavior.

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

**Comment by yufangong** [comment]
Hi @pra527vin , can you provide more info here about the issues you run into? From the [QuickStart](http://twitter.github.io/finagle/guide/Quickstart.html), I think you could bind the services to different ports.

**Comment by pra527vin** [comment]
Http.server
      .withAdmissionControl
      .concurrencyLimit(maxConcurrentRequests = maxRequests, maxWaiters = maxRequestsQueue)
      .withMaxHeaderSize(new StorageUnit(maxHeaderSize))
      .withMaxRequestSize(new StorageUnit(maxRequestSize))
      .withRequestTimeout(30.seconds)
      .configured(Stats(statsReceiver))
      .serve(s"${ServerEnvironment.SERVER_ADDRESS}:${ServerEnvironment.PORT()}",
        new Cors.HttpFilter(originPolicy).andThen(kiranaAPI))
/**
      * Make Exit happening here.
      */
    onExit {
      server.close()
    }

I have configured server like this 
for two instances with different ports 
After first services is started  then second service with different port is gives AddressBindException 
I have cretaed different jar for two server insctances

**Comment by kevinoliver** [comment]
Unable to reproduce this.
