### ISSUE TITLE
Retry Strategy does not work

### ISSUE THREAD

**Issue by politrons** [twitter/finagle#759]
Retry policy not working

### Expected behavior

After configure my RetryPolicy Strategy I was expecting see some retries. 

### Actual behavior

After the first timeout the request fails

### Steps to reproduce the behavior

Shutdown a mock service and invoke with this config and code.

I create my service with this two filters

```
        Map<String, String> map = new HashMap<>();
        map.put("environment.permissions.timeout","1000");
        map.put("environment.permissions.retries","3");
        map.put("environment.permissions.backoff","200");

  /**
    * Timeout filter to override the default timeout of finagle client
    *
    * @return Finagle TimeoutFilter
    */
  private def withTimeoutFilter: () => TimeoutFilter[Request, Response] =
    () => new TimeoutFilter[Request, Response](
      timeout = timeout.millisecond,
      timer = DefaultTimer.twitter)

  /**
    * Retry policy to override the default finagle retry policy with user properties retry number and backoff
    *
    * @return Finagle RetryFilter
    */
  private def withRetryPolicyFilter: () => RetryFilter[Request, Response] =
    () => RetryFilter(Backoff.const(backoff.millisecond)
      .take(retries))(shouldRetry)
```

response is 

com.twitter.finagle.IndividualRequestTimeoutException: exceeded 1.seconds to unspecified while waiting for a response for an individual request, excluding retries. Remote Info: Not Available
Response:The request failed cause a timeout connection.

**Comment by kevinoliver** [comment]
Took a while for someone to look at this. I don't really understand the issue you are seeing. Maybe you can rephrase the instructions on how to reproduce the issue?
