### ISSUE TITLE
Finagle-Redis: Add RPOPLPUSH Command

### ISSUE THREAD

**Issue by martinffx** [twitter/finagle#762]
I want to use the RPOPLPUSH Command

### Expected behavior

The redis client should support RPOPLPUSH `client.rPopLPush(source, dest)`

### Actual behavior

Command not supported

**Comment by martinffx** [comment]
https://github.com/twitter/finagle/pull/763

**Comment by kevinoliver** [comment]
This got addressed in https://github.com/twitter/finagle/pull/767
