### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pengisgood** [twitter/finagle#772]
The [link](https://www.eckner.com/papers/ts_alg.pdf) in the code comments is dead.

Code block reference: https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/loadbalancer/PeakEwma.scala#L48

```scala
    // Calculate the exponential weighted moving average of our
    // round trip time. It isn't exactly an ewma, but rather a
    // "peak-ewma", since `cost` is hyper-sensitive to latency peaks.
    // Note, because the frequency of observations represents an
    // unevenly spaced time-series[1], we consider the time between
    // observations when calculating our weight.
    // [1] https://www.eckner.com/papers/ts_alg.pdf
    private[this] def observe(rtt: Double): Unit = {
      val t = nanoTime()
      val td = math.max(t - stamp, 0)
      val w = math.exp(-td / Tau)
      if (rtt > cost) cost = rtt
      else cost = cost * w + rtt * (1.0 - w)
      stamp = t
    }
```

**Comment by crispywalrus** [comment]
it looks to me like the link to that paper has changed to http://www.eckner.com/papers/unevenly_spaced_time_series_analysis.pdf

**Comment by kevinoliver** [comment]
thanks for noticing. and for the updated link. 

would love a PR for this if you can help.

**Comment by pengisgood** [comment]
Thanks for the PR.

Shall we save a copy of the paper in this repo just in case?
What do you think?

**Comment by crispywalrus** [comment]
My take is that there's advantage to keeping the link as a link. I (for instance) followed the old broken link and was able with a minimum of fuss to find the new link as well as newer papers on the same subject. Based on that, and the fact that the paper is never really going to go away makes me say leave it a link.

**Comment by yufangong** [comment]
Thanks for the report! this is fixed by @crispywalrus at https://github.com/twitter/finagle/commit/96cb072f1678b45811e3e5d3800b44cc3ea4e441
