### ISSUE TITLE
CPU metrics (system and process usage) are missed

### ISSUE THREAD

**Issue by dkulichkin** [twitter/finagle#777]
I'm not able to see cpu-related metrics at
https://twitter.github.io/finagle/guide/Metrics.html

Hence need to tailor my own custom meters leveraging `com.sun.management.OperatingSystemMXBean` and `java.lang.management.ManagementFactory` classes, but it would be more convenient to have it in the statsregistry by default

**Comment by ryanoneill** [comment]
Hi @dkulichkin!

Can you tell us specifically what metrics are missing, and also which JVM version you're using and what OS you're running on? Thanks.

**Comment by dkulichkin** [comment]
@ryanoneill I'd like to be able to monitor cpu usage per process and overall for the whole host as I specified in the issue's title. JVM and OS in this case do not really mater since the subject metrics are not listed among:
https://twitter.github.io/finagle/guide/Metrics.html

**Comment by ryanoneill** [comment]
Ah, ok. Now I understand what you meant.

Within Finagle, we only export the [number of cpus as a gauge ('jvm/num_cpus')](https://docbird.twitter.biz/finagle/Metrics.html#jvm) by default. One reason we don't do more here is that measurement of this is highly contextual. The vast majority of Twitter's architecture runs on Mesos currently, and so measuring the number of physical cpus (as we do for 'num_cpus') is largely incorrect, as what really matters is what your service has been allocated by the scheduler (in our case, Aurora).

Therefore at Twitter, folks use stats in this area provided by the container itself, which are very similar to the ones mentioned [here](http://mesos.apache.org/documentation/latest/isolators/cgroups-cpu/).

**Comment by dkulichkin** [comment]
Clear, for those still willing to add these metrics to finagle's statsReceiver implementation (PrometheusStatsReceiver in my case) - this is how I've done it:
```
import com.sun.management.OperatingSystemMXBean
import java.lang.management.ManagementFactory

val operatingSystemBean: OperatingSystemMXBean = ManagementFactory .getOperatingSystemMXBean.asInstanceOf[OperatingSystemMXBean]
val stats = statsReceiver.scope("cpu")
stats.addGauge("system_cpu_usage")(operatingSystemBean.getSystemCpuLoad.toFloat)
stats.addGauge("process_cpu_load")(operatingSystemBean.getProcessCpuLoad.toFloat)
```

**Comment by mosesn** [comment]
Thanks @dkulichkin!  I'm going to close this out since we're not planning on implementing this for now.
