### ISSUE TITLE
MaxRequestSize/MaxResponseSize and fixedLengthStreamedAfter unexpected behavior

### ISSUE THREAD

**Issue by zaharidichev** [twitter/finagle#780]
`http.param.MaxRequestSize` and `http.param.MaxResponseSize` have ambiguous semantics wheh combined with `fixedLengthStreamedAfter`

### Expected behavior
I would expect that if `fixedLengthStreamedAfter` is set say 5 kilobytes and `MaxRequestSize` is set at 4 kilobytes, a message with `Content-Length` set to 6 kilobytes is processed as a streaming message without a problem

### Actual behavior
What happens instead is that the message is dropped as it exceeds `MaxRequestSize`. To me (and I might be totally off here), this does not sounds correct. What I expect to happen is for fixed size message to always be streamed after a certain amound of length, despite the fact that there is limit on the `MaxRequestSize`. How fo these two settings relate in more detail? Isn't the purpose of `fixedLengthStreamedAfter` to enable the processing of arbitrary long messages without imposing a hard limit. Moreover, it seems at the moment `http.param.MaxRequestSize` and `http.param.MaxResponseSize` are capped at 2GB. This effectivelly means that there is no way to process a message that has `Content-Length`  set and is larger than 2GB. Is it possible that the cap from these settings is removed. And if so, is that a good idea at all?  Thanks for the clarification in advance.

Also, another question I have is how do the `MaxHeaderSize` and `MaxInitialLineSize` params relate to `fixedLengthStreamedAfter`? Are these necessary when the message is streamed? And if so, do they become reduntant when the message is larger than `fixedLengthStreamedAfter`?

**Comment by luciferous** [comment]
Hi @zaharidichev, firstly, I agree that this is somewhat confusing. I think the API gives many choices to the user, perhaps there is a better way to structure them. I found some docs for these params at https://github.com/twitter/finagle/blob/develop/finagle-http/src/main/scala/com/twitter/finagle/Http.scala#L242. In particular,

> [`fixedLengthStreamedAfter`] effectively turns on streaming (think `withStreaming(true)`). The `fixedLengthStreamedAfter`, however, disables streaming for sufficiently small messages of known fixed length.

There is some backstory of the feature request in #538 and more discussion around semantics and naming in #740. I hope this answers your question about how the params relate. (Btw, we are open to suggestions to improve the docs or the names of these.)

> Moreover, it seems at the moment http.param.MaxRequestSize and http.param.MaxResponseSize are capped at 2GB. This effectivelly means that there is no way to process a message that has Content-Length set and is larger than 2GB. Is it possible that the cap from these settings is removed. And if so, is that a good idea at all?

I would suggest that it's not a good idea. 2GB means that your server will allocate up to 2GB at a time to serve a request. Much better if it processes 2GB as a stream.

> Also, another question I have is how do the MaxHeaderSize and MaxInitialLineSize params relate to fixedLengthStreamedAfter? Are these necessary when the message is streamed? And if so, do they become reduntant when the message is larger than fixedLengthStreamedAfter?

They are independent of streaming. `MaxHeaderSize` and `MaxInitialLineSize` apply constraints to the part of the HTTP request before the content body. Streaming is always a configuration of the content body. Let's have a look at an HTTP request example:

```
GET /this/is/the/song/that/never/ends/yes/it/goes/on/and/on/my/friend HTTP/1.1
Host: example.com
X-Example-Header: some people started singing it not knowing what it was and they continue singing it forever just because
Content-Length: 5

hello
```

In our example, the content body is smaller than the initial line (starting with `GET`) and a custom HTTP header (`X-Example-Header`). So, while content bodies can be arbitrarily large, we see that URL paths and HTTP headers can be large too! At some point, they become non-compliant with some RFC. But servers may set more conservative limits, and so that's why we have `MaxHeaderSize` and `MaxInitialLineSize`.

**Comment by edio** [comment]
@luciferous 
> I would suggest that it's not a good idea. 2GB means that your server will allocate up to 2GB at a time to serve a request. Much better if it processes 2GB as a stream.

Having 2GiB cap on `http.param.MaxRequestSize` value means, that HTTP requests without `Transfer-Encoding: chunked` and body larger than 2 GiB can not be processed by finagle applications. 
I'd like to highlight, that `http.param.MaxRequestSize` doesn't seem to be optional, if it is not set explicitly during service construction, it falls back to its default value of `5.megabytes` (unless I'm missing something) https://github.com/twitter/finagle/blob/develop/finagle-base-http/src/main/scala/com/twitter/finagle/http/param/params.scala#L46

**Comment by adleong** [comment]
If I understand the interaction between these parameters correctly, Finagle should only need to allocate at most `fixedLengthStreamedAfter`, even for non-chunked messages with very large content-lengths, as these will be streamed.  Is that correct?

**Comment by zaharidichev** [comment]
@edio I also see this as a problem. The purpose of `fixedLengthStreamedAfter` is that if you have a request that is more than a certain threshold and has `Content-Length` that reflects that size, it will be streamed. It will be streamed, and this is what happens indeed. However I cannot really understand the logic behind limiting this with `MaxRequestSize`. If I understand correctly, the semantics should be that if fixedLengthStreamedAfter, `MaxRequestSize` should not be throwing away a request that would be streamed anyway. Correct me if I am wrong. 

> I would suggest that it's not a good idea. 2GB means that your server will allocate up to 2GB at a time to serve a request. Much better if it processes 2GB as a stream.

@luciferous I would not think this is the case, if the request is streamed... 

@adleong My understanding is the same as yours and I belive its correct.

**Comment by luciferous** [comment]
@edio 

> Having 2GiB cap on http.param.MaxRequestSize value means, that HTTP requests without Transfer-Encoding: chunked and body larger than 2 GiB can not be processed by finagle applications.

If this is true, then it is a bug.

**Comment by luciferous** [comment]
@zaharidichev 
>> I would suggest that it's not a good idea. 2GB means that your server will allocate up to 2GB at a time to serve a request. Much better if it processes 2GB as a stream.
> @luciferous I would not think this is the case, if the request is streamed...

Yes, sorry, if I was unclear. I meant that it's not a good idea to process such a large request without streaming.

**Comment by zaharidichev** [comment]
> If this is true, then it is a bug.


@luciferous will provide an example of this behaviour soon enough

**Comment by luciferous** [comment]
@zaharidichev 

Just did a Http.withStreaming(5.kilobytes).serve(":8000", echoStream) and curled it with a huge file and got 413. That's enough to convince me something is not quite right.

**Comment by edio** [comment]
I'll let myself to chime in here.

I believe, that  `maxRequestSize` is currently behaving correctly: it limits request size regardless of transport mechanism used. This is a useful feature which I, as a service developer, would like to have.

The only issue with it, is that it is required and at the same time is capped at 2GiB.

Hence solution is to either make it optional or to remove the 2GiB cap.

**Comment by luciferous** [comment]
Seems like a reasonable solution. Would you like to contribute a patch?

**Comment by zaharidichev** [comment]
I agree with @edio that we can just remove the 2GB cap. That will be a breaking change however as some users of the lib might rely on that. Should I submit a fix or @edio will do it ?

**Comment by edio** [comment]
@zaharidichev, I merely joined this thread because I wanted to support the case, didn't mean to hijack it.
I could do the patch, but I think it should be yours :)

**Comment by zaharidichev** [comment]
Thanks a bunch for chiming in @edio! If you have any more suggestions, feel free to share. But I think this change will place nicely with https://github.com/linkerd/linkerd/pull/2298
