### ISSUE TITLE
Upgrade caffeine library

### ISSUE THREAD

**Issue by dziemba** [twitter/finagle#812]
Finagle is currently using caffeine `2.3.4`, which is now roughly 3 years old. The latest version `2.8.0` which brings new features, performance improvements and bugfixes.

In some of our projects we would like to use new caffeine features. Since these projects also use finagle, we can't easily just override the version without risking incompatibilities.

Caffeine is also used in twitter/util (and probably other twitter projects), so I want to check with you first before opening PRs. I tested finagle and util locally and it compiles fine with the new caffeine version, no code changes needed.

**Comment by mosesn** [comment]
Yeah, we should probably do that on our side, thanks for reaching out.  I'll file a ticket internally and keep you posted.  Assuming there aren't any big surprises, we should be able to have it by the next release.

**Comment by mosesn** [comment]
@dziemba update on this: I have a patch up for review internally, so we're on track for the next release.

**Comment by dziemba** [comment]
Cool, thanks!

**Comment by mosesn** [comment]
Updated!  Commit here: https://github.com/twitter/finagle/commit/c335b29e7632ce7165e662136beaf377bfc4e24e

Thanks for filing the ticket!
