### ISSUE TITLE
com.twitter:maven-finagle-thrift-plugin jar is missing in twitter's maven repo

### ISSUE THREAD

**Issue by HenryCaiHaiying** [twitter/finagle#816]
Not sure whether the above jar is managed by this project, the jars is missing in the twitter's maven repo (only md5 file are left):

https://maven.twttr.com/com/twitter/maven-finagle-thrift-plugin/0.0.9/

maven-finagle-thrift-plugin-0.0.9.jar.md5
maven-finagle-thrift-plugin-0.0.9.jar.sha1
maven-finagle-thrift-plugin-0.0.9.pom
maven-finagle-thrift-plugin-0.0.9.pom.md5
maven-finagle-thrift-plugin-0.0.9.pom.sha1

**Comment by olix0r** [comment]
probably related to https://github.com/twitter/commons/issues/485

**Comment by mosesn** [comment]
@HenryCaiHaiying @olix0r the problem should have been fixed.  Please reopen if the problem continues.  In the mean time, I encourage you to migrate to a modern version of scrooge that's hosted by bintray and artifactory, which should be more reliable than maven.twttr.com.
