### ISSUE TITLE
 In my application it's java netty server work on client server mode. is it possible to accept tls and non tls request on server side?

### ISSUE THREAD

**Issue by sanjeevbis** [twitter/finagle#829]
One line summary of the issue here.

### Expected behavior

As concisely as possible, describe the expected behavior.

### Actual behavior

As concisely as possible, describe the observed behavior.

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

**Comment by bryce-anderson** [comment]
We don't surface netty as a first class API for creating clients or servers. For non-bug support checkout the resources linked [here](https://github.com/twitter/finagle#getting-involved).
