### ISSUE TITLE
Disable cache in Http client

### ISSUE THREAD

**Issue by politrons** [twitter/finagle#830]
Hi all,

We're suffering a weird behavior in our network using Finagle client with default configuration.

Once we establish a connection to some backends going through some proxies we detect that after some idle time, the connections are closed by Proxy, but Finagle has cached the connections, keeping opens, which provoke `IndividualRequestTimeoutException` when the client try to reuse those connections. I understand that since we use the client over Http 1.1 we are not able to keep the connections open, but Finagle it does by default.

I tried to disable the cache of connections, but without any success.

Here the code

```
  private def createServiceWithTLS: String => Service[Request, Response] =
    dest =>
      Http.client
        .configured(FailFastFactory.FailFast(enabled = failFast))
        .configured(createPoolConfig)
        .withSession.maxIdleTime(1 minutes)
        .withTransport.tls(TLSUtils._sslContext.get)
        .newService(dest, "my-service")

  private def createPoolConfig: DefaultPool.Param = {
    DefaultPool.Param(
      low = 0,
      high = 1,
      bufferSize = 0,
      idleTime = 60.milliseconds,
      maxWaiters = 1)
  }
```

Any idea how to disable the cache in the Http client.

**Comment by DieBauer** [comment]
I believe https://twitter.github.io/finagle/guide/Clients.html#pooling is describing your observations. Did you try to set the sessionpool ttl?

**Comment by politrons** [comment]
Actually is the only argument that I missing and looks like is the most important 😱. I will try again adding it! Thanks!

**Comment by mosesn** [comment]
@politrons since you didn't follow up here, I'm going to assume that solved your problem and close the ticket.  Thanks for your help @DieBauer!
