### ISSUE TITLE
Case sensitive heders

### ISSUE THREAD

**Issue by DanielCharczynski** [twitter/finagle#831]
According to specification header names should be case insensitive..

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

But when user adds "host" header finagle will add another "Host" header.
Two headers will be send with different values

Finagle at the moment is not compatible with headers defined in netty 4
netty uses lower case names

`io.netty.handler.codec.http.HttpHeaderNames`

finagle
`com.twitter.finagle.http.Fields`
  
conversion doesn't work correctly in because is case sensitive
`com.twitter.finagle.netty4.http.Bijections.finagle.headersToNetty`

### Expected behavior

One case insensitive header when set method is used

### Actual behavior

Headers are case sensitive
Names are no compatible with Netty 4

### Steps to reproduce the behavior

Add "host" header and send http Request

**Comment by yufangong** [comment]
Hi @DanielCharczynski , can you provide more information of reproducing the issue? 
Finagle headers should be case-insensitive, actually force them to the lower case [here](https://github.com/twitter/finagle/blob/7acd423f88312a2f9dd00d38a06ae7ef3e51faf7/finagle-base-http/src/main/scala/com/twitter/finagle/http/HeaderMap.scala#L109). If two "host"s are set, the second host should win.

**Comment by DanielCharczynski** [comment]
Code
```
val client = Http.client
val service = client.newService("inet!localhost:8888")

var requestBuilder = RequestBuilder().url("http://dummy.restapiexample.com/api/v1/employees")
requestBuilder = requestBuilder.setHeader("host", "myhost")
requestBuilder = requestBuilder.setHeader("hOst", "myhost2")

requestBuilder = requestBuilder.setHeader("testh", "test1")
requestBuilder = requestBuilder.setHeader("testh", "test2")
requestBuilder = requestBuilder.setHeader("testH", "test3")

val result = Await.result(service.apply(requestBuilder.buildGet()))
```

-------------------

request that has been sent

```
GET http://myhost/api/v1/employees HTTP/1.1
X-B3-SpanId: 023283cd77be2eba
Finagle-Ctx-com.twitter.finagle.Retries: 0
testh: test2
testH: test3
host: myhost
hOst: myhost2
Host: dummy.restapiexample.com
X-B3-TraceId: 023283cd77be2eba
```

**Comment by yufangong** [comment]
@DanielCharczynski , sorry I missed your response before. I think `RequestBuilder` doesn't have a consistent behavior to treat headers case insensitive, it doesn't align with building directly with request.headerMap.set("xx", "yy;zz"). I'm going to put up a fix. Thanks for reporting!

**Comment by yufangong** [comment]
Hey @DanielCharczynski, we put up a fix for this here https://github.com/twitter/finagle/commit/535f324c8255f87f7848ad927759dac63888ad22. Feel free to test against the develop branch. The April release will have this fix.
I'm closing this one, If you still experience issues, please open another one.
