### ISSUE TITLE
finagle http can not work with kerberos 

### ISSUE THREAD

**Issue by sydt2014** [twitter/finagle#836]
When finagle http visit service with kerberos seecurity, it need authorization.

It occurs :
No.LoginModules.configured.for.name
this is because some code lack kerberos configuration in 
com.twitter.finagle.http.SpnegoAuthenticator  
line 149:
 portalOption = Some(new LoginContext(loginContext))
the LoginContext() lack configuration about kerberos like this:

  return new AppConfigurationEntry[]{new AppConfigurationEntry("com.sun.security.auth.module.Krb5LoginModule",
                        AppConfigurationEntry.LoginModuleControlFlag.REQUIRED, new HashMap<String, Object>() {
                    {
                        put("useTicketCache", "true");
                        put("useKeyTab", "false");
//                        put("keyTab", keyTabLocation);
                        //Krb5 in GSS API needs to be refreshed so it does not throw the error
                        //Specified version of key is not available
                        put("refreshKrb5Config", "true");
                        put("principal", principal);
                        put("storeKey", "false");
                        put("doNotPrompt", "true");
                        put("isInitiator", "true");
                        put("debug", isDebugStr);
                        put("ticketCache", ticketCachePath);
                    }
                })};
So it needs kerberos configuration such as keytab file or ticket cache

**Comment by sydt2014** [comment]
It can not work because there is no kerberos configuration!!!

**Comment by sydt2014** [comment]
The correct code is 
new LoginContext(loginContext,null,null,new AppConfigurationEntry[] )

**Comment by ryanoneill** [comment]
Hi @sydt2014, I believe everyone using this internally does so through the use of two system properties:
* java.security.auth.login.config
* java.security.auth.login.context

I am not sure of the specifics as this isn't code that any of us have looked at deeply in a long time. This code is mostly maintained by the folks at Twitter who are actively using it, and it is used quite extensively for multiple Kerberos systems.
