### ISSUE TITLE
Move FinagleMDCAdapter from Finatra to Finagle

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#850]
Move the [`FinagleMDCAdapter`](https://github.com/twitter/finatra/blob/develop/inject/inject-slf4j/src/main/scala/com/twitter/inject/logging/FinagleMDCAdapter.scala) from Finatra to Finagle as it is usable for everyone using Finagle and doesn't contain Finatra logic.

### Expected behavior

I want to be able to hook MDC to Finagle's context without having to depend on Finatra as well.

**Comment by ryanoneill** [comment]
Hi @spockz, entirely reasonable request and understandable. Finagle, unfortunately, still depends on the ancient `com.twitter.logging` (based on JUL), and not slf4j, yet. It's on our roadmap, but other work consistently jumps ahead of that migration. Until that's in place, I don't see something like `FinagleMDCAdapter`, which depends on slf4j types, being moved into Finagle proper. Once Finagle depends on slf4j though, sure.

With that said, @cacoco [just this week moved that file to an 'inject-mdc'](https://github.com/twitter/finatra/commit/daf8716d2833854cc5c80b7a521897ae908a1273) package. While it's inside of 'Finatra', it's really a standalone item, and depending on that that doesn't mean that you're depending on any of the internals of Finatra. Hope that works for you.

**Comment by cacoco** [comment]
As @ryanoneill mentioned, that functionality is now fairly separated with dependencies only on finagle-core, util-core, our slf4j-api scala wrapper (util-slf4j-api), and the slf4j-api itself. 

There is a cross module dependency on Finatra's slf4j-api scala wrapper but its dependencies are again util-core, util-slf4j-api, and the slf4j-api...along with Jackson -- which isn't ideal and we're working to move away from in the Finatra slf4j-api scala wrapper.

Until Finagle adopts the slf4j-api for framework logging this code will likely not appear in Finagle. Finatra is currently the only place with the correct confluence of dependencies.

**Comment by spockz** [comment]
@ryanoneill and @cacoco having a separate module in Finatra works for me as well.

I think we can close this as I don't expect Finagle to go to SLF4J any time soon. :)

**Comment by enbnt** [comment]
Thanks @spockz, closing this out.
