### ISSUE TITLE
Creating your own Services

### ISSUE THREAD

**Issue by olib963** [twitter/finagle#853]
I cannot find in the docs a way to create a `Service[NotRequest, NotResponse]`, perhaps I am missing something obvious but I am wondering if you need to recreate the whole stack.

### Expected behavior

I would like to be able to extend the `Request` and `Response` types to create a `Service[AuthorisedRequest, MonitoredResponse]`.

### Actual behavior

I can implement a `Filter[Reqest, Response, AuthorisedRequest, MonitoredResponse]` but I don't know how to create endpoints etc. that can be integrated with these types. Ideally I would like something like this as a trivial case:

```
// Healthchecks
val ping = get("ping"){_ => Ok("pong")}
val healthService = Bootstrap.serve[Plaintext](ping).toService

// Authorised endpoints
val hello = withRole("foo")(get("/hello"){_ =>
 Ok(Timed(Duration.ofMillis(10), value = "world"))
})

val otherEndpoint = // more of the same

val authedService = (hello :+: otherEndpoint) // Somehow turn into Service[AuthorisedRequest, MonitoredResponse]

// Server to run
val server = healthService andThen (MyFilter andThen authedService)
```

I can see that you have the `com.twitter.finagle.http.SpnegoAuthenticator` that does a similar transformation on the request but I am unsure how to use it. Perhaps someone could point me in the direction of documentation for using a `Filter`?

**Comment by cacoco** [comment]
Hi there,

I think you're looking for [Service.mk](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/Service.scala#L28)? This will allow you to easily create a `Service[YourRequestType, YourResponseType]`.

```
val svc: Service[AuthorisedRequest, MonitoredResponse] = 
  Service.mk[AuthorisedRequest, MonitoredResponse] { request: AuthorisedRequest =>
    ???
  }
```

I would highly recommend reading through the [Finagle User's Guide](http://twitter.github.io/finagle/guide/) if you haven't already. There's a section specifically about [Services & Filters](http://twitter.github.io/finagle/guide/ServicesAndFilters.html) which may also help.

As for "endpoints", Finagle is a fairly low-level protocol agnostic RPC library. The syntax you're describing `get("ping"){_ => Ok("pong")}` does not exist in Finagle, though something similar does in [Finatra](http://twitter.github.io/finatra/) and I would also recommend taking a look through the [User's Guide](https://twitter.github.io/finatra/user-guide/) there for more information.

**Comment by olib963** [comment]
I am very sorry. I appear to have opened the issue on the wrong project! I hope you have a nice day and thank you for taking the time to look into it anyway!
