### ISSUE TITLE
MethodBuilder from the HTTP stack doesn't allow `.withTraceInitializer`

### ISSUE THREAD

**Issue by plaflamme** [twitter/finagle#857]
`http.MethodBuilder` hides the `.withTraceInitializer` method on the underlying `client.MethodBuilder`.

### Expected behavior

It should be possible to call `.withTraceInitializer` on `http.MethodBuilder`.

### Actual behavior

`http.MethodBuilder` hides `client.Methodbuilder.withTraceInitializer`

### Steps to reproduce the behavior

N/A

**Comment by hamdiallam** [comment]
Thanks! Are you interested in submitting a PR to support this?

**Comment by plaflamme** [comment]
Sure: https://github.com/twitter/finagle/pull/858

**Comment by hamdiallam** [comment]
Closing this as it was merged
