### ISSUE TITLE
Set own ExecutionContext in Twitter future

### ISSUE THREAD

**Issue by politrons** [twitter/finagle#860]
Hi I´m reading the documentation regarding the Futures and Context where to execute them https://twitter.github.io/finagle/guide/Contexts.html

But I cannot find a way to pass to finagle to use my own ExecutionContext as you can do with Scala future. 
There's any way to do that?.

Regards.

**Comment by hamdiallam** [comment]
Hey, I believe what you're looking for is a `FuturePool`, https://twitter.github.io/util/docs/com/twitter/util/FuturePool$.html

You can create a FuturePool backed by a supplied ExecutorService. The work in the `apply` will be scheduled but the Executor along the continuations on the returned future.

**Comment by politrons** [comment]
How is this FuturePool used once I created?. Finagle Service does not apply a function param for this FuturePool. shall I defined as implicit like Scala Future allow and that's it?. Sorry I´m little bit lost here.

**Comment by hamdiallam** [comment]
No problem, I understand the confusion.

Some clarity around what you are trying to accomplish would be helpful. In terms of `Finagle Service`, is your intention to use your own Scheduler for finagle threads? Or are you trying to simply trying to perform some computation asynchronously using a provided Executor?

By default, all of Finagle's futures are scheduled using the [FinagleScheduler](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/exp/FinagleScheduler.scala). This can be configured or entirely swapped if this is what you're looking to configure (i do not recommend). [Scheduler.setUnsafe](https://github.com/twitter/util/blob/develop/util-core/concurrent-extra/src/main/scala/com/twitter/concurrent/Scheduler.scala#L74)

If you're simply looking to do some computation into another thread pool that's backed by your own Executor, this is where `FuturePools` come in. For example

```
val pool = FuturePool(Executors.newFixedThreadPool(2))
val interruptibleThreadPool = FuturePool.interruptible(Executors.defaultThreadPool())

val myResult: Future[SomeTypeGoesHere] = pool {
 someReallyExpensiveComputation() // will be scheduled on the executor backing `pool`
}
```

`FuturePool` already comes with a default executor if you're just looked to just offload some computations

```
val fooBarResult: Future[fooBarReturnType] = FuturePool.unboundedPool {
  fooBar() // scheduled using the default executor
}
```

However, the global Scheduler is what is responsible for scheduling the submitted Runnables to corresponding threads (FinagleScheduler or one that you set).
The `com.twitter.finagle.exp.scheduler` flags provides some options for schedulers provided by Finagle

**Comment by politrons** [comment]
How would you use a FuturePool with a Finagle `Service` created?.

What I want is to make the request of the Finagle Service running in a particular` ExecutionContext`


`FuturePool(Executors.newFixedThreadPool(2)).Future().flatMap(_ => service(request) this is terrible 😅`

**Comment by hamdiallam** [comment]
I see. Have you looked using the Offloading functionality in Finagle, https://twitter.github.io/finagle/guide/ThreadingModel.html#offloading?

The threads used by Finagle are IO threads. Blocking these threads will impact performance. Using the offload filter to run your application code in a dedicated thread pool would mitigate this.

For example, 14 worker (application) threads and 14 IO threads. 
`-com.twitter.finagle.offload.numWorkers=14 -com.twitter.finagle.netty4.numWorkers=10`

I believe this would give you the behavior you're looking for if I'm not mistaken

**Comment by politrons** [comment]
I´m afriad I cannot use offloading in our mandatory version 18.11.0 😒

**Comment by hamdiallam** [comment]
Ah, I didn't realize you also posted #861 

The offload filter can still be applied manually to your client/server stacks. Did you get a change to see my latest comment there?

**Comment by politrons** [comment]
Hi,

Yes I was trying now to apply that code. I guess is just the Client class which is a filter right?.

Can I use composition with andThen using that class?

Enviado desde mi iPhone

**Comment by hamdiallam** [comment]
yep!

It would look something like this
```
val offloadWorkerPool = FuturePool(Executors.newCachedThreadPool(14) // application worker pool
val offloadClientFilter = new OffloadFilter.Client(offloadWorkerPool)
val rawHttpClient = Http.client.newService("twitter.com:80")
val client = offloadClientFilter.andThen(rawHttpClient)

client(Request("/")).map { resp =>
  // this code will not be running on an IO Finagle thread
  // and instead one of the offload threads i
  handleResp()
}
```

Be sure to share the `offloadWorkerPool` so that the same worker pool is used across your various clients. A similar process can be used for the offloading your server code.

The number of IO threads by default is the number of cores on the machine. If you'd like to change that, this flag should still be available to you
`-com.twitter.finagle.netty4.numWorkers=<num io threads>`

**Comment by politrons** [comment]
Yep I just create my own Filter and I add it the Service

  ```
private val pool: ExecutorServiceFuturePool = FuturePool(executorService)

  def withCustomExecutionContext: () => Filter[Request, Response, Request, Response] = () =>
    (request: Request, service: Service[Request, Response]) => {
      val response = service(request)
      val shifted = Promise.interrupts[Response](response)
      response.respond { tryResponse =>
        pool(shifted.update(tryResponse))
      }
      shifted
    }

filters.withCustomExecutionContext())
      .andThen(getService(requestInfo))
```

Unfortunately  no improvement so far. I will continue investigating. 
Thanks a lot for all the support

**Comment by hamdiallam** [comment]
hm interesting. I would also recommend profiling your service/code to find blocking threads, making sure they aren't finagle threads

**Comment by politrons** [comment]
I´ve been playing with visualVM and I can see the 100 threads of the FuturePool that I created, but they are park, and I can only see the 24 threads of finagle/netty4 running.

I dont think the interrupt and shifted is working as we expect. Also I think even if it worked the filter is applied when I receive the response, but that's too late all the blocking part are the 500ms I´m waiting for the response between only 24 threads. So I end up blocking the main even loop threads of my app (10 threads) waiting for default Finagle pool to obtain a thread.

**Comment by politrons** [comment]
Hi again I made a very simple example, and watching threads with `VisualVM` I cannot being able to make the Future to being interrupted and passed the execution into one Thread of the `FuturePool`

```
object TestFuturePool extends App {

  private val pool: ExecutorServiceFuturePool = FuturePool(Executors.newFixedThreadPool(100))

  Thread.sleep(30000)
  while (true) {

    val future: Future[String] = Future {
      Thread.sleep(500)
      "Hello world!"
    }.interruptible()

    val shifted: Promise[String] = Promise.interrupts[String](future)

    future.respond(tryResponse => {
      pool(shifted.update(tryResponse))
    })

    Thread.sleep(200)

  }

}
```

**Comment by politrons** [comment]
I make it work a little example with this code, what do you think?

```
object TestFuturePool extends App {

  private val pool: ExecutorServiceFuturePool = FuturePool(Executors.newFixedThreadPool(10))

  while (true) {

    val shifted = Promise[Unit]()

    pool(shifted.become(Future {
      Thread.sleep(500)
      println(s"Hello world! in ${Thread.currentThread().getName}")

    }))

    Thread.sleep(200)

  }
  
}
```

**Comment by hamdiallam** [comment]
Closing in favor of #862
