### ISSUE TITLE
withExecutionOffloaded in 18.11.0 version

### ISSUE THREAD

**Issue by politrons** [twitter/finagle#861]
hi all, with version 18.11.0 how can use this `Offloading` as is described in this example code https://twitter.github.io/finagle/guide/ThreadingModel.html

```
val client: Http.Client = Http.client
  .withExecutionOffloaded(FuturePool.unboundedPool)
```

I cannot find `withExecutionOffloaded` as part of `Http.client` in my version. And I´m afraid upgrade is not an option.

Basically I need to configure my own `ExecutionContext`. Any other solution for my current version?

Regards

**Comment by hamdiallam** [comment]
The OffloadFilter is a relatively new feature. 18.11.0 is a release from two years ago which does not include the changes where the OffloadFilter and `withExecutionOffloaded` api was introduced.

If upgrading is not an option, you can copy the filter code into your app and compose it with your Http client. It's relatively simple. [Client Filter](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/filter/OffloadFilter.scala#L61).

Some [documentation](https://twitter.github.io/finagle/guide/ServicesAndFilters.html#composing-filters-and-services) around composing custom filters.

**Comment by hamdiallam** [comment]
Is it okay if I close this issue?

**Comment by politrons** [comment]
sure
