### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [twitter/finagle#878]
The README file in this repo has a bad link - [404:NotFound]

### Expected behavior

Link should work and I think it should point to here:
https://github.com/twitter/code-of-conduct/blob/master/code-of-conduct.md

### Actual behavior

When clicking: “Open Source Code of Conduct”
Status code [404:NotFound] - Link: https://github.com/twitter/code-of-conduct/blob/release/code-of-conduct.md

### Steps to reproduce the behavior

Click the link under “Open Source Code of Conduct”

### additional

This bad link was found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3A%2F%2Fgithub.com%2Ftwitter%2Ffinagle
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=twitter

If this has been in any way helpful then please consider giving the above Repo a Star.
If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by ryanoneill** [comment]
Covered by PR https://github.com/twitter/finagle/commit/e169f083d6d2721bf6ae431fa9f0db3370960330
