### ISSUE TITLE
Use of Jackson 2.12.0

### ISSUE THREAD

**Issue by SerCeMan** [twitter/finagle#885]
Hi, finagle maintainers!

Jackson has recently version [released 2.12](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12) and finagle currently depends on 2.11.2
https://github.com/twitter/finagle/blob/c4dc4fdc5beedec031a5af25a512e5319843f02b/build.sbt#L64-L70

I was wondering if there are any know issues that could prevent finagle from using 2.12.0 or using finagle with a transitive jackson dependency on 2.12.0

**Comment by yufangong** [comment]
Hi Sergey,

That's cool! Can you open an issue on GitHub propose a version bump and we
can start testing with the new version!
Thank you!

Yufan

**Comment by yufangong** [comment]
Thanks, @SerCeMan. We will schedule some testing and see if we can bump the Jackson version!

**Comment by SerCeMan** [comment]
Hey, @yufangong! Thanks, I created a pull request here: https://github.com/twitter/finagle/pull/886.

**Comment by SerCeMan** [comment]
Just a note, a patch version, `2.12.1`, [was recently released](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12.1).

**Comment by tigerlily-he** [comment]
Hi @SerCeMan, The January 2022 release of Finagle has the Jackson upgrade to 2.13.1. https://github.com/twitter/finagle/commit/831b25120addc828b7de83ae20dfbc7c2606125a.
