### ISSUE TITLE
Finagle-Thrift streaming documentation not found

### ISSUE THREAD

**Issue by politrons** [twitter/finagle#899]
Hi all,

So sorry if this request is in the wrong place. I'm plating with the Finagle-thrift library and I manage to create a functional example using a thrift file where I define the contract for there RPC call.
The part that I'm completely missing and I not able to find the in the whole internet, is an example of how can we use streaming with Finagle-Thrift.

Something similar as we use for HTTP in Finagle with ```withStreaming(enabled = true)```  and using the ```reader``` and ```writable```

Somebody know a good code base or documentation that I might follow?

Regards

**Comment by yufangong** [comment]
Sorry for the delay, Finagle doesn't have Thrift streaming support as of now, could you please share your use case a bit more? Is the large payload that drives to enable streaming or any other case. Thanks!
