### ISSUE TITLE
A link is expired

### ISSUE THREAD

**Issue by 24kpure** [twitter/finagle#914]
`http://www.eckner.com/papers/ts_alg.pdf` is expired and `http://www.eckner.com/papers/Algorithms%20for%20Unevenly%20Spaced%20Time%20Series.pdf` maybe the new link in file
`https://github.com/twitter/finagle/blob/1bc837c4feafc0096e43c0e98516a8e1c50c4421/finagle-core/src/main/scala/com/twitter/finagle/loadbalancer/PeakEwma.scala`

**Comment by tigerlily-he** [comment]
Thanks @24kpure! Can you make a PR to fix the link?

**Comment by 24kpure** [comment]
With a pleasure.

**Comment by tigerlily-he** [comment]
Fixed in https://github.com/twitter/finagle/commit/ad0c9d12ad053374a93c6f00b2902c5c251523c3
