### ISSUE TITLE
Finagle 21.10.0 artifacts are not found on Maven central

### ISSUE THREAD

**Issue by xerial** [twitter/finagle#920]
**Describe the bug**

Some artifact files of Finagle 21.10.0 return 404 not found error at the Maven repository. For example, this pom file for Scala 2.12 and Finagle 21.10.0 is not found:
https://repo1.maven.org/maven2/com/twitter/finagle-core_2.12/21.10.0/finagle-core_2.12-21.10.0.pom

**Expected behavior**

These files become readable at Maven central.

**Screen shot**
Files are already indexed https://repo1.maven.org/maven2/com/twitter/finagle-core_2.12/21.10.0/, but some of these file contents are empty:
![image](https://user-images.githubusercontent.com/57538/140173540-85a0a279-4de9-4596-a2c9-3b206bb3fa1e.png)

**Environment**
Any web browsers.

**Additional context**

I once hit this issue when Sonatype had a caching issue on their CDN. It would be better to file an issue ticket like this to Sonatype JIRA:
https://issues.sonatype.org/browse/OSSRH-54502?filter=-2

**Comment by xerial** [comment]
Files become visble. Let me close the issue. Thanks

**Comment by joybestourous** [comment]
Hey @xerial , yes this should now be resolved. We filed a similar ticket to the one you linked with Sonatype on Friday and they fixed the issue shortly after. Thanks for filing the ticket and helping us resolve this more quickly! Cheers!
