### ISSUE TITLE
Non-blocking DNS resolution

### ISSUE THREAD

**Issue by fwbrasil** [twitter/finagle#929]
**Is your feature request related to a problem? Please describe.**

We use DNS at Nubank to resolve names and the blocking behavior of the DNS resolution is a problem for one of our services that distributes requests to several other services. It often has a large number of threads doing DNS resolution and that contributes to CPU throttling. Example:

![image](https://user-images.githubusercontent.com/831175/167690924-ca4d1785-7b39-4592-974a-817aad79cfa2.png)

**Describe the solution you'd like**

Finagle should support non-blocking DNS resolution by default or by configuration.

**Describe alternatives you've considered**

We can use the service loading mechanism introduced by https://github.com/twitter/finagle/commit/e9e2239e7fa0bc15dabd5a84ac3a9c3575e09844 and have a separate implementation but I it'd be great if Finagle had this feature built in.

**Additional context**

I worked on an async DNS resolver as part of the fiber scheduler project (see earlier phab versions, I think I removed it eventually when the kafka client wasn't a problem anymore). It'd be great if it could be open sourced.

**Comment by heligw** [comment]
we have created a ticket to look into it, we'll reach out to you when we have updates. thanks!

**Comment by vkostyukov** [comment]
Hey @fwbrasil, I'm working on it. I have a draft phab that I'm testing internally at the moment.

**Comment by fwbrasil** [comment]
awesome news folks! Thank you very much :)

**Comment by vkostyukov** [comment]
It took us a while but it's landed! https://github.com/twitter/finagle/commit/ca456b8e1f905f02e032b52a773af3c7fdaa4d3b

It's behind a toggle if you want to enable it for your apps. Will do more testing internally before enabling it by default.

**Comment by fwbrasil** [comment]
nice! this is going to be very helpful, thank you!!!

**Comment by fwbrasil** [comment]
@vkostyukov are there plans to make a new release with this change?

**Comment by vkostyukov** [comment]
Yea, this should make it into the July release.

Update: We do publish snapshots nightly, maybe you want to try depending on them in the meantime?
