### ISSUE TITLE
DeadlineFilter takes `rejectWithdrawal` regardless of passed Deadline

### ISSUE THREAD

**Issue by DieBauer** [twitter/finagle#936]
**Describe the bug**
The DeadlineFilter will always take a `rejectWithdrawal` (default 5000) amount of tokens, while only restoring `serviceDeposit` (default 1000 tokens), in case rejection is not required. 

**Expected behavior**
Tokens get only withdrawn when the deadline is truly passed, as it was before the [Traceability PR](https://github.com/twitter/finagle/commit/e1b33abc67f1811260f0ba62793bce1043f9a3e5). 

**Additional context**
https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/service/DeadlineFilter.scala#L283

**Comment by xin301x** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
