### ISSUE TITLE
Upgrade to netty 4.1.86.Final in Finagle 

### ISSUE THREAD

**Issue by kumarbairesh** [twitter/finagle#945]
**Describe the bug**
@tigerlily-he @mosesn The Finagle version of 22.12.0 does it have the netty version 4.1.86.Final ?? Because the following CVE's are fixed in this netty version, Can you help which version of netty is present in the latest Finagle??
CVE ID: https://github.com/advisories/GHSA-fx2c-96vj-985v
CVSS score: 7.5
Description: Netty project is an event-driven asynchronous network application framework. In versions prior to 4.1.86.Final, a StackOverflowError can be raised when parsing a malformed crafted message due to an infinite recursion. This issue is patched in version 4.1.86.Final. There is no workaround, except using a custom HaProxyMessageDecoder.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by kumarbairesh** [comment]
@tigerlily-he. @mosesn Any update on this ?

**Comment by kumarbairesh** [comment]
@tigerlily-he  @mosesn  An update on this ?

**Comment by mattdickinson5** [comment]
see https://github.com/twitter/finagle/commit/83e31f81361430a427fe9d4b636419b52d42542c
